function(){return function(){var h,aa=this;function l(a){return void 0!==a}function m(a){return"string"==typeof a}function ba(a){return"number"==typeof a}function ca(a,b){a=a.split(".");var c=aa;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ea(a){return"function"==da(a)}function fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ga(a,b,c){return a.call.apply(a.bind,arguments)}
function ha(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ia(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia=ga:ia=ha;return ia.apply(null,arguments)}
function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var la=Date.now||function(){return+new Date};function p(a,b){function c(){}c.prototype=b.prototype;a.ka=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ia=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var ma=window;function q(a,b){this.code=a;this.a=r[a]||na;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}p(q,Error);var na="unknown error",r={15:"element not selectable",11:"element not visible"};r[31]=na;r[30]=na;r[24]="invalid cookie domain";r[29]="invalid element coordinates";r[12]="invalid element state";
r[32]="invalid selector";r[51]="invalid selector";r[52]="invalid selector";r[17]="javascript error";r[405]="unsupported operation";r[34]="move target out of bounds";r[27]="no such alert";r[7]="no such element";r[8]="no such frame";r[23]="no such window";r[28]="script timeout";r[33]="session not created";r[10]="stale element reference";r[21]="timeout";r[25]="unable to set cookie";r[26]="unexpected alert open";r[13]=na;r[9]="unknown command";q.prototype.toString=function(){return this.name+": "+this.message};var oa={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};function pa(a){if(Error.captureStackTrace)Error.captureStackTrace(this,pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}p(pa,Error);pa.prototype.name="CustomError";var qa;function ra(a,b){this.width=a;this.height=b}h=ra.prototype;h.toString=function(){return"("+this.width+" x "+this.height+")"};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};h.scale=function(a,b){b=ba(b)?b:a;this.width*=a;this.height*=b;return this};function sa(a,b){var c=ta;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};function ua(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var va=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function wa(a,b){var c=0;a=va(String(a)).split(".");b=va(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;!c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=xa(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||xa(0==f[2].length,0==g[2].length)||xa(f[2],g[2]);f=f[3];g=g[3]}while(!c)}return c}function xa(a,b){return a<b?-1:a>b?1:0}
function ya(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function za(a,b,c){this.a=a;this.b=b||1;this.f=c||1};function Aa(a){this.b=a;this.a=0}function Ba(a){a=a.match(Ca);for(var b=0;b<a.length;b++)Da.test(a[b])&&a.splice(b,1);return new Aa(a)}var Ca=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,Da=/^\s/;function t(a,b){return a.b[a.a+(b||0)]}function u(a){return a.b[a.a++]}function Ea(a){return a.b.length<=a.a};function v(a){pa.call(this,a)}p(v,pa);var Fa;a:{var Ga=aa.navigator;if(Ga){var Ha=Ga.userAgent;if(Ha){Fa=Ha;break a}}Fa=""}function y(a){return-1!=Fa.indexOf(a)};function z(a,b){this.j=a;this.c=l(b)?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function Ia(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}z.prototype.a=function(a){return null===this.b||this.b==a.nodeType};z.prototype.f=function(){return this.j};
z.prototype.toString=function(){var a="Kind Test: "+this.j;null===this.c||(a+=A(this.c));return a};function Ja(a,b){this.l=a.toLowerCase();a="*"==this.l?"*":"http://www.w3.org/1999/xhtml";this.c=b?b.toLowerCase():a}Ja.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=l(a.localName)?a.localName:a.nodeName;return"*"!=this.l&&this.l!=b.toLowerCase()?!1:"*"==this.c?!0:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Ja.prototype.f=function(){return this.l};
Ja.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.l};function Ka(a){switch(a.nodeType){case 1:return ka(Ma,a);case 9:return Ka(a.documentElement);case 11:case 10:case 6:case 12:return Na;default:return a.parentNode?Ka(a.parentNode):Na}}function Na(){return null}function Ma(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Ma(a.parentNode,b):null};function Oa(a,b){return(new RegExp(a)).test(b)}function Pa(a,b){return(new RegExp(a,"i")).test(b)}function Qa(a){a=a.replace(/([.^$+(){}\[\]\\|])/g,"\\$1");a=a.replace(/\?/g,"(.|[\r\n])");return a=a.replace(/\*/g,"(.|[\r\n])*")}var Ra={exact:function(a,b){return-1!=b.indexOf(a)},glob:function(a,b){return(new RegExp("^"+Qa(a)+"$")).test(b)},globcontains:function(a,b){return(new RegExp(Qa(a))).test(b)},regex:Oa,regexi:Pa,regexpi:Pa,regexp:Oa};
function Sa(a){var b="glob",c=/^([a-zA-Z-]+):(.*)/.exec(a);if(c){var d=c[1],c=c[2];Ra[d.toLowerCase()]&&(b=d.toLowerCase(),a=c)}d=Ra[b];if(!d)throw new v("Cannot find pattern matching strategy: "+b);"glob"==b?(a.indexOf("glob:")||(a=a.substring(5)),d=Ra.glob):"exact"!=b||a.indexOf("exact:")||(a=a.substring(6));a=ka(d,a);a.ja=b;return a};function Ta(a,b){if(m(a))return m(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function B(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function Ua(a,b){for(var c=a.length,d=[],e=0,f=m(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d}function Va(a,b,c){var d=c;B(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}
function Wa(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function Xa(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}function Ya(a,b){a:{for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:m(a)?a.charAt(b):a[b]}function Za(a){return Array.prototype.concat.apply([],arguments)}
function $a(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function ab(){return y("iPhone")&&!y("iPod")&&!y("iPad")};var bb="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),cb=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,db=/^#(?:[0-9a-f]{3}){1,2}$/i,eb=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,fb=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;var gb={v:function(a,b){if(""===a)throw new q(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},w:function(a,b){if(""===a)throw new q(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};function hb(){return(y("Chrome")||y("CriOS"))&&!y("Edge")};function ib(a,b){this.x=l(a)?a:0;this.y=l(b)?b:0}h=ib.prototype;h.toString=function(){return"("+this.x+", "+this.y+")"};h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};h.scale=function(a,b){b=ba(b)?b:a;this.x*=a;this.y*=b;return this};var jb=y("Opera"),C=y("Trident")||y("MSIE"),kb=y("Edge"),lb=y("Gecko")&&!(-1!=Fa.toLowerCase().indexOf("webkit")&&!y("Edge"))&&!(y("Trident")||y("MSIE"))&&!y("Edge"),mb=-1!=Fa.toLowerCase().indexOf("webkit")&&!y("Edge"),nb=y("Macintosh"),ob=y("Windows");function pb(){var a=aa.document;return a?a.documentMode:void 0}var qb;
a:{var rb="",sb=function(){var a=Fa;if(lb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(kb)return/Edge\/([\d\.]+)/.exec(a);if(C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(mb)return/WebKit\/(\S+)/.exec(a);if(jb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();sb&&(rb=sb?sb[1]:"");if(C){var tb=pb();if(null!=tb&&tb>parseFloat(rb)){qb=String(tb);break a}}qb=rb}var ta={};function ub(a){return sa(a,function(){return 0<=wa(qb,a)})}var vb;var wb=aa.document;
vb=wb&&C?pb()||("CSS1Compat"==wb.compatMode?parseInt(qb,10):5):void 0;function xb(a,b,c,d){this.c=a;this.a=b;this.b=c;this.f=d}h=xb.prototype;h.toString=function(){return"("+this.c+"t, "+this.a+"r, "+this.b+"b, "+this.f+"l)"};h.contains=function(a){return this&&a?a instanceof xb?a.f>=this.f&&a.a<=this.a&&a.c>=this.c&&a.b<=this.b:a.x>=this.f&&a.x<=this.a&&a.y>=this.c&&a.y<=this.b:!1};h.ceil=function(){this.c=Math.ceil(this.c);this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.f=Math.ceil(this.f);return this};
h.floor=function(){this.c=Math.floor(this.c);this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.f=Math.floor(this.f);return this};h.round=function(){this.c=Math.round(this.c);this.a=Math.round(this.a);this.b=Math.round(this.b);this.f=Math.round(this.f);return this};h.scale=function(a,b){b=ba(b)?b:a;this.f*=a;this.a*=a;this.c*=b;this.b*=b;return this};function yb(a,b){this.B={};this.o=[];this.a=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof yb){d=zb(a);Ab(a);var e=[];for(c=0;c<a.o.length;c++)e.push(a.B[a.o[c]])}else{var c=[],f=0;for(d in a)c[f++]=d;d=c;c=[];f=0;for(e in a)c[f++]=a[e];e=c}for(c=0;c<d.length;c++)this.set(d[c],e[c])}}function zb(a){Ab(a);return a.o.concat()}
function Ab(a){var b,c;if(a.a!=a.o.length){for(b=c=0;c<a.o.length;){var d=a.o[c];Object.prototype.hasOwnProperty.call(a.B,d)&&(a.o[b++]=d);c++}a.o.length=b}if(a.a!=a.o.length){var e={};for(b=c=0;c<a.o.length;)d=a.o[c],Object.prototype.hasOwnProperty.call(e,d)||(a.o[b++]=d,e[d]=1),c++;a.o.length=b}}yb.prototype.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.B,a)?this.B[a]:b};
yb.prototype.set=function(a,b){Object.prototype.hasOwnProperty.call(this.B,a)||(this.a++,this.o.push(a));this.B[a]=b};var Bb=y("Firefox"),Cb=ab()||y("iPod"),Db=y("iPad"),Eb=y("Android")&&!(hb()||y("Firefox")||y("Opera")||y("Silk")),Fb=hb(),Gb=y("Safari")&&!(hb()||y("Coast")||y("Opera")||y("Edge")||y("Silk")||y("Android"))&&!(ab()||y("iPad")||y("iPod"));var Hb=C&&!(9<=Number(vb)),Ib=C&&!(8<=Number(vb));function D(a,b,c,d){this.a=a;this.b=b;this.width=c;this.height=d}h=D.prototype;h.toString=function(){return"("+this.a+", "+this.b+" - "+this.width+"w x "+this.height+"h)"};h.contains=function(a){return a instanceof ib?a.x>=this.a&&a.x<=this.a+this.width&&a.y>=this.b&&a.y<=this.b+this.height:this.a<=a.a&&this.a+this.width>=a.a+a.width&&this.b<=a.b&&this.b+this.height>=a.b+a.height};
h.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.scale=function(a,b){b=ba(b)?b:a;this.a*=a;this.width*=a;this.b*=b;this.height*=b;return this};function Jb(a){return(a=a.exec(Fa))?a[1]:""}var Kb=function(){if(Bb)return Jb(/Firefox\/([0-9.]+)/);if(C||kb||jb)return qb;if(Fb)return ab()||y("iPad")||y("iPod")?Jb(/CriOS\/([0-9.]+)/):Jb(/Chrome\/([0-9.]+)/);if(Gb&&!(ab()||y("iPad")||y("iPod")))return Jb(/Version\/([0-9.]+)/);if(Cb||Db){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Fa);if(a)return a[1]+"."+a[2]}else if(Eb)return(a=Jb(/Android\s+([0-9.]+)/))?a:Jb(/Version\/([0-9.]+)/);return""}();function Lb(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Mb(a,b){var c=Ib&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Lb(b,a,b.nodeName,c)};var Nb={},Ob,Pb;function Qb(a){return Rb?Ob(a):C?0<=wa(vb,a):ub(a)}function Sb(a){return Rb?Pb(a):Eb?0<=wa(Tb,a):0<=wa(Kb,a)}
var Rb=function(){if(!lb)return!1;var a=aa.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;Ob=function(a){return 0<=c.compare(d,""+a)};Pb=function(a){return 0<=c.compare(e,""+a)};return!0}(),Ub;if(Eb){var Vb=/Android\s+([0-9\.]+)/.exec(Fa);Ub=Vb?Vb[1]:"0"}else Ub="0";
var Tb=Ub,Wb=C&&!(8<=Number(vb)),Xb=C&&!(9<=Number(vb));Eb&&Sb(2.3);Eb&&Sb(4);Gb&&Sb(6);function Yb(a){return a?new Zb(E(a)):qa||(qa=new Zb)}
function $b(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){d=a.getElementsByClassName(c);if(e){a={};for(var f=b=0,g;g=d[f];f++)e==g.nodeName&&(a[b++]=g);a.length=b;return a}return d}d=a.getElementsByTagName(e||"*");if(c){a={};for(f=b=0;g=d[f];f++){var e=g.className,k;if(k="function"==typeof e.split)k=0<=Ta(e.split(/\s+/),c);k&&(a[b++]=g)}a.length=b;return a}return d}
function ac(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function bc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function cc(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(C&&!(9<=Number(vb))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?dc(a,b):!c&&bc(e,b)?-1*ec(a,b):!d&&bc(f,a)?ec(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=E(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(aa.Range.START_TO_END,a)}function ec(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return dc(b,a)}function dc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function E(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var fc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},gc={IMG:" ",BR:"\n"};
function hc(a,b,c){if(!(a.nodeName in fc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in gc)b.push(gc[a.nodeName]);else for(a=a.firstChild;a;)hc(a,b,c),a=a.nextSibling}function ic(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function Zb(a){this.a=a||aa.document||document}Zb.prototype.getElementsByTagName=function(a,b){return(b||this.a).getElementsByTagName(String(a))};
function jc(a,b,c,d){return $b(a.a,b,c,d)}Zb.prototype.contains=bc;function F(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(Hb&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),Hb&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function kc(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}Ib&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function lc(a,b,c,d,e){return(Hb?mc:nc).call(null,a,b,m(c)?c:null,m(d)?d:null,e||new G)}
function mc(a,b,c,d,e){if(a instanceof Ja||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;var g=oc(a);if("*"!=g&&(f=b.getElementsByTagName(g),!f))return e;if(c){var k=[];for(a=0;b=f[a++];)kc(b,c,d)&&k.push(b);f=k}for(a=0;b=f[a++];)"*"==g&&"!"==b.tagName||H(e,b);return e}pc(a,b,c,d,e);return e}
function nc(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!C?(b=b.getElementsByName(d),B(b,function(b){a.a(b)&&H(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),B(b,function(b){b.className==d&&a.a(b)&&H(e,b)})):a instanceof z?pc(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),B(b,function(a){kc(a,c,d)&&H(e,a)}));return e}
function qc(a,b,c,d,e){var f;if((a instanceof Ja||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var g=oc(a);if("*"!=g&&(f=Ua(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=Ua(f,function(a){return kc(a,c,d)}));B(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||H(e,a)});return e}return rc(a,b,c,d,e)}function rc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)kc(b,c,d)&&a.a(b)&&H(e,b);return e}
function pc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)kc(b,c,d)&&a.a(b)&&H(e,b),pc(a,b,c,d,e)}function oc(a){if(a instanceof z){if(8==a.b)return"!";if(null===a.b)return"*"}return a.f()};function sc(a,b){b=b.toLowerCase();return"style"==b?tc(a.style.cssText):Wb&&"value"==b&&I(a,"INPUT")?a.value:Xb&&!0===a[b]?String(a.getAttribute(b)):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var uc=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function tc(a){var b=[];B(a.split(uc),function(a){var c=a.indexOf(":");0<c&&(a=[a.slice(0,c),a.slice(c+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function vc(a,b){Wb&&"value"==b&&I(a,"OPTION")&&null===sc(a,"value")?(b=[],hc(a,b,!1),a=b.join("")):a=a[b];return a}function I(a,b){b&&"string"!==typeof b&&(b=b.toString());return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};mb||lb&&Qb(3.5)||C&&Qb(8);var wc={F:function(a){return!(!a.querySelectorAll||!a.querySelector)},v:function(a,b){if(!a)throw new q(32,"No class name specified");a=va(a);if(-1!==a.indexOf(" "))throw new q(32,"Compound class names not permitted");if(wc.F(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new q(32,"An invalid or illegal class name was specified");}a=jc(Yb(b),"*",a,b);return a.length?a[0]:null},w:function(a,b){if(!a)throw new q(32,"No class name specified");a=va(a);if(-1!==a.indexOf(" "))throw new q(32,
"Compound class names not permitted");if(wc.F(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new q(32,"An invalid or illegal class name was specified");}return jc(Yb(b),"*",a,b)}};var xc={v:function(a,b){if(!ea(b.querySelector)&&C&&Qb(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new q(32,"No selector specified");a=va(a);try{var c=b.querySelector(a)}catch(d){throw new q(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},w:function(a,b){if(!ea(b.querySelectorAll)&&C&&Qb(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new q(32,"No selector specified");a=va(a);try{return b.querySelectorAll(a)}catch(c){throw new q(32,
"An invalid or illegal selector was specified");}}};function G(){this.b=this.a=null;this.s=0}function yc(a){this.node=a;this.a=this.b=null}function zc(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;){e=c.node;var g=b.node;e==g||e instanceof Lb&&g instanceof Lb&&e.a==g.a?(e=c,c=c.a,b=b.a):0<cc(c.node,b.node)?(e=b,b=b.a):(e=c,c=c.a);(e.b=d)?d.a=e:a.a=e;d=e;f++}for(e=c||b;e;)e.b=d,d=d.a=e,f++,e=e.a;a.b=d;a.s=f;return a}function Ac(a,b){b=new yc(b);b.a=a.a;a.b?a.a.b=b:a.a=a.b=b;a.a=b;a.s++}
function H(a,b){b=new yc(b);b.b=a.b;a.a?a.b.a=b:a.a=a.b=b;a.b=b;a.s++}function Bc(a){return(a=a.a)?a.node:null}G.prototype.f=function(){var a=Bc(this);return a?F(a):""};function Cc(a,b){return new Dc(a,!!b)}function Dc(a,b){this.f=a;this.b=(this.C=b)?a.b:a.a;this.a=null}function J(a){var b=a.b;if(b){var c=a.a=b;a.b=a.C?b.b:b.a;return c.node}return null};C&&Qb(10);Eb&&Sb(4);function K(a){this.m=a;this.b=this.i=!1;this.f=null}function A(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Ec(a,b){a.i=b}function Fc(a,b){a.b=b}function M(a,b){a=a.a(b);return a instanceof G?+a.f():+a}function N(a,b){a=a.a(b);return a instanceof G?a.f():""+a}function Gc(a,b){a=a.a(b);return a instanceof G?!!a.s:!!a};var Hc="function"===typeof ShadowRoot;
function Ic(a,b){if(a.style&&("hidden"==a.style.visibility||"none"==a.style.display))return"";if(3==a.nodeType){var c=a.data;b||(c=c.replace(/\n|\r|\t/g," "));return c.replace(/&nbsp/," ")}if(Hc&&1==a.nodeType&&null!==a.shadowRoot)return Ic(a.shadowRoot,b);if((1==a.nodeType||11==a.nodeType)&&"SCRIPT"!=a.nodeName&&"STYLE"!=a.nodeName){var d=b||"PRE"==a.tagName;c="";for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes.item(e);if(f)if(!Hc||"CONTENT"!=f.nodeName&&"SLOT"!=f.nodeName)c+=Ic(f,d);else for(var f=
"CONTENT"==f.nodeName?f.getDistributedNodes():f.assignedNodes(),g=0;g<f.length;g++){var k=f[g];k&&(c+=Ic(k,b))}}if("P"==a.tagName||"BR"==a.tagName||"HR"==a.tagName||"DIV"==a.tagName)c+="\n";c=c.replace(/&nbsp/," ");Nb.ha&&Sb(9)&&(c=c.replace(/&#100;/," "));return c}return""};function Jc(a,b,c){K.call(this,a.m);this.c=a;this.j=b;this.A=c;this.i=b.i||c.i;this.b=b.b||c.b;this.c==Kc&&(c.b||c.i||4==c.m||0==c.m||!b.f?b.b||b.i||4==b.m||0==b.m||!c.f||(this.f={name:c.f.name,D:b}):this.f={name:b.f.name,D:c})}p(Jc,K);
function Lc(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof G&&c instanceof G){b=Cc(b);for(d=J(b);d;d=J(b))for(e=Cc(c),f=J(e);f;f=J(e))if(a(F(d),F(f)))return!0;return!1}if(b instanceof G||c instanceof G){b instanceof G?(e=b,d=c):(e=c,d=b);f=Cc(e);for(var g=typeof d,k=J(f);k;k=J(f)){switch(g){case "number":k=+F(k);break;case "boolean":k=!!F(k);break;case "string":k=F(k);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(k,d)||e==c&&a(d,k))return!0}return!1}return e?
"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Jc.prototype.a=function(a){return this.c.u(this.j,this.A,a)};Jc.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+A(this.j);return a+=A(this.A)};function Mc(a,b,c,d){this.ea=a;this.U=b;this.m=c;this.u=d}Mc.prototype.toString=function(){return this.ea};var Nc={};
function O(a,b,c,d){if(Nc.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new Mc(a,b,c,d);return Nc[a.toString()]=a}O("div",6,1,function(a,b,c){return M(a,c)/M(b,c)});O("mod",6,1,function(a,b,c){return M(a,c)%M(b,c)});O("*",6,1,function(a,b,c){return M(a,c)*M(b,c)});O("+",5,1,function(a,b,c){return M(a,c)+M(b,c)});O("-",5,1,function(a,b,c){return M(a,c)-M(b,c)});O("<",4,2,function(a,b,c){return Lc(function(a,b){return a<b},a,b,c)});
O(">",4,2,function(a,b,c){return Lc(function(a,b){return a>b},a,b,c)});O("<=",4,2,function(a,b,c){return Lc(function(a,b){return a<=b},a,b,c)});O(">=",4,2,function(a,b,c){return Lc(function(a,b){return a>=b},a,b,c)});var Kc=O("=",3,2,function(a,b,c){return Lc(function(a,b){return a==b},a,b,c,!0)});O("!=",3,2,function(a,b,c){return Lc(function(a,b){return a!=b},a,b,c,!0)});O("and",2,2,function(a,b,c){return Gc(a,c)&&Gc(b,c)});O("or",1,2,function(a,b,c){return Gc(a,c)||Gc(b,c)});function Oc(a,b){if(b.a.length&&4!=a.m)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");K.call(this,a.m);this.c=a;this.j=b;this.i=a.i;this.b=a.b}p(Oc,K);Oc.prototype.a=function(a){a=this.c.a(a);return Pc(this.j,a)};Oc.prototype.toString=function(){var a="Filter:"+A(this.c);return a+=A(this.j)};function Qc(a,b){if(b.length<a.S)throw Error("Function "+a.l+" expects at least"+a.S+" arguments, "+b.length+" given");if(null!==a.K&&b.length>a.K)throw Error("Function "+a.l+" expects at most "+a.K+" arguments, "+b.length+" given");a.da&&B(b,function(b,d){if(4!=b.m)throw Error("Argument "+d+" to function "+a.l+" is not of type Nodeset: "+b);});K.call(this,a.m);this.H=a;this.c=b;Ec(this,a.i||Wa(b,function(a){return a.i}));Fc(this,a.ca&&!b.length||a.ba&&!!b.length||Wa(b,function(a){return a.b}))}
p(Qc,K);Qc.prototype.a=function(a){return this.H.u.apply(null,Za(a,this.c))};Qc.prototype.toString=function(){var a="Function: "+this.H;if(this.c.length)var b=Va(this.c,function(a,b){return a+A(b)},"Arguments:"),a=a+A(b);return a};function Rc(a,b,c,d,e,f,g,k,w){this.l=a;this.m=b;this.i=c;this.ca=d;this.ba=e;this.u=f;this.S=g;this.K=l(k)?k:g;this.da=!!w}Rc.prototype.toString=function(){return this.l};var Sc={};
function P(a,b,c,d,e,f,g,k){if(Sc.hasOwnProperty(a))throw Error("Function already created: "+a+".");Sc[a]=new Rc(a,b,c,d,!1,e,f,g,k)}P("boolean",2,!1,!1,function(a,b){return Gc(b,a)},1);P("ceiling",1,!1,!1,function(a,b){return Math.ceil(M(b,a))},1);P("concat",3,!1,!1,function(a,b){return Va($a(arguments,1),function(b,d){return b+N(d,a)},"")},2,null);P("contains",2,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);return-1!=b.indexOf(a)},2);P("count",1,!1,!1,function(a,b){return b.a(a).s},1,1,!0);
P("false",2,!1,!1,function(){return!1},0);P("floor",1,!1,!1,function(a,b){return Math.floor(M(b,a))},1);P("id",4,!1,!1,function(a,b){function c(a){if(Hb){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return Ya(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument;a=N(b,a).split(/\s+/);var f=[];B(a,function(a){a=c(a);!a||0<=Ta(f,a)||f.push(a)});f.sort(cc);var g=new G;B(f,function(a){H(g,a)});return g},1);
P("lang",2,!1,!1,function(){return!1},1);P("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);P("local-name",3,!1,!0,function(a,b){return(a=b?Bc(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);P("name",3,!1,!0,function(a,b){return(a=b?Bc(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);P("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
P("normalize-space",3,!1,!0,function(a,b){return(b?N(b,a):F(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);P("not",2,!1,!1,function(a,b){return!Gc(b,a)},1);P("number",1,!1,!0,function(a,b){return b?M(b,a):+F(a.a)},0,1);P("position",1,!0,!1,function(a){return a.b},0);P("round",1,!1,!1,function(a,b){return Math.round(M(b,a))},1);P("starts-with",2,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);return!b.lastIndexOf(a,0)},2);P("string",3,!1,!0,function(a,b){return b?N(b,a):F(a.a)},0,1);
P("string-length",1,!1,!0,function(a,b){return(b?N(b,a):F(a.a)).length},0,1);P("substring",3,!1,!1,function(a,b,c,d){c=M(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?M(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=N(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);P("substring-after",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
P("substring-before",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);P("sum",1,!1,!1,function(a,b){a=Cc(b.a(a));b=0;for(var c=J(a);c;c=J(a))b+=+F(c);return b},1,1,!0);P("translate",3,!1,!1,function(a,b,c,d){b=N(b,a);c=N(c,a);var e=N(d,a);d={};for(var f=0;f<c.length;f++)a=c.charAt(f),a in d||(d[a]=e.charAt(f));c="";for(f=0;f<b.length;f++)a=b.charAt(f),c+=a in d?d[a]:a;return c},3);P("true",2,!1,!1,function(){return!0},0);function Tc(a){K.call(this,3);this.c=a.substring(1,a.length-1)}p(Tc,K);Tc.prototype.a=function(){return this.c};Tc.prototype.toString=function(){return"Literal: "+this.c};function Uc(a){K.call(this,1);this.c=a}p(Uc,K);Uc.prototype.a=function(){return this.c};Uc.prototype.toString=function(){return"Number: "+this.c};function Vc(a,b){K.call(this,a.m);this.j=a;this.c=b;this.i=a.i;this.b=a.b;1==this.c.length&&(a=this.c[0],a.J||a.c!=Wc||(a=a.A,"*"!=a.f()&&(this.f={name:a.f(),D:null})))}p(Vc,K);function Xc(){K.call(this,4)}p(Xc,K);Xc.prototype.a=function(a){var b=new G;a=a.a;9==a.nodeType?H(b,a):H(b,a.ownerDocument);return b};Xc.prototype.toString=function(){return"Root Helper Expression"};function Yc(){K.call(this,4)}p(Yc,K);Yc.prototype.a=function(a){var b=new G;H(b,a.a);return b};Yc.prototype.toString=function(){return"Context Helper Expression"};
function Zc(a){return"/"==a||"//"==a}Vc.prototype.a=function(a){var b=this.j.a(a);if(!(b instanceof G))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.s;c++){var e=a[c],f=Cc(b,e.c.C);if(e.i||e.c!=$c)if(e.i||e.c!=ad){var g=J(f);for(b=e.a(new za(g));g=J(f);)g=e.a(new za(g)),b=zc(b,g)}else g=J(f),b=e.a(new za(g));else{for(g=J(f);(b=J(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new za(g))}}return b};
Vc.prototype.toString=function(){var a="Path Expression:"+A(this.j);if(this.c.length){var b=Va(this.c,function(a,b){return a+A(b)},"Steps:");a+=A(b)}return a};function bd(a,b){this.a=a;this.C=!!b}
function Pc(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=Cc(b),f=b.s,g,k=0;g=J(e);k++){var w=a.C?f-k:k+1;g=d.a(new za(g,w,f));if("number"==typeof g)w=w==g;else if("string"==typeof g||"boolean"==typeof g)w=!!g;else if(g instanceof G)w=0<g.s;else throw Error("Predicate.evaluate returned an unexpected type.");if(!w){w=e;g=w.f;var x=w.a;if(!x)throw Error("Next must be called at least once before remove.");var n=x.b,x=x.a;n?n.a=x:g.a=x;x?x.b=n:g.b=n;g.s--;w.a=null}}return b}
bd.prototype.toString=function(){return Va(this.a,function(a,b){return a+A(b)},"Predicates:")};function cd(a){K.call(this,1);this.c=a;this.i=a.i;this.b=a.b}p(cd,K);cd.prototype.a=function(a){return-M(this.c,a)};cd.prototype.toString=function(){return"Unary Expression: -"+A(this.c)};function dd(a){K.call(this,4);this.c=a;Ec(this,Wa(this.c,function(a){return a.i}));Fc(this,Wa(this.c,function(a){return a.b}))}p(dd,K);dd.prototype.a=function(a){var b=new G;B(this.c,function(c){c=c.a(a);if(!(c instanceof G))throw Error("Path expression must evaluate to NodeSet.");b=zc(b,c)});return b};dd.prototype.toString=function(){return Va(this.c,function(a,b){return a+A(b)},"Union Expression:")};function ed(a,b,c,d){K.call(this,4);this.c=a;this.A=b;this.j=c||new bd([]);this.J=!!d;b=this.j;b=0<b.a.length?b.a[0].f:null;a.ga&&b&&(a=b.name,a=Hb?a.toLowerCase():a,this.f={name:a,D:b.D});a:{a=this.j;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.i||1==c.m||0==c.m){a=!0;break a}a=!1}this.i=a}p(ed,K);
ed.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.D?N(c.D,a):null,f=1);if(this.J)if(this.i||this.c!=fd)if(b=Cc((new ed(gd,new z("node"))).a(a)),c=J(b))for(a=this.u(c,d,e,f);c=J(b);)a=zc(a,this.u(c,d,e,f));else a=new G;else a=lc(this.A,b,d,e),a=Pc(this.j,a,f);else a=this.u(a.a,d,e,f);return a};ed.prototype.u=function(a,b,c,d){a=this.c.H(this.A,a,b,c);return a=Pc(this.j,a,d)};
ed.prototype.toString=function(){var a="Step:"+A("Operator: "+(this.J?"//":"/"));this.c.l&&(a+=A("Axis: "+this.c));a+=A(this.A);if(this.j.a.length){var b=Va(this.j.a,function(a,b){return a+A(b)},"Predicates:");a+=A(b)}return a};function hd(a,b,c,d){this.l=a;this.H=b;this.C=c;this.ga=d}hd.prototype.toString=function(){return this.l};var id={};function Q(a,b,c,d){if(id.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new hd(a,b,c,!!d);return id[a]=b}
Q("ancestor",function(a,b){for(var c=new G;b=b.parentNode;)a.a(b)&&Ac(c,b);return c},!0);Q("ancestor-or-self",function(a,b){var c=new G;do a.a(b)&&Ac(c,b);while(b=b.parentNode);return c},!0);
var Wc=Q("attribute",function(a,b){var c=new G,d=a.f();if("style"==d&&Hb&&b.style)return H(c,new Lb(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof z&&null===a.b||"*"==d)for(d=0;a=e[d];d++)Hb?a.nodeValue&&H(c,Mb(b,a)):H(c,a);else(a=e.getNamedItem(d))&&(Hb?a.nodeValue&&H(c,Mb(b,a)):H(c,a));return c},!1),fd=Q("child",function(a,b,c,d,e){return(Hb?qc:rc).call(null,a,b,m(c)?c:null,m(d)?d:null,e||new G)},!1,!0);Q("descendant",lc,!1,!0);
var gd=Q("descendant-or-self",function(a,b,c,d){var e=new G;kc(b,c,d)&&a.a(b)&&H(e,b);return lc(a,b,c,d,e)},!1,!0),$c=Q("following",function(a,b,c,d){var e=new G;do for(var f=b;f=f.nextSibling;)kc(f,c,d)&&a.a(f)&&H(e,f),e=lc(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);Q("following-sibling",function(a,b){for(var c=new G;b=b.nextSibling;)a.a(b)&&H(c,b);return c},!1);Q("namespace",function(){return new G},!1);
var jd=Q("parent",function(a,b){var c=new G;if(9==b.nodeType)return c;if(2==b.nodeType)return H(c,b.ownerElement),c;b=b.parentNode;a.a(b)&&H(c,b);return c},!1),ad=Q("preceding",function(a,b,c,d){var e=new G,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,k=f.length;g<k;g++){var w=[];for(b=f[g];b=b.previousSibling;)w.unshift(b);for(var x=0,n=w.length;x<n;x++)b=w[x],kc(b,c,d)&&a.a(b)&&H(e,b),e=lc(a,b,c,d,e)}return e},!0,!0);
Q("preceding-sibling",function(a,b){for(var c=new G;b=b.previousSibling;)a.a(b)&&Ac(c,b);return c},!0);var kd=Q("self",function(a,b){var c=new G;a.a(b)&&H(c,b);return c},!1);function ld(a,b){this.a=a;this.b=b}function md(a){for(var b,c=[];;){R(a,"Missing right hand side of binary expression.");b=nd(a);var d=u(a.a);if(!d)break;var e=(d=Nc[d]||null)&&d.U;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].U;)b=new Jc(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Jc(c.pop(),c.pop(),b);return b}function R(a,b){if(Ea(a.a))throw Error(b);}function od(a,b){a=u(a.a);if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function pd(a){a=u(a.a);if(")"!=a)throw Error("Bad token: "+a);}function qd(a){a=u(a.a);if(2>a.length)throw Error("Unclosed literal string");return new Tc(a)}
function rd(a){var b=[];if(Zc(t(a.a))){var c=u(a.a);var d=t(a.a);if("/"==c&&(Ea(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new Xc;d=new Xc;R(a,"Missing next location step.");c=sd(a,c);b.push(c)}else{a:{c=t(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":u(a.a);c=md(a);R(a,'unclosed "("');od(a,")");break;case '"':case "'":c=qd(a);break;default:if(isNaN(+c))if(!Ia(c)&&/(?![0-9])[\w]/.test(d)&&"("==t(a.a,1)){c=u(a.a);
c=Sc[c]||null;u(a.a);for(d=[];")"!=t(a.a);){R(a,"Missing function argument list.");d.push(md(a));if(","!=t(a.a))break;u(a.a)}R(a,"Unclosed function argument list.");pd(a);c=new Qc(c,d)}else{c=null;break a}else c=new Uc(+u(a.a))}"["==t(a.a)&&(d=new bd(td(a)),c=new Oc(c,d))}if(c)if(Zc(t(a.a)))d=c;else return c;else c=sd(a,"/"),d=new Yc,b.push(c)}for(;Zc(t(a.a));)c=u(a.a),R(a,"Missing next location step."),c=sd(a,c),b.push(c);return new Vc(d,b)}
function sd(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==t(a.a)){var c=new ed(kd,new z("node"));u(a.a);return c}if(".."==t(a.a))return c=new ed(jd,new z("node")),u(a.a),c;if("@"==t(a.a)){var d=Wc;u(a.a);R(a,"Missing attribute name")}else if("::"==t(a.a,1)){if(!/(?![0-9])[\w]/.test(t(a.a).charAt(0)))throw Error("Bad token: "+u(a.a));var e=u(a.a);d=id[e]||null;if(!d)throw Error("No axis with name: "+e);u(a.a);R(a,"Missing node name")}else d=fd;e=t(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==
t(a.a,1)){if(!Ia(e))throw Error("Invalid node type: "+e);e=u(a.a);if(!Ia(e))throw Error("Invalid type name: "+e);od(a,"(");R(a,"Bad nodetype");var f=t(a.a).charAt(0),g=null;if('"'==f||"'"==f)g=qd(a);R(a,"Bad nodetype");pd(a);e=new z(e,g)}else if(e=u(a.a),f=e.indexOf(":"),-1==f)e=new Ja(e);else{var g=e.substring(0,f);if("*"==g)var k="*";else if(k=a.b(g),!k)throw Error("Namespace prefix not declared: "+g);e=e.substr(f+1);e=new Ja(e,k)}else throw Error("Bad token: "+u(a.a));a=new bd(td(a),d.C);return c||
new ed(d,e,a,"//"==b)}function td(a){for(var b=[];"["==t(a.a);){u(a.a);R(a,"Missing predicate expression.");var c=md(a);b.push(c);R(a,"Unclosed predicate expression.");od(a,"]")}return b}function nd(a){if("-"==t(a.a))return u(a.a),new cd(nd(a));var b=rd(a);if("|"!=t(a.a))a=b;else{for(b=[b];"|"==u(a.a);)R(a,"Missing next union location path."),b.push(rd(a));a.a.a--;a=new dd(b)}return a};function ud(a,b){if(!a.length)throw Error("Empty XPath expression.");a=Ba(a);if(Ea(a))throw Error("Invalid XPath expression.");b?ea(b)||(b=ia(b.lookupNamespaceURI,b)):b=function(){return null};var c=md(new ld(a,b));if(!Ea(a))throw Error("Bad token: "+u(a));this.evaluate=function(a,b){a=c.a(new za(a));return new S(a,b)}}
function S(a,b){if(!b)if(a instanceof G)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof G))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof G?a.f():""+a;break;case 1:this.numberValue=a instanceof G?+a.f():+a;break;case 3:this.booleanValue=a instanceof G?0<a.s:!!a;break;case 4:case 5:case 6:case 7:var c=
Cc(a);var d=[];for(var e=J(c);e;e=J(c))d.push(e instanceof Lb?e.a:e);this.snapshotLength=a.s;this.invalidIteratorState=!1;break;case 8:case 9:a=Bc(a);this.singleNodeValue=a instanceof Lb?a.a:a;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=d.length||
0>a?null:d[a]}}S.ANY_TYPE=0;S.NUMBER_TYPE=1;S.STRING_TYPE=2;S.BOOLEAN_TYPE=3;S.UNORDERED_NODE_ITERATOR_TYPE=4;S.ORDERED_NODE_ITERATOR_TYPE=5;S.UNORDERED_NODE_SNAPSHOT_TYPE=6;S.ORDERED_NODE_SNAPSHOT_TYPE=7;S.ANY_UNORDERED_NODE_TYPE=8;S.FIRST_ORDERED_NODE_TYPE=9;function vd(a){this.lookupNamespaceURI=Ka(a)}
function wd(a,b){a=a||aa;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=S,c.evaluate=function(a,b,c,g){return(new ud(a,c)).evaluate(b,g)},c.createExpression=function(a,b){return new ud(a,b)},c.createNSResolver=function(a){return new vd(a)}}ca("wgxpath.install",wd);var T={};T.L=function(){var a={la:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
T.u=function(a,b,c){var d=E(a);if(!d.documentElement)return null;(C||Eb)&&wd(d?d.parentWindow||d.defaultView:window);try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):T.L;if(C&&!ub(7))return d.evaluate.call(d,b,a,e,c,null);if(!C||9<=Number(vb)){for(var f={},g=d.getElementsByTagName("*"),k=0;k<g.length;++k){var w=g[k],x=w.namespaceURI;if(x&&!f[x]){var n=w.lookupPrefix(x);if(!n)var L=x.match(".*/(\\w+)/?$"),n=L?L[1]:"xhtml";f[x]=n}}var U={},ja;for(ja in f)U[f[ja]]=ja;e=function(a){return U[a]||
null}}try{return d.evaluate(b,a,e,c,null)}catch(La){if("TypeError"===La.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):T.L,d.evaluate(b,a,e,c,null);throw La;}}catch(La){if(!lb||"NS_ERROR_ILLEGAL_VALUE"!=La.name)throw new q(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+La);}};T.M=function(a,b){if(!a||1!=a.nodeType)throw new q(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
T.v=function(a,b){var c=function(){var c=T.u(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=E(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||T.M(c,a);return c};
T.w=function(a,b){var c=function(){var c=T.u(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=E(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();B(c,function(b){T.M(b,a)});return c};var xd="function"===typeof ShadowRoot;function yd(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return I(a)?a:null}
function V(a,b){b=ya(b);if("float"==b||"cssFloat"==b||"styleFloat"==b)b=Xb?"styleFloat":"cssFloat";a:{var c=b;var d=E(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||zd(a,b);if(null===a)a=null;else if(0<=Ta(bb,b)){b:{var e=a.match(eb);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),e=Number(e[4]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d&&0<=e&&1>=e)){b=[b,c,d,e];break b}b=null}if(!b)b:{if(d=a.match(fb))if(b=
Number(d[1]),c=Number(d[2]),d=Number(d[3]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=oa[b.toLowerCase()];if(!c&&(c="#"==b.charAt(0)?b:"#"+b,4==c.length&&(c=c.replace(cb,"#$1$1$2$2$3$3")),!db.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}
function zd(a,b){var c=a.currentStyle||a.style,d=c[b];!l(d)&&ea(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?l(d)?d:null:(a=yd(a))?zd(a,b):null}
function Ad(a,b,c){function d(a){var b=Bd(a);return 0<b.height&&0<b.width?!0:I(a,"PATH")&&(0<b.height||0<b.width)?(a=V(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=V(a,"overflow")&&Wa(a.childNodes,function(a){return 3==a.nodeType||I(a)&&d(a)})}function e(a){return Cd(a)==W&&Xa(a.childNodes,function(a){return!I(a)||e(a)||!d(a)})}if(!I(a))throw Error("Argument to isShown must be of type Element");if(I(a,"BODY"))return!0;if(I(a,"OPTION")||I(a,"OPTGROUP"))return a=ic(a,function(a){return I(a,"SELECT")}),
!!a&&Ad(a,!0,c);var f=Dd(a);if(f)return!!f.P&&0<f.rect.width&&0<f.rect.height&&Ad(f.P,b,c);if(I(a,"INPUT")&&"hidden"==a.type.toLowerCase()||I(a,"NOSCRIPT"))return!1;f=V(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||Ed(a))&&d(a)?!e(a):!1}
function Fd(a){function b(a){if(I(a)&&"none"==V(a,"display"))return!1;var c;(c=a.parentNode)&&c.shadowRoot&&void 0!==a.assignedSlot?c=a.assignedSlot?a.assignedSlot.parentNode:null:a.getDestinationInsertionPoints&&(a=a.getDestinationInsertionPoints(),0<a.length&&(c=a[a.length-1]));if(xd&&c instanceof ShadowRoot){if(c.host.shadowRoot!==c)return!1;c=c.host}return!c||9!=c.nodeType&&11!=c.nodeType?c&&b(c):!0}return Ad(a,!1,b)}var W="hidden";
function Cd(a){function b(a){function b(a){return a==g?!0:!V(a,"display").lastIndexOf("inline",0)||"absolute"==c&&"static"==V(a,"position")?!1:!0}var c=V(a,"position");if("fixed"==c)return x=!0,a==g?null:g;for(a=yd(a);a&&!b(a);)a=yd(a);return a}function c(a){var b=a;if("visible"==w)if(a==g&&k)b=k;else if(a==k)return{x:"visible",y:"visible"};b={x:V(b,"overflow-x"),y:V(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new Zb(f)).a;
a=b.scrollingElement?b.scrollingElement:mb||"CSS1Compat"!=b.compatMode?b.body||b.documentElement:b.documentElement;b=b.parentWindow||b.defaultView;a=C&&ub("10")&&b.pageYOffset!=a.scrollTop?new ib(a.scrollLeft,a.scrollTop):new ib(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new ib(a.scrollLeft,a.scrollTop);return a}var e=Gd(a);var f=E(a),g=f.documentElement,k=f.body,w=V(g,"overflow"),x;for(a=b(a);a;a=b(a)){var n=c(a);if("visible"!=n.x||"visible"!=n.y){var L=Bd(a);if(!L.width||!L.height)return W;
var U=e.a<L.a,ja=e.b<L.b;if(U&&"hidden"==n.x||ja&&"hidden"==n.y)return W;if(U&&"visible"!=n.x||ja&&"visible"!=n.y){U=d(a);ja=e.b<L.b-U.y;if(e.a<L.a-U.x&&"visible"!=n.x||ja&&"visible"!=n.x)return W;e=Cd(a);return e==W?W:"scroll"}U=e.f>=L.a+L.width;L=e.c>=L.b+L.height;if(U&&"hidden"==n.x||L&&"hidden"==n.y)return W;if(U&&"visible"!=n.x||L&&"visible"!=n.y){if(x&&(n=d(a),e.f>=g.scrollWidth-n.x||e.a>=g.scrollHeight-n.y))return W;e=Cd(a);return e==W?W:"scroll"}}}return"none"}
function Bd(a){var b=Dd(a);if(b)return b.rect;if(I(a,"HTML"))return a=E(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new ra(a.clientWidth,a.clientHeight),new D(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new D(0,0,0,0)}b=new D(c.left,c.top,c.right-c.left,c.bottom-c.top);C&&a.ownerDocument.body&&(a=E(a),b.a-=a.documentElement.clientLeft+a.body.clientLeft,b.b-=a.documentElement.clientTop+a.body.clientTop);
return b}function Dd(a){var b=I(a,"MAP");if(!b&&!I(a,"AREA"))return null;var c=b?a:I(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=T.v('/descendant::*[@usemap = "#'+c.name+'"]',E(c)))&&(e=Bd(d),b||"default"==a.shape.toLowerCase()||(a=Hd(a),b=Math.min(Math.max(a.a,0),e.width),c=Math.min(Math.max(a.b,0),e.height),e=new D(b+e.a,c+e.b,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{P:d,rect:e||new D(0,0,0,0)}}
function Hd(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new D(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new D(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new D(b,c,d-b,e-c)}return new D(0,0,0,0)}function Gd(a){a=Bd(a);return new xb(a.b,a.a+a.width,a.b+a.height,a.a)}
function Id(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function Jd(a){var b=[];xd?Kd(a,b):Ld(a,b);var c=b;a=c.length;for(var b=Array(a),c=m(c)?c.split(""):c,d=0;d<a;d++)d in c&&(b[d]=Id.call(void 0,c[d]));return Id(b.join("\n")).replace(/\xa0/g," ")}
function Md(a,b,c){if(I(a,"BR"))b.push("");else{var d=I(a,"TD"),e=V(a,"display"),f=!d&&!(0<=Ta(Nd,e)),g=l(a.previousElementSibling)?a.previousElementSibling:ac(a.previousSibling),g=g?V(g,"display"):"",k=V(a,"float")||V(a,"cssFloat")||V(a,"styleFloat");!f||"run-in"==g&&"none"==k||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var w=Fd(a),x=null,n=null;w&&(x=V(a,"white-space"),n=V(a,"text-transform"));B(a.childNodes,function(a){c(a,b,w,x,n)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||ua(a," ")||
(b[b.length-1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function Ld(a,b){Md(a,b,function(a,b,e,f,g){3==a.nodeType&&e?Od(a,b,f,g):I(a)&&Ld(a,b)})}var Nd="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function Od(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";ua(c," ")&&!a.lastIndexOf(" ",0)&&(a=a.substr(1));b.push(c+a)}
function Ed(a){if(Xb){if("relative"==V(a,"position"))return 1;a=V(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return Pd(a)}function Pd(a){var b=1,c=V(a,"opacity");c&&(b=Number(c));(a=yd(a))&&(b*=Pd(a));return b}
function Qd(a,b,c,d,e){var f;if(3==a.nodeType&&c)Od(a,b,d,e);else if(I(a))if(I(a,"CONTENT")||I(a,"SLOT")){for(f=a;f.parentNode;)f=f.parentNode;f instanceof ShadowRoot?(a=I(a,"CONTENT")?a.getDistributedNodes():a.assignedNodes(),B(a,function(a){Qd(a,b,c,d,e)})):Kd(a,b)}else if(I(a,"SHADOW")){for(f=a;f.parentNode;)f=f.parentNode;if(f instanceof ShadowRoot&&(a=f))for(a=a.olderShadowRoot;a;)B(a.childNodes,function(a){Qd(a,b,c,d,e)}),a=a.olderShadowRoot}else Kd(a,b)}
function Kd(a,b){a.shadowRoot&&B(a.shadowRoot.childNodes,function(a){Qd(a,b,!0,null,null)});Md(a,b,function(a,b,e,f,g){var c=null;1==a.nodeType?c=a:3==a.nodeType&&(c=a);c&&(c.assignedSlot||c.getDestinationInsertionPoints&&0<c.getDestinationInsertionPoints().length)||Qd(a,b,e,f,g)})};var Rd={F:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},v:function(a,b){var c=Yb(b),d=m(a)?c.a.getElementById(a):a;return d?sc(d,"id")==a&&b!=d&&bc(b,d)?d:Ya(jc(c,"*"),function(c){return sc(c,"id")==a&&b!=c&&bc(b,c)}):null},w:function(a,b){if(!a)return[];if(Rd.F(b,a))try{return b.querySelectorAll("#"+Rd.Z(a))}catch(c){return[]}b=jc(Yb(b),"*",null,b);return Ua(b,function(b){return sc(b,"id")==a})},Z:function(a){return a.replace(/([\s'"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var X={},Sd={};X.V=function(a,b,c){try{var d=xc.w("a",b)}catch(e){d=jc(Yb(b),"A",null,b)}return Ya(d,function(b){b=Jd(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};X.R=function(a,b,c){try{var d=xc.w("a",b)}catch(e){d=jc(Yb(b),"A",null,b)}return Ua(d,function(b){b=Jd(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};X.v=function(a,b){return X.V(a,b,!1)};X.w=function(a,b){return X.R(a,b,!1)};Sd.v=function(a,b){return X.V(a,b,!0)};
Sd.w=function(a,b){return X.R(a,b,!0)};var Td={index:function(a,b){var c=Number(a);if(isNaN(c)||0>c)throw new v("Illegal Index: "+a);if(b.length<=c)throw new v("Index out of range: "+a);return[b[c]]},name:function(a,b){return Ua(b,function(b){return vc(b,"name")==a})},value:function(a,b){return Ua(b,function(b){return vc(b,"value")===a})}};var Ud={className:wc,"class name":wc,css:xc,"css selector":xc,id:Rd,linkText:X,"link text":X,name:{v:function(a,b){b=jc(Yb(b),"*",null,b);return Ya(b,function(b){return sc(b,"name")==a})},w:function(a,b){b=jc(Yb(b),"*",null,b);return Ua(b,function(b){return sc(b,"name")==a})}},partialLinkText:Sd,"partial link text":Sd,tagName:gb,"tag name":gb,xpath:T};
function Vd(a,b){a:{for(c in a)if(a.hasOwnProperty(c))break a;var c=null}if(c){var d=Ud[c];if(d&&ea(d.v))return d.v(a[c],b||ma.document)}throw Error("Unsupported locator strategy: "+c);};mb||Rb&&Sb(3.6);var Y={aa:function(a,b){return a.lastIndexOf("//",0)?a.lastIndexOf("document.",0)?Y.O(a,b):Y.N(a,b):Y.W(a,b)},X:function(a,b){return Wd(b||E(ma),function(b){return b.alt==a})},Y:function(a,b){return Wd(b||E(ma),function(b){return b.className==a})},N:function(a){var b=null;try{b=eval(a)}catch(c){return null}return b?b:null},$:function(a,b){return Vd({id:a},b)},O:function(a,b){return Y.id(a,b)||Y.name(a,b)},l:function(a,b){b=b||E(ma);Yb(b);b=$b(document,"*",null,b);a=a.split(" ");for(a[0]="name="+a[0];a.length;){var c=
a.shift(),d=b;b="value";var e=c.match(/^([A-Za-z]+)=(.+)/);e&&(b=e[1].toLowerCase(),c=e[2]);e=Td[b];if(!e)throw new v("Unrecognised element-filter type: '"+b+"'");b=e(c,d)}return 0<b.length?b[0]:null},fa:function(a,b){try{a:{a=decodeURIComponent(a);b=b||document;var c=b||document,d=c.$wdc_;d||(d=c.$wdc_={},d.T=la());d.T||(d.T=la());var e=d;if(!(null!==e&&a in e))throw new q(10,"Element does not exist in cache");var f=e[a];if(null!==f&&"setInterval"in f){if(f.closed)throw delete e[a],new q(23,"Window has been closed.");
var g=f}else{for(d=f;d;){if(d==b.documentElement){g=f;break a}d=d.parentNode}delete e[a];throw new q(10,"Element is no longer attached to the DOM");}}return g}catch(k){return null}},W:function(a,b){var c=ua(a,"/"),d={xpath:a};try{var e=Vd(d,b);if(e||!c)return e}catch(f){if(!c)throw f;}d={xpath:a.substring(0,a.length-1)};return Vd(d,b)}};Y.alt=Y.X;Y["class"]=Y.Y;Y.dom=Y.N;Y.id=Y.$;Y.identifier=Y.O;Y.implicit=Y.aa;
Y.link=function(a,b){b=(b||E(ma)).getElementsByTagName("a");for(var c=0;c<b.length;c++){var d=b[c],e=d,f="";lb&&"1.8"<=qb||mb||C?f=Ic(e,!1):e.textContent?f=e.textContent:e.innerText&&(f=e.innerText);e=f=f.replace(/\r\n|\r/g,"\n");e=e.replace(/\ +/g," ");f=new RegExp(String.fromCharCode(160),"g");if(mb)for(f=String.fromCharCode(160);-1!=e.indexOf(f);)e=e.replace(f," ");else e=e.replace(f," ");f=e;e=va(f);if(Sa(a)(e))return d}return null};Y.name=Y.l;Y.stored=Y.fa;Y.xpath=Y.W;var Xd={};function Z(a,b,c){fa(a)&&(a=lb?a.g:a.h);a=new Yd(a);!b||b in Xd&&!c||(Xd[b]={key:a,shift:!1},c&&(Xd[c]={key:a,shift:!0}));return a}function Yd(a){this.code=a}Z(8);Z(9);Z(13);var Zd=Z(16),$d=Z(17),ae=Z(18);Z(19);Z(20);Z(27);Z(32," ");Z(33);Z(34);Z(35);Z(36);Z(37);Z(38);Z(39);Z(40);Z(44);Z(45);Z(46);Z(48,"0",")");Z(49,"1","!");Z(50,"2","@");Z(51,"3","#");Z(52,"4","$");Z(53,"5","%");Z(54,"6","^");Z(55,"7","&");Z(56,"8","*");Z(57,"9","(");Z(65,"a","A");Z(66,"b","B");Z(67,"c","C");Z(68,"d","D");
Z(69,"e","E");Z(70,"f","F");Z(71,"g","G");Z(72,"h","H");Z(73,"i","I");Z(74,"j","J");Z(75,"k","K");Z(76,"l","L");Z(77,"m","M");Z(78,"n","N");Z(79,"o","O");Z(80,"p","P");Z(81,"q","Q");Z(82,"r","R");Z(83,"s","S");Z(84,"t","T");Z(85,"u","U");Z(86,"v","V");Z(87,"w","W");Z(88,"x","X");Z(89,"y","Y");Z(90,"z","Z");var be=Z(ob?{g:91,h:91}:nb?{g:224,h:91}:{g:0,h:91});Z(ob?{g:92,h:92}:nb?{g:224,h:93}:{g:0,h:92});Z(ob?{g:93,h:93}:nb?{g:0,h:0}:{g:93,h:null});Z({g:96,h:96},"0");Z({g:97,h:97},"1");
Z({g:98,h:98},"2");Z({g:99,h:99},"3");Z({g:100,h:100},"4");Z({g:101,h:101},"5");Z({g:102,h:102},"6");Z({g:103,h:103},"7");Z({g:104,h:104},"8");Z({g:105,h:105},"9");Z({g:106,h:106},"*");Z({g:107,h:107},"+");Z({g:109,h:109},"-");Z({g:110,h:110},".");Z({g:111,h:111},"/");Z(144);Z(112);Z(113);Z(114);Z(115);Z(116);Z(117);Z(118);Z(119);Z(120);Z(121);Z(122);Z(123);Z({g:107,h:187},"=","+");Z(108,",");Z({g:109,h:189},"-","_");Z(188,",","<");Z(190,".",">");Z(191,"/","?");Z(192,"`","~");Z(219,"[","{");
Z(220,"\\","|");Z(221,"]","}");Z({g:59,h:186},";",":");Z(222,"'",'"');var ce=new yb;ce.set(1,Zd);ce.set(2,$d);ce.set(4,ae);ce.set(8,be);(function(a){var b=new yb;B(zb(a),function(c){b.set(a.get(c).code,c)});return b})(ce);lb&&Qb(12);function de(a,b,c,d){var e=Y[a];if(!e)throw new v("Unrecognised locator type: '"+a+"'");if(c=e.call(null,b,c))return c;if(!d)return null;for(e=0;e<d.frames.length;e++){try{var f=d.frames[e].document}catch(g){}if(f&&(c=de(a,b,f,d.frames[e])))return c}return null}function Wd(a,b){for(var c=a.childNodes.length,d=0;d<c;d++){var e=a.childNodes[d];if(1==e.nodeType&&(b(e)||(e=Wd(e,b))))return e}return null};function ee(a){var b=Sa(a);return{G:function(c){for(var d=0;d<c.options.length;d++)if(b(c.options[d].text))return c.options[d];throw new v("Option with label '"+a+"' not found");},I:function(c){c=c.options[c.selectedIndex].text;if(!b(c))throw new v("Expected text ("+a+") did not match: "+c);}}}
var fe={id:function(a){var b=Sa(a);return{G:function(c){for(var d=0;d<c.options.length;d++)if(b(c.options[d].id))return c.options[d];throw new v("Option with id '"+a+"' not found");},I:function(c){c=c.options[c.selectedIndex].id;if(!b(c))throw new v("Expected id ("+a+") did not match: "+c);}}},index:function(a){var b=Number(a);if(isNaN(b)||0>b)throw new v("Illegal Index: "+a);return{G:function(a){if(a.options.length<=b)throw new v("Index out of range.  Only "+a.options.length+" options available");
return a.options[b]},I:function(a){if(b!=a.selectedIndex)throw new v("Selected index ("+a.selectedIndex+") does not match expected index: "+b);}}},label:ee,text:ee,value:function(a){var b=Sa(a);return{G:function(c){for(var d=0;d<c.options.length;d++)if(b(c.options[d].value))return c.options[d];throw new v("Option with value '"+a+"' not found");},I:function(c){c=c.options[c.selectedIndex].value;if(!b(c))throw new v("Expected value ("+a+") did not match: "+c);}}}};ca("_",function(a,b){if(m(a)&&m(a)){var c;(c=a.match(/^([A-Za-z]+)=.+/))?(c=c[1].toLowerCase(),c={type:c,string:a.substring(c.length+1)}):(c={string:"",type:""},c.string=a,c.type=a.lastIndexOf("//",0)?a.lastIndexOf("document.",0)?"identifier":"dom":"xpath");var d=ma||ma;c=de(c.type,c.string,d.document,d);if(!c)throw new v("Element "+a+" not found");a=c}if(!l(a.options))throw new v("Specified element is not a Select (has no options)");c="label";d=b;if(b=b.match(/^([a-zA-Z]+)=(.*)/))c=b[1],d=b[2];if(b=
fe[c])b=b(d);else throw new v("Unknown option locator type: "+c);return b.G(a)});; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
