function(){return function(){var aa=this;function ba(a){return void 0!==a}function l(a){return"string"==typeof a}function ca(a){return"number"==typeof a}function da(a,b){a=a.split(".");var c=aa;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&ba(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}
function ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function fa(a){return"function"==ea(a)}function ga(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ha(a,b,c){return a.call.apply(a.bind,arguments)}
function ia(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ja(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja=ha:ja=ia;return ja.apply(null,arguments)}
function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var la=Date.now||function(){return+new Date};function m(a,b){function c(){}c.prototype=b.prototype;a.Ua=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Sa=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var na=window;function q(a,b){this.code=a;this.a=r[a]||oa;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}m(q,Error);var oa="unknown error",r={15:"element not selectable",11:"element not visible"};r[31]=oa;r[30]=oa;r[24]="invalid cookie domain";r[29]="invalid element coordinates";r[12]="invalid element state";
r[32]="invalid selector";r[51]="invalid selector";r[52]="invalid selector";r[17]="javascript error";r[405]="unsupported operation";r[34]="move target out of bounds";r[27]="no such alert";r[7]="no such element";r[8]="no such frame";r[23]="no such window";r[28]="script timeout";r[33]="session not created";r[10]="stale element reference";r[21]="timeout";r[25]="unable to set cookie";r[26]="unexpected alert open";r[13]=oa;r[9]="unknown command";q.prototype.toString=function(){return this.name+": "+this.message};var pa={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};function qa(a){if(Error.captureStackTrace)Error.captureStackTrace(this,qa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}m(qa,Error);qa.prototype.name="CustomError";var ra;function sa(a,b){this.width=a;this.height=b}sa.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};sa.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};sa.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};sa.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
sa.prototype.scale=function(a,b){b=ca(b)?b:a;this.width*=a;this.height*=b;return this};function ta(a,b){var c=ua;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};function va(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var wa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function xa(a,b){var c=0;a=wa(String(a)).split(".");b=wa(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;!c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=ya(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||ya(0==f[2].length,0==g[2].length)||ya(f[2],g[2]);f=f[3];g=g[3]}while(!c)}return c}function ya(a,b){return a<b?-1:a>b?1:0}
function za(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function Aa(a,b,c){this.a=a;this.b=b||1;this.f=c||1};function Ba(a){this.b=a;this.a=0}function Ca(a){a=a.match(Da);for(var b=0;b<a.length;b++)Ea.test(a[b])&&a.splice(b,1);return new Ba(a)}var Da=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,Ea=/^\s/;function t(a,b){return a.b[a.a+(b||0)]}function u(a){return a.b[a.a++]}function Fa(a){return a.b.length<=a.a};function Ga(a){qa.call(this,a)}m(Ga,qa);var Ha;a:{var Ia=aa.navigator;if(Ia){var Ja=Ia.userAgent;if(Ja){Ha=Ja;break a}}Ha=""}function v(a){return-1!=Ha.indexOf(a)};function w(a,b){this.c=a;this.f=ba(b)?b:null;this.g=null;switch(a){case "comment":this.g=8;break;case "text":this.g=3;break;case "processing-instruction":this.g=7;break;case "node":break;default:throw Error("Unexpected argument");}}function Ka(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}w.prototype.a=function(a){return null===this.g||this.g==a.nodeType};w.prototype.b=function(){return this.c};
w.prototype.toString=function(){var a="Kind Test: "+this.c;null===this.f||(a+=x(this.f));return a};function La(a,b){this.j=a.toLowerCase();a="*"==this.j?"*":"http://www.w3.org/1999/xhtml";this.f=b?b.toLowerCase():a}La.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=ba(a.localName)?a.localName:a.nodeName;return"*"!=this.j&&this.j!=b.toLowerCase()?!1:"*"==this.f?!0:this.f==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};La.prototype.b=function(){return this.j};
La.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.f?"":this.f+":")+this.j};function Ma(a){switch(a.nodeType){case 1:return ka(Na,a);case 9:return Ma(a.documentElement);case 11:case 10:case 6:case 12:return Pa;default:return a.parentNode?Ma(a.parentNode):Pa}}function Pa(){return null}function Na(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Na(a.parentNode,b):null};function Qa(a,b){return(new RegExp(a)).test(b)}function Ra(a,b){return(new RegExp(a,"i")).test(b)}function Sa(a){a=a.replace(/([.^$+(){}\[\]\\|])/g,"\\$1");a=a.replace(/\?/g,"(.|[\r\n])");return a=a.replace(/\*/g,"(.|[\r\n])*")}var Ta={exact:function(a,b){return-1!=b.indexOf(a)},glob:function(a,b){return(new RegExp("^"+Sa(a)+"$")).test(b)},globcontains:function(a,b){return(new RegExp(Sa(a))).test(b)},regex:Qa,regexi:Ra,regexpi:Ra,regexp:Qa};function Ua(a,b){if(l(a))return l(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function y(a,b){for(var c=a.length,d=l(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function Va(a,b){for(var c=a.length,d=[],e=0,f=l(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d}
function Wa(a,b){for(var c=a.length,d=Array(c),e=l(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d}function Xa(a,b,c){var d=c;y(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}function Ya(a,b){for(var c=a.length,d=l(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function Za(a,b){for(var c=a.length,d=l(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}
function $a(a,b){a:{for(var c=a.length,d=l(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:l(a)?a.charAt(b):a[b]}function ab(a){return Array.prototype.concat.apply([],arguments)}function bb(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function cb(){return v("iPhone")&&!v("iPod")&&!v("iPad")};var db="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),eb=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,fb=/^#(?:[0-9a-f]{3}){1,2}$/i,gb=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,hb=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;var ib={s:function(a,b){if(""===a)throw new q(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},u:function(a,b){if(""===a)throw new q(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};function jb(){return(v("Chrome")||v("CriOS"))&&!v("Edge")};function kb(a,b){this.x=ba(a)?a:0;this.y=ba(b)?b:0}kb.prototype.toString=function(){return"("+this.x+", "+this.y+")"};kb.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};kb.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};kb.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};kb.prototype.scale=function(a,b){b=ca(b)?b:a;this.x*=a;this.y*=b;return this};var lb=v("Opera"),z=v("Trident")||v("MSIE"),mb=v("Edge"),A=v("Gecko")&&!(-1!=Ha.toLowerCase().indexOf("webkit")&&!v("Edge"))&&!(v("Trident")||v("MSIE"))&&!v("Edge"),nb=-1!=Ha.toLowerCase().indexOf("webkit")&&!v("Edge");function ob(){var a=aa.document;return a?a.documentMode:void 0}var pb;
a:{var qb="",rb=function(){var a=Ha;if(A)return/rv\:([^\);]+)(\)|;)/.exec(a);if(mb)return/Edge\/([\d\.]+)/.exec(a);if(z)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(nb)return/WebKit\/(\S+)/.exec(a);if(lb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();rb&&(qb=rb?rb[1]:"");if(z){var sb=ob();if(null!=sb&&sb>parseFloat(qb)){pb=String(sb);break a}}pb=qb}var ua={};function tb(a){return ta(a,function(){return 0<=xa(pb,a)})}var ub;var vb=aa.document;
ub=vb&&z?ob()||("CSS1Compat"==vb.compatMode?parseInt(pb,10):5):void 0;function wb(a,b,c,d){this.c=a;this.a=b;this.b=c;this.f=d}wb.prototype.toString=function(){return"("+this.c+"t, "+this.a+"r, "+this.b+"b, "+this.f+"l)"};wb.prototype.ceil=function(){this.c=Math.ceil(this.c);this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.f=Math.ceil(this.f);return this};wb.prototype.floor=function(){this.c=Math.floor(this.c);this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.f=Math.floor(this.f);return this};
wb.prototype.round=function(){this.c=Math.round(this.c);this.a=Math.round(this.a);this.b=Math.round(this.b);this.f=Math.round(this.f);return this};wb.prototype.scale=function(a,b){b=ca(b)?b:a;this.f*=a;this.a*=a;this.c*=b;this.b*=b;return this};var xb=v("Firefox"),yb=cb()||v("iPod"),zb=v("iPad"),Ab=v("Android")&&!(jb()||v("Firefox")||v("Opera")||v("Silk")),Bb=jb(),Cb=v("Safari")&&!(jb()||v("Coast")||v("Opera")||v("Edge")||v("Silk")||v("Android"))&&!(cb()||v("iPad")||v("iPod"));var Db=z&&!(9<=Number(ub)),Eb=z&&!(8<=Number(ub));function B(a,b,c,d){this.a=a;this.b=b;this.width=c;this.height=d}B.prototype.toString=function(){return"("+this.a+", "+this.b+" - "+this.width+"w x "+this.height+"h)"};B.prototype.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};B.prototype.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
B.prototype.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};B.prototype.scale=function(a,b){b=ca(b)?b:a;this.a*=a;this.width*=a;this.b*=b;this.height*=b;return this};function Fb(a){return(a=a.exec(Ha))?a[1]:""}var Gb=function(){if(xb)return Fb(/Firefox\/([0-9.]+)/);if(z||mb||lb)return pb;if(Bb)return cb()||v("iPad")||v("iPod")?Fb(/CriOS\/([0-9.]+)/):Fb(/Chrome\/([0-9.]+)/);if(Cb&&!(cb()||v("iPad")||v("iPod")))return Fb(/Version\/([0-9.]+)/);if(yb||zb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Ha);if(a)return a[1]+"."+a[2]}else if(Ab)return(a=Fb(/Android\s+([0-9.]+)/))?a:Fb(/Version\/([0-9.]+)/);return""}();function Hb(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Ib(a,b){var c=Eb&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Hb(b,a,b.nodeName,c)};var Jb={},Kb,Lb;function Mb(a){return Nb?Kb(a):z?0<=xa(ub,a):tb(a)}function Ob(a){return Nb?Lb(a):Ab?0<=xa(Pb,a):0<=xa(Gb,a)}
var Nb=function(){if(!A)return!1;var a=aa.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;Kb=function(a){return 0<=c.compare(d,""+a)};Lb=function(a){return 0<=c.compare(e,""+a)};return!0}(),Qb=zb||yb,Rb;
if(Ab){var Sb=/Android\s+([0-9\.]+)/.exec(Ha);Rb=Sb?Sb[1]:"0"}else Rb="0";var Pb=Rb,Tb=z&&!(8<=Number(ub)),Ub=z&&!(9<=Number(ub));Ab&&Ob(2.3);Ab&&Ob(4);Cb&&Ob(6);function D(a){return a?new Vb(E(a)):ra||(ra=new Vb)}
function Wb(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){d=a.getElementsByClassName(c);if(e){a={};for(var f=b=0,g;g=d[f];f++)e==g.nodeName&&(a[b++]=g);a.length=b;return a}return d}d=a.getElementsByTagName(e||"*");if(c){a={};for(f=b=0;g=d[f];f++){var e=g.className,h;if(h="function"==typeof e.split)h=0<=Ua(e.split(/\s+/),c);h&&(a[b++]=g)}a.length=b;return a}return d}
function Xb(a){return a.scrollingElement?a.scrollingElement:nb||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement}function Yb(a){return a?a.parentWindow||a.defaultView:window}function Zb(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function $b(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function ac(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(z&&!(9<=Number(ub))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?bc(a,b):!c&&$b(e,b)?-1*cc(a,b):!d&&$b(f,a)?cc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=E(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(aa.Range.START_TO_END,a)}function cc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return bc(b,a)}function bc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function E(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var dc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},ec={IMG:" ",BR:"\n"};
function fc(a,b,c){if(!(a.nodeName in dc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in ec)b.push(ec[a.nodeName]);else for(a=a.firstChild;a;)fc(a,b,c),a=a.nextSibling}function gc(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function Vb(a){this.a=a||aa.document||document}Vb.prototype.getElementsByTagName=function(a,b){return(b||this.a).getElementsByTagName(String(a))};
function hc(a,b,c,d){return Wb(a.a,b,c,d)};function F(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(Db&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),Db&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function ic(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}Eb&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function jc(a,b,c,d,e){return(Db?kc:lc).call(null,a,b,l(c)?c:null,l(d)?d:null,e||new G)}
function kc(a,b,c,d,e){if(a instanceof La||8==a.g||c&&null===a.g){var f=b.all;if(!f)return e;var g=mc(a);if("*"!=g&&(f=b.getElementsByTagName(g),!f))return e;if(c){var h=[];for(a=0;b=f[a++];)ic(b,c,d)&&h.push(b);f=h}for(a=0;b=f[a++];)"*"==g&&"!"==b.tagName||H(e,b);return e}nc(a,b,c,d,e);return e}
function lc(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!z?(b=b.getElementsByName(d),y(b,function(b){a.a(b)&&H(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),y(b,function(b){b.className==d&&a.a(b)&&H(e,b)})):a instanceof w?nc(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.b()),y(b,function(a){ic(a,c,d)&&H(e,a)}));return e}
function oc(a,b,c,d,e){var f;if((a instanceof La||8==a.g||c&&null===a.g)&&(f=b.childNodes)){var g=mc(a);if("*"!=g&&(f=Va(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=Va(f,function(a){return ic(a,c,d)}));y(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||H(e,a)});return e}return pc(a,b,c,d,e)}function pc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)ic(b,c,d)&&a.a(b)&&H(e,b);return e}
function nc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)ic(b,c,d)&&a.a(b)&&H(e,b),nc(a,b,c,d,e)}function mc(a){if(a instanceof w){if(8==a.g)return"!";if(null===a.g)return"*"}return a.b()};function qc(a,b){b=b.toLowerCase();return"style"==b?rc(a.style.cssText):Tb&&"value"==b&&I(a,"INPUT")?a.value:Ub&&!0===a[b]?String(a.getAttribute(b)):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var sc=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function rc(a){var b=[];y(a.split(sc),function(a){var c=a.indexOf(":");0<c&&(a=[a.slice(0,c),a.slice(c+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function tc(a,b){Tb&&"value"==b&&I(a,"OPTION")&&null===qc(a,"value")?(b=[],fc(a,b,!1),a=b.join("")):a=a[b];return a}function I(a,b){b&&"string"!==typeof b&&(b=b.toString());return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};nb||A&&Mb(3.5)||z&&Mb(8);var uc={B:function(a){return!(!a.querySelectorAll||!a.querySelector)},s:function(a,b){if(!a)throw new q(32,"No class name specified");a=wa(a);if(-1!==a.indexOf(" "))throw new q(32,"Compound class names not permitted");if(uc.B(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new q(32,"An invalid or illegal class name was specified");}a=hc(D(b),"*",a,b);return a.length?a[0]:null},u:function(a,b){if(!a)throw new q(32,"No class name specified");a=wa(a);if(-1!==a.indexOf(" "))throw new q(32,
"Compound class names not permitted");if(uc.B(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new q(32,"An invalid or illegal class name was specified");}return hc(D(b),"*",a,b)}};var vc={s:function(a,b){if(!fa(b.querySelector)&&z&&Mb(8)&&!ga(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new q(32,"No selector specified");a=wa(a);try{var c=b.querySelector(a)}catch(d){throw new q(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},u:function(a,b){if(!fa(b.querySelectorAll)&&z&&Mb(8)&&!ga(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new q(32,"No selector specified");a=wa(a);try{return b.querySelectorAll(a)}catch(c){throw new q(32,
"An invalid or illegal selector was specified");}}};function wc(a){a=a?E(a):document;return!z||9<=Number(ub)||"CSS1Compat"==D(a).a.compatMode?a.documentElement:a.body};function G(){this.b=this.a=null;this.m=0}function xc(a){this.node=a;this.a=this.b=null}function yc(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;){e=c.node;var g=b.node;e==g||e instanceof Hb&&g instanceof Hb&&e.a==g.a?(e=c,c=c.a,b=b.a):0<ac(c.node,b.node)?(e=b,b=b.a):(e=c,c=c.a);(e.b=d)?d.a=e:a.a=e;d=e;f++}for(e=c||b;e;)e.b=d,d=d.a=e,f++,e=e.a;a.b=d;a.m=f;return a}function zc(a,b){b=new xc(b);b.a=a.a;a.b?a.a.b=b:a.a=a.b=b;a.a=b;a.m++}
function H(a,b){b=new xc(b);b.b=a.b;a.a?a.b.a=b:a.a=a.b=b;a.b=b;a.m++}function Ac(a){return(a=a.a)?a.node:null}G.prototype.f=function(){var a=Ac(this);return a?F(a):""};function Bc(a,b){return new Cc(a,!!b)}function Cc(a,b){this.f=a;this.b=(this.w=b)?a.b:a.a;this.a=null}function J(a){var b=a.b;if(b){var c=a.a=b;a.b=a.w?b.b:b.a;return c.node}return null};var Dc=!(z&&!Mb(10)),Ec=Ab?!Ob(4):!Qb,Fc=z&&na.navigator.msPointerEnabled;function K(a,b,c){this.g=a;this.a=b;this.b=c}K.prototype.create=function(a){a=E(a);Ub&&a.createEventObject?a=a.createEventObject():(a=a.createEvent("HTMLEvents"),a.initEvent(this.g,this.a,this.b));return a};K.prototype.toString=function(){return this.g};function L(a,b,c){K.call(this,a,b,c)}m(L,K);
L.prototype.create=function(a,b){if(!A&&this==Gc)throw new q(9,"Browser does not support a mouse pixel scroll event.");var c=E(a);if(Ub){var d=c.createEventObject();d.altKey=b.altKey;d.ctrlKey=b.ctrlKey;d.metaKey=b.metaKey;d.shiftKey=b.shiftKey;d.button=b.button;d.clientX=b.clientX;d.clientY=b.clientY;c=function(a,b){Object.defineProperty(d,a,{get:function(){return b}})};if(this==Hc||this==Ic)if(Object.defineProperty){var e=this==Hc;c("fromElement",e?a:b.relatedTarget);c("toElement",e?b.relatedTarget:
a)}else d.relatedTarget=b.relatedTarget;this==Jc&&(Object.defineProperty?c("wheelDelta",b.wheelDelta):d.detail=b.wheelDelta)}else{e=Yb(c);d=c.createEvent("MouseEvents");var f=1;this==Jc&&(A||(d.wheelDelta=b.wheelDelta),A&&(f=b.wheelDelta/-40));A&&this==Gc&&(f=b.wheelDelta);d.initMouseEvent(this.g,this.a,this.b,e,f,b.clientX,b.clientY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);if(z&&!d.pageX&&!d.pageY&&Object.defineProperty){a=Xb(D(a).a);var c=wc(c),g=b.clientX+
a.scrollLeft-c.clientLeft,h=b.clientY+a.scrollTop-c.clientTop;Object.defineProperty(d,"pageX",{get:function(){return g}});Object.defineProperty(d,"pageY",{get:function(){return h}})}}return d};function Kc(a,b,c){K.call(this,a,b,c)}m(Kc,K);
Kc.prototype.create=function(a,b){var c=E(a);if(A){a=Yb(c);var d=b.charCode?0:b.keyCode,c=c.createEvent("KeyboardEvent");c.initKeyEvent(this.g,this.a,this.b,a,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,d,b.charCode);this.g==Lc&&b.preventDefault&&c.preventDefault()}else if(Ub?c=c.createEventObject():(c=c.createEvent("Events"),c.initEvent(this.g,this.a,this.b)),c.altKey=b.altKey,c.ctrlKey=b.ctrlKey,c.metaKey=b.metaKey,c.shiftKey=b.shiftKey,c.keyCode=b.charCode||b.keyCode,nb||mb)c.charCode=this==Lc?c.keyCode:
0;return c};function Mc(a,b,c){K.call(this,a,b,c)}m(Mc,K);
Mc.prototype.create=function(a,b){function c(b){b=Wa(b,function(b){return g.createTouch(h,a,b.identifier,b.pageX,b.pageY,b.screenX,b.screenY)});return g.createTouchList.apply(g,b)}function d(b){var c=Wa(b,function(b){return{identifier:b.identifier,screenX:b.screenX,screenY:b.screenY,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,target:a}});c.item=function(a){return c[a]};return c}function e(b){return Wa(b,function(b){return new Touch({identifier:b.identifier,screenX:b.screenX,screenY:b.screenY,
clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,target:a})})}function f(a,b){switch(a){case 1:return d(b);case 2:return c(b);case 3:return e(b)}return null}if(!Dc)throw new q(9,"Browser does not support firing touch events.");var g=E(a),h=Yb(g);if(Ec)var k=1;else if(TouchEvent.prototype.initTouchEvent)k=2;else if(TouchEvent&&0<TouchEvent.length)k=3;else throw new q(9,"Not able to create touch events in this browser");var p=f(k,b.changedTouches),n=b.touches==b.changedTouches?p:f(k,
b.touches),C=b.targetTouches==b.changedTouches?p:f(k,b.targetTouches);if(1==k)k=g.createEvent("MouseEvents"),k.initMouseEvent(this.g,this.a,this.b,h,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,b.relatedTarget),k.touches=n,k.targetTouches=C,k.changedTouches=p,k.scale=b.scale,k.rotation=b.rotation;else if(2==k)k=g.createEvent("TouchEvent"),0==k.initTouchEvent.length?k.initTouchEvent(n,C,p,this.g,h,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey):k.initTouchEvent(this.g,
this.a,this.b,h,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,n,C,p,b.scale,b.rotation),k.relatedTarget=b.relatedTarget;else if(3==k)k=new TouchEvent(this.g,{touches:n,targetTouches:C,changedTouches:p,bubbles:this.a,cancelable:this.b,ctrlKey:b.ctrlKey,shiftKey:b.shiftKey,altKey:b.altKey,metaKey:b.metaKey});else throw new q(9,"Illegal TouchEventStrategy_ value (this is a bug)");return k};function Nc(a,b,c){K.call(this,a,b,c)}m(Nc,K);
Nc.prototype.create=function(a,b){if(!Fc)throw new q(9,"Browser does not support MSGesture events.");var c=E(a);a=Yb(c);c=c.createEvent("MSGestureEvent");c.initGestureEvent(this.g,this.a,this.b,a,1,0,0,b.clientX,b.clientY,0,0,b.translationX,b.translationY,b.scale,b.expansion,b.rotation,b.velocityX,b.velocityY,b.velocityExpansion,b.velocityAngular,(new Date).getTime(),b.relatedTarget);return c};function M(a,b,c){K.call(this,a,b,c)}m(M,K);
M.prototype.create=function(a,b){if(!Fc)throw new q(9,"Browser does not support MSPointer events.");var c=E(a);a=Yb(c);c=c.createEvent("MSPointerEvent");c.initPointerEvent(this.g,this.a,this.b,a,0,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget,0,0,b.width,b.height,b.pressure,b.rotation,b.tiltX,b.tiltY,b.pointerId,b.pointerType,0,b.isPrimary);return c};
var Hc=new L("mouseout",!0,!0),Ic=new L("mouseover",!0,!0),Jc=new L(A?"DOMMouseScroll":"mousewheel",!0,!0),Gc=new L("MozMousePixelScroll",!0,!0),Lc=new Kc("keypress",!0,!0),Oc={ca:new K("blur",!1,!1),da:new K("change",!0,!1),ha:new K("focus",!1,!1),ia:new K("focusin",!0,!1),ja:new K("focusout",!0,!1),la:new K("input",!0,!1),Ka:new K("orientationchange",!1,!1),La:new K("propertychange",!1,!1),Ma:new K("select",!0,!1),Na:new K("submit",!0,!0),Oa:new K("textInput",!0,!0),ea:new L("click",!0,!0),fa:new L("contextmenu",
!0,!0),ga:new L("dblclick",!0,!0),pa:new L("mousedown",!0,!0),qa:new L("mousemove",!0,!1),ra:Hc,sa:Ic,ua:new L("mouseup",!0,!0),va:Jc,ta:Gc,ma:new Kc("keydown",!0,!0),na:Lc,oa:new Kc("keyup",!0,!0),Pa:new Mc("touchend",!0,!0),Qa:new Mc("touchmove",!0,!0),Ra:new Mc("touchstart",!0,!0),wa:new Nc("MSGestureChange",!0,!0),xa:new Nc("MSGestureEnd",!0,!0),ya:new Nc("MSGestureHold",!0,!0),za:new Nc("MSGestureStart",!0,!0),Aa:new Nc("MSGestureTap",!0,!0),Ca:new Nc("MSInertiaStart",!0,!0),Ba:new M("MSGotPointerCapture",
!0,!1),Da:new M("MSLostPointerCapture",!0,!1),Ea:new M("MSPointerCancel",!0,!0),Fa:new M("MSPointerDown",!0,!0),Ga:new M("MSPointerMove",!0,!0),Ia:new M("MSPointerOver",!0,!0),Ha:new M("MSPointerOut",!0,!0),Ja:new M("MSPointerUp",!0,!0)};function N(a){this.l=a;this.b=this.h=!1;this.f=null}function x(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Pc(a,b){a.h=b}function Qc(a,b){a.b=b}function O(a,b){a=a.a(b);return a instanceof G?+a.f():+a}function P(a,b){a=a.a(b);return a instanceof G?a.f():""+a}function Rc(a,b){a=a.a(b);return a instanceof G?!!a.m:!!a};var Sc="function"===typeof ShadowRoot;
function Tc(a,b){if(a.style&&("hidden"==a.style.visibility||"none"==a.style.display))return"";if(3==a.nodeType){var c=a.data;b||(c=c.replace(/\n|\r|\t/g," "));return c.replace(/&nbsp/," ")}if(Sc&&1==a.nodeType&&null!==a.shadowRoot)return Tc(a.shadowRoot,b);if((1==a.nodeType||11==a.nodeType)&&"SCRIPT"!=a.nodeName&&"STYLE"!=a.nodeName){var d=b||"PRE"==a.tagName;c="";for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes.item(e);if(f)if(!Sc||"CONTENT"!=f.nodeName&&"SLOT"!=f.nodeName)c+=Tc(f,d);else for(var f=
"CONTENT"==f.nodeName?f.getDistributedNodes():f.assignedNodes(),g=0;g<f.length;g++){var h=f[g];h&&(c+=Tc(h,b))}}if("P"==a.tagName||"BR"==a.tagName||"HR"==a.tagName||"DIV"==a.tagName)c+="\n";c=c.replace(/&nbsp/," ");Jb.ka&&Ob(9)&&(c=c.replace(/&#100;/," "));return c}return""};function Uc(a,b,c){N.call(this,a.l);this.c=a;this.i=b;this.v=c;this.h=b.h||c.h;this.b=b.b||c.b;this.c==Vc&&(c.b||c.h||4==c.l||0==c.l||!b.f?b.b||b.h||4==b.l||0==b.l||!c.f||(this.f={name:c.f.name,A:b}):this.f={name:b.f.name,A:c})}m(Uc,N);
function Wc(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof G&&c instanceof G){b=Bc(b);for(d=J(b);d;d=J(b))for(e=Bc(c),f=J(e);f;f=J(e))if(a(F(d),F(f)))return!0;return!1}if(b instanceof G||c instanceof G){b instanceof G?(e=b,d=c):(e=c,d=b);f=Bc(e);for(var g=typeof d,h=J(f);h;h=J(f)){switch(g){case "number":h=+F(h);break;case "boolean":h=!!F(h);break;case "string":h=F(h);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(h,d)||e==c&&a(d,h))return!0}return!1}return e?
"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Uc.prototype.a=function(a){return this.c.o(this.i,this.v,a)};Uc.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+x(this.i);return a+=x(this.v)};function Xc(a,b,c,d){this.$=a;this.O=b;this.l=c;this.o=d}Xc.prototype.toString=function(){return this.$};var Yc={};
function Q(a,b,c,d){if(Yc.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new Xc(a,b,c,d);return Yc[a.toString()]=a}Q("div",6,1,function(a,b,c){return O(a,c)/O(b,c)});Q("mod",6,1,function(a,b,c){return O(a,c)%O(b,c)});Q("*",6,1,function(a,b,c){return O(a,c)*O(b,c)});Q("+",5,1,function(a,b,c){return O(a,c)+O(b,c)});Q("-",5,1,function(a,b,c){return O(a,c)-O(b,c)});Q("<",4,2,function(a,b,c){return Wc(function(a,b){return a<b},a,b,c)});
Q(">",4,2,function(a,b,c){return Wc(function(a,b){return a>b},a,b,c)});Q("<=",4,2,function(a,b,c){return Wc(function(a,b){return a<=b},a,b,c)});Q(">=",4,2,function(a,b,c){return Wc(function(a,b){return a>=b},a,b,c)});var Vc=Q("=",3,2,function(a,b,c){return Wc(function(a,b){return a==b},a,b,c,!0)});Q("!=",3,2,function(a,b,c){return Wc(function(a,b){return a!=b},a,b,c,!0)});Q("and",2,2,function(a,b,c){return Rc(a,c)&&Rc(b,c)});Q("or",1,2,function(a,b,c){return Rc(a,c)||Rc(b,c)});function Zc(a,b){if(b.a.length&&4!=a.l)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");N.call(this,a.l);this.c=a;this.i=b;this.h=a.h;this.b=a.b}m(Zc,N);Zc.prototype.a=function(a){a=this.c.a(a);return $c(this.i,a)};Zc.prototype.toString=function(){var a="Filter:"+x(this.c);return a+=x(this.i)};function ad(a,b){if(b.length<a.M)throw Error("Function "+a.j+" expects at least"+a.M+" arguments, "+b.length+" given");if(null!==a.F&&b.length>a.F)throw Error("Function "+a.j+" expects at most "+a.F+" arguments, "+b.length+" given");a.Z&&y(b,function(b,d){if(4!=b.l)throw Error("Argument "+d+" to function "+a.j+" is not of type Nodeset: "+b);});N.call(this,a.l);this.C=a;this.c=b;Pc(this,a.h||Ya(b,function(a){return a.h}));Qc(this,a.Y&&!b.length||a.X&&!!b.length||Ya(b,function(a){return a.b}))}
m(ad,N);ad.prototype.a=function(a){return this.C.o.apply(null,ab(a,this.c))};ad.prototype.toString=function(){var a="Function: "+this.C;if(this.c.length)var b=Xa(this.c,function(a,b){return a+x(b)},"Arguments:"),a=a+x(b);return a};function bd(a,b,c,d,e,f,g,h,k){this.j=a;this.l=b;this.h=c;this.Y=d;this.X=e;this.o=f;this.M=g;this.F=ba(h)?h:g;this.Z=!!k}bd.prototype.toString=function(){return this.j};var cd={};
function R(a,b,c,d,e,f,g,h){if(cd.hasOwnProperty(a))throw Error("Function already created: "+a+".");cd[a]=new bd(a,b,c,d,!1,e,f,g,h)}R("boolean",2,!1,!1,function(a,b){return Rc(b,a)},1);R("ceiling",1,!1,!1,function(a,b){return Math.ceil(O(b,a))},1);R("concat",3,!1,!1,function(a,b){return Xa(bb(arguments,1),function(b,d){return b+P(d,a)},"")},2,null);R("contains",2,!1,!1,function(a,b,c){b=P(b,a);a=P(c,a);return-1!=b.indexOf(a)},2);R("count",1,!1,!1,function(a,b){return b.a(a).m},1,1,!0);
R("false",2,!1,!1,function(){return!1},0);R("floor",1,!1,!1,function(a,b){return Math.floor(O(b,a))},1);R("id",4,!1,!1,function(a,b){function c(a){if(Db){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return $a(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument;a=P(b,a).split(/\s+/);var f=[];y(a,function(a){a=c(a);!a||0<=Ua(f,a)||f.push(a)});f.sort(ac);var g=new G;y(f,function(a){H(g,a)});return g},1);
R("lang",2,!1,!1,function(){return!1},1);R("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);R("local-name",3,!1,!0,function(a,b){return(a=b?Ac(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);R("name",3,!1,!0,function(a,b){return(a=b?Ac(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);R("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
R("normalize-space",3,!1,!0,function(a,b){return(b?P(b,a):F(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);R("not",2,!1,!1,function(a,b){return!Rc(b,a)},1);R("number",1,!1,!0,function(a,b){return b?O(b,a):+F(a.a)},0,1);R("position",1,!0,!1,function(a){return a.b},0);R("round",1,!1,!1,function(a,b){return Math.round(O(b,a))},1);R("starts-with",2,!1,!1,function(a,b,c){b=P(b,a);a=P(c,a);return!b.lastIndexOf(a,0)},2);R("string",3,!1,!0,function(a,b){return b?P(b,a):F(a.a)},0,1);
R("string-length",1,!1,!0,function(a,b){return(b?P(b,a):F(a.a)).length},0,1);R("substring",3,!1,!1,function(a,b,c,d){c=O(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?O(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=P(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);R("substring-after",3,!1,!1,function(a,b,c){b=P(b,a);a=P(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
R("substring-before",3,!1,!1,function(a,b,c){b=P(b,a);a=P(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);R("sum",1,!1,!1,function(a,b){a=Bc(b.a(a));b=0;for(var c=J(a);c;c=J(a))b+=+F(c);return b},1,1,!0);R("translate",3,!1,!1,function(a,b,c,d){b=P(b,a);c=P(c,a);var e=P(d,a);d={};for(var f=0;f<c.length;f++)a=c.charAt(f),a in d||(d[a]=e.charAt(f));c="";for(f=0;f<b.length;f++)a=b.charAt(f),c+=a in d?d[a]:a;return c},3);R("true",2,!1,!1,function(){return!0},0);function dd(a){N.call(this,3);this.c=a.substring(1,a.length-1)}m(dd,N);dd.prototype.a=function(){return this.c};dd.prototype.toString=function(){return"Literal: "+this.c};function ed(a){N.call(this,1);this.c=a}m(ed,N);ed.prototype.a=function(){return this.c};ed.prototype.toString=function(){return"Number: "+this.c};function fd(a,b){N.call(this,a.l);this.i=a;this.c=b;this.h=a.h;this.b=a.b;1==this.c.length&&(a=this.c[0],a.D||a.c!=gd||(a=a.v,"*"!=a.b()&&(this.f={name:a.b(),A:null})))}m(fd,N);function hd(){N.call(this,4)}m(hd,N);hd.prototype.a=function(a){var b=new G;a=a.a;9==a.nodeType?H(b,a):H(b,a.ownerDocument);return b};hd.prototype.toString=function(){return"Root Helper Expression"};function id(){N.call(this,4)}m(id,N);id.prototype.a=function(a){var b=new G;H(b,a.a);return b};id.prototype.toString=function(){return"Context Helper Expression"};
function jd(a){return"/"==a||"//"==a}fd.prototype.a=function(a){var b=this.i.a(a);if(!(b instanceof G))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.m;c++){var e=a[c],f=Bc(b,e.c.w);if(e.h||e.c!=kd)if(e.h||e.c!=ld){var g=J(f);for(b=e.a(new Aa(g));g=J(f);)g=e.a(new Aa(g)),b=yc(b,g)}else g=J(f),b=e.a(new Aa(g));else{for(g=J(f);(b=J(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new Aa(g))}}return b};
fd.prototype.toString=function(){var a="Path Expression:"+x(this.i);if(this.c.length){var b=Xa(this.c,function(a,b){return a+x(b)},"Steps:");a+=x(b)}return a};function md(a,b){this.a=a;this.w=!!b}
function $c(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=Bc(b),f=b.m,g,h=0;g=J(e);h++){var k=a.w?f-h:h+1;g=d.a(new Aa(g,k,f));if("number"==typeof g)k=k==g;else if("string"==typeof g||"boolean"==typeof g)k=!!g;else if(g instanceof G)k=0<g.m;else throw Error("Predicate.evaluate returned an unexpected type.");if(!k){k=e;g=k.f;var p=k.a;if(!p)throw Error("Next must be called at least once before remove.");var n=p.b,p=p.a;n?n.a=p:g.a=p;p?p.b=n:g.b=n;g.m--;k.a=null}}return b}
md.prototype.toString=function(){return Xa(this.a,function(a,b){return a+x(b)},"Predicates:")};function nd(a){N.call(this,1);this.c=a;this.h=a.h;this.b=a.b}m(nd,N);nd.prototype.a=function(a){return-O(this.c,a)};nd.prototype.toString=function(){return"Unary Expression: -"+x(this.c)};function od(a){N.call(this,4);this.c=a;Pc(this,Ya(this.c,function(a){return a.h}));Qc(this,Ya(this.c,function(a){return a.b}))}m(od,N);od.prototype.a=function(a){var b=new G;y(this.c,function(c){c=c.a(a);if(!(c instanceof G))throw Error("Path expression must evaluate to NodeSet.");b=yc(b,c)});return b};od.prototype.toString=function(){return Xa(this.c,function(a,b){return a+x(b)},"Union Expression:")};function pd(a,b,c,d){N.call(this,4);this.c=a;this.v=b;this.i=c||new md([]);this.D=!!d;b=this.i;b=0<b.a.length?b.a[0].f:null;a.ba&&b&&(a=b.name,a=Db?a.toLowerCase():a,this.f={name:a,A:b.A});a:{a=this.i;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.h||1==c.l||0==c.l){a=!0;break a}a=!1}this.h=a}m(pd,N);
pd.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.A?P(c.A,a):null,f=1);if(this.D)if(this.h||this.c!=qd)if(b=Bc((new pd(rd,new w("node"))).a(a)),c=J(b))for(a=this.o(c,d,e,f);c=J(b);)a=yc(a,this.o(c,d,e,f));else a=new G;else a=jc(this.v,b,d,e),a=$c(this.i,a,f);else a=this.o(a.a,d,e,f);return a};pd.prototype.o=function(a,b,c,d){a=this.c.C(this.v,a,b,c);return a=$c(this.i,a,d)};
pd.prototype.toString=function(){var a="Step:"+x("Operator: "+(this.D?"//":"/"));this.c.j&&(a+=x("Axis: "+this.c));a+=x(this.v);if(this.i.a.length){var b=Xa(this.i.a,function(a,b){return a+x(b)},"Predicates:");a+=x(b)}return a};function sd(a,b,c,d){this.j=a;this.C=b;this.w=c;this.ba=d}sd.prototype.toString=function(){return this.j};var td={};function S(a,b,c,d){if(td.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new sd(a,b,c,!!d);return td[a]=b}
S("ancestor",function(a,b){for(var c=new G;b=b.parentNode;)a.a(b)&&zc(c,b);return c},!0);S("ancestor-or-self",function(a,b){var c=new G;do a.a(b)&&zc(c,b);while(b=b.parentNode);return c},!0);
var gd=S("attribute",function(a,b){var c=new G,d=a.b();if("style"==d&&Db&&b.style)return H(c,new Hb(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof w&&null===a.g||"*"==d)for(d=0;a=e[d];d++)Db?a.nodeValue&&H(c,Ib(b,a)):H(c,a);else(a=e.getNamedItem(d))&&(Db?a.nodeValue&&H(c,Ib(b,a)):H(c,a));return c},!1),qd=S("child",function(a,b,c,d,e){return(Db?oc:pc).call(null,a,b,l(c)?c:null,l(d)?d:null,e||new G)},!1,!0);S("descendant",jc,!1,!0);
var rd=S("descendant-or-self",function(a,b,c,d){var e=new G;ic(b,c,d)&&a.a(b)&&H(e,b);return jc(a,b,c,d,e)},!1,!0),kd=S("following",function(a,b,c,d){var e=new G;do for(var f=b;f=f.nextSibling;)ic(f,c,d)&&a.a(f)&&H(e,f),e=jc(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);S("following-sibling",function(a,b){for(var c=new G;b=b.nextSibling;)a.a(b)&&H(c,b);return c},!1);S("namespace",function(){return new G},!1);
var ud=S("parent",function(a,b){var c=new G;if(9==b.nodeType)return c;if(2==b.nodeType)return H(c,b.ownerElement),c;b=b.parentNode;a.a(b)&&H(c,b);return c},!1),ld=S("preceding",function(a,b,c,d){var e=new G,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,h=f.length;g<h;g++){var k=[];for(b=f[g];b=b.previousSibling;)k.unshift(b);for(var p=0,n=k.length;p<n;p++)b=k[p],ic(b,c,d)&&a.a(b)&&H(e,b),e=jc(a,b,c,d,e)}return e},!0,!0);
S("preceding-sibling",function(a,b){for(var c=new G;b=b.previousSibling;)a.a(b)&&zc(c,b);return c},!0);var vd=S("self",function(a,b){var c=new G;a.a(b)&&H(c,b);return c},!1);function wd(a,b){this.a=a;this.b=b}function xd(a){for(var b,c=[];;){T(a,"Missing right hand side of binary expression.");b=yd(a);var d=u(a.a);if(!d)break;var e=(d=Yc[d]||null)&&d.O;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].O;)b=new Uc(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Uc(c.pop(),c.pop(),b);return b}function T(a,b){if(Fa(a.a))throw Error(b);}function zd(a,b){a=u(a.a);if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function Ad(a){a=u(a.a);if(")"!=a)throw Error("Bad token: "+a);}function Bd(a){a=u(a.a);if(2>a.length)throw Error("Unclosed literal string");return new dd(a)}
function Cd(a){var b=[];if(jd(t(a.a))){var c=u(a.a);var d=t(a.a);if("/"==c&&(Fa(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new hd;d=new hd;T(a,"Missing next location step.");c=Dd(a,c);b.push(c)}else{a:{c=t(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":u(a.a);c=xd(a);T(a,'unclosed "("');zd(a,")");break;case '"':case "'":c=Bd(a);break;default:if(isNaN(+c))if(!Ka(c)&&/(?![0-9])[\w]/.test(d)&&"("==t(a.a,1)){c=u(a.a);
c=cd[c]||null;u(a.a);for(d=[];")"!=t(a.a);){T(a,"Missing function argument list.");d.push(xd(a));if(","!=t(a.a))break;u(a.a)}T(a,"Unclosed function argument list.");Ad(a);c=new ad(c,d)}else{c=null;break a}else c=new ed(+u(a.a))}"["==t(a.a)&&(d=new md(Ed(a)),c=new Zc(c,d))}if(c)if(jd(t(a.a)))d=c;else return c;else c=Dd(a,"/"),d=new id,b.push(c)}for(;jd(t(a.a));)c=u(a.a),T(a,"Missing next location step."),c=Dd(a,c),b.push(c);return new fd(d,b)}
function Dd(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==t(a.a)){var c=new pd(vd,new w("node"));u(a.a);return c}if(".."==t(a.a))return c=new pd(ud,new w("node")),u(a.a),c;if("@"==t(a.a)){var d=gd;u(a.a);T(a,"Missing attribute name")}else if("::"==t(a.a,1)){if(!/(?![0-9])[\w]/.test(t(a.a).charAt(0)))throw Error("Bad token: "+u(a.a));var e=u(a.a);d=td[e]||null;if(!d)throw Error("No axis with name: "+e);u(a.a);T(a,"Missing node name")}else d=qd;e=t(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==
t(a.a,1)){if(!Ka(e))throw Error("Invalid node type: "+e);e=u(a.a);if(!Ka(e))throw Error("Invalid type name: "+e);zd(a,"(");T(a,"Bad nodetype");var f=t(a.a).charAt(0),g=null;if('"'==f||"'"==f)g=Bd(a);T(a,"Bad nodetype");Ad(a);e=new w(e,g)}else if(e=u(a.a),f=e.indexOf(":"),-1==f)e=new La(e);else{var g=e.substring(0,f);if("*"==g)var h="*";else if(h=a.b(g),!h)throw Error("Namespace prefix not declared: "+g);e=e.substr(f+1);e=new La(e,h)}else throw Error("Bad token: "+u(a.a));a=new md(Ed(a),d.w);return c||
new pd(d,e,a,"//"==b)}function Ed(a){for(var b=[];"["==t(a.a);){u(a.a);T(a,"Missing predicate expression.");var c=xd(a);b.push(c);T(a,"Unclosed predicate expression.");zd(a,"]")}return b}function yd(a){if("-"==t(a.a))return u(a.a),new nd(yd(a));var b=Cd(a);if("|"!=t(a.a))a=b;else{for(b=[b];"|"==u(a.a);)T(a,"Missing next union location path."),b.push(Cd(a));a.a.a--;a=new od(b)}return a};function Fd(a,b){if(!a.length)throw Error("Empty XPath expression.");a=Ca(a);if(Fa(a))throw Error("Invalid XPath expression.");b?fa(b)||(b=ja(b.lookupNamespaceURI,b)):b=function(){return null};var c=xd(new wd(a,b));if(!Fa(a))throw Error("Bad token: "+u(a));this.evaluate=function(a,b){a=c.a(new Aa(a));return new U(a,b)}}
function U(a,b){if(!b)if(a instanceof G)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof G))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof G?a.f():""+a;break;case 1:this.numberValue=a instanceof G?+a.f():+a;break;case 3:this.booleanValue=a instanceof G?0<a.m:!!a;break;case 4:case 5:case 6:case 7:var c=
Bc(a);var d=[];for(var e=J(c);e;e=J(c))d.push(e instanceof Hb?e.a:e);this.snapshotLength=a.m;this.invalidIteratorState=!1;break;case 8:case 9:a=Ac(a);this.singleNodeValue=a instanceof Hb?a.a:a;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=d.length||
0>a?null:d[a]}}U.ANY_TYPE=0;U.NUMBER_TYPE=1;U.STRING_TYPE=2;U.BOOLEAN_TYPE=3;U.UNORDERED_NODE_ITERATOR_TYPE=4;U.ORDERED_NODE_ITERATOR_TYPE=5;U.UNORDERED_NODE_SNAPSHOT_TYPE=6;U.ORDERED_NODE_SNAPSHOT_TYPE=7;U.ANY_UNORDERED_NODE_TYPE=8;U.FIRST_ORDERED_NODE_TYPE=9;function Gd(a){this.lookupNamespaceURI=Ma(a)}
function Hd(a,b){a=a||aa;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=U,c.evaluate=function(a,b,c,g){return(new Fd(a,c)).evaluate(b,g)},c.createExpression=function(a,b){return new Fd(a,b)},c.createNSResolver=function(a){return new Gd(a)}}da("wgxpath.install",Hd);var V={};V.G=function(){var a={Va:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
V.o=function(a,b,c){var d=E(a);if(!d.documentElement)return null;(z||Ab)&&Hd(Yb(d));try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):V.G;if(z&&!tb(7))return d.evaluate.call(d,b,a,e,c,null);if(!z||9<=Number(ub)){for(var f={},g=d.getElementsByTagName("*"),h=0;h<g.length;++h){var k=g[h],p=k.namespaceURI;if(p&&!f[p]){var n=k.lookupPrefix(p);if(!n)var C=p.match(".*/(\\w+)/?$"),n=C?C[1]:"xhtml";f[p]=n}}var W={},ma;for(ma in f)W[f[ma]]=ma;e=function(a){return W[a]||null}}try{return d.evaluate(b,
a,e,c,null)}catch(Oa){if("TypeError"===Oa.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):V.G,d.evaluate(b,a,e,c,null);throw Oa;}}catch(Oa){if(!A||"NS_ERROR_ILLEGAL_VALUE"!=Oa.name)throw new q(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+Oa);}};V.H=function(a,b){if(!a||1!=a.nodeType)throw new q(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
V.s=function(a,b){var c=function(){var c=V.o(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=E(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||V.H(c,a);return c};
V.u=function(a,b){var c=function(){var c=V.o(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=E(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();y(c,function(b){V.H(b,a)});return c};var Id="function"===typeof ShadowRoot;function Jd(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return I(a)?a:null}
function X(a,b){b=za(b);if("float"==b||"cssFloat"==b||"styleFloat"==b)b=Ub?"styleFloat":"cssFloat";a:{var c=b;var d=E(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||Kd(a,b);if(null===a)a=null;else if(0<=Ua(db,b)){b:{var e=a.match(gb);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),e=Number(e[4]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d&&0<=e&&1>=e)){b=[b,c,d,e];break b}b=null}if(!b)b:{if(d=a.match(hb))if(b=
Number(d[1]),c=Number(d[2]),d=Number(d[3]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=pa[b.toLowerCase()];if(!c&&(c="#"==b.charAt(0)?b:"#"+b,4==c.length&&(c=c.replace(eb,"#$1$1$2$2$3$3")),!fb.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}
function Kd(a,b){var c=a.currentStyle||a.style,d=c[b];!ba(d)&&fa(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?ba(d)?d:null:(a=Jd(a))?Kd(a,b):null}
function Ld(a,b,c){function d(a){var b=Md(a);return 0<b.height&&0<b.width?!0:I(a,"PATH")&&(0<b.height||0<b.width)?(a=X(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=X(a,"overflow")&&Ya(a.childNodes,function(a){return 3==a.nodeType||I(a)&&d(a)})}function e(a){return Nd(a)==Y&&Za(a.childNodes,function(a){return!I(a)||e(a)||!d(a)})}if(!I(a))throw Error("Argument to isShown must be of type Element");if(I(a,"BODY"))return!0;if(I(a,"OPTION")||I(a,"OPTGROUP"))return a=gc(a,function(a){return I(a,"SELECT")}),
!!a&&Ld(a,!0,c);var f=Od(a);if(f)return!!f.K&&0<f.rect.width&&0<f.rect.height&&Ld(f.K,b,c);if(I(a,"INPUT")&&"hidden"==a.type.toLowerCase()||I(a,"NOSCRIPT"))return!1;f=X(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||Pd(a))&&d(a)?!e(a):!1}
function Qd(a){function b(a){if(I(a)&&"none"==X(a,"display"))return!1;var c;(c=a.parentNode)&&c.shadowRoot&&void 0!==a.assignedSlot?c=a.assignedSlot?a.assignedSlot.parentNode:null:a.getDestinationInsertionPoints&&(a=a.getDestinationInsertionPoints(),0<a.length&&(c=a[a.length-1]));if(Id&&c instanceof ShadowRoot){if(c.host.shadowRoot!==c)return!1;c=c.host}return!c||9!=c.nodeType&&11!=c.nodeType?c&&b(c):!0}return Ld(a,!1,b)}var Y="hidden";
function Nd(a){function b(a){function b(a){return a==g?!0:!X(a,"display").lastIndexOf("inline",0)||"absolute"==c&&"static"==X(a,"position")?!1:!0}var c=X(a,"position");if("fixed"==c)return p=!0,a==g?null:g;for(a=Jd(a);a&&!b(a);)a=Jd(a);return a}function c(a){var b=a;if("visible"==k)if(a==g&&h)b=h;else if(a==h)return{x:"visible",y:"visible"};b={x:X(b,"overflow-x"),y:X(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new Vb(f)).a;
a=Xb(b);b=b.parentWindow||b.defaultView;a=z&&tb("10")&&b.pageYOffset!=a.scrollTop?new kb(a.scrollLeft,a.scrollTop):new kb(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new kb(a.scrollLeft,a.scrollTop);return a}var e=Rd(a);var f=E(a),g=f.documentElement,h=f.body,k=X(g,"overflow"),p;for(a=b(a);a;a=b(a)){var n=c(a);if("visible"!=n.x||"visible"!=n.y){var C=Md(a);if(!C.width||!C.height)return Y;var W=e.a<C.a,ma=e.b<C.b;if(W&&"hidden"==n.x||ma&&"hidden"==n.y)return Y;if(W&&"visible"!=n.x||
ma&&"visible"!=n.y){W=d(a);ma=e.b<C.b-W.y;if(e.a<C.a-W.x&&"visible"!=n.x||ma&&"visible"!=n.x)return Y;e=Nd(a);return e==Y?Y:"scroll"}W=e.f>=C.a+C.width;C=e.c>=C.b+C.height;if(W&&"hidden"==n.x||C&&"hidden"==n.y)return Y;if(W&&"visible"!=n.x||C&&"visible"!=n.y){if(p&&(n=d(a),e.f>=g.scrollWidth-n.x||e.a>=g.scrollHeight-n.y))return Y;e=Nd(a);return e==Y?Y:"scroll"}}}return"none"}
function Md(a){var b=Od(a);if(b)return b.rect;if(I(a,"HTML"))return a=E(a),a=(Yb(a)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new sa(a.clientWidth,a.clientHeight),new B(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new B(0,0,0,0)}b=new B(c.left,c.top,c.right-c.left,c.bottom-c.top);z&&a.ownerDocument.body&&(a=E(a),b.a-=a.documentElement.clientLeft+a.body.clientLeft,b.b-=a.documentElement.clientTop+a.body.clientTop);return b}
function Od(a){var b=I(a,"MAP");if(!b&&!I(a,"AREA"))return null;var c=b?a:I(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=V.s('/descendant::*[@usemap = "#'+c.name+'"]',E(c)))&&(e=Md(d),b||"default"==a.shape.toLowerCase()||(a=Sd(a),b=Math.min(Math.max(a.a,0),e.width),c=Math.min(Math.max(a.b,0),e.height),e=new B(b+e.a,c+e.b,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{K:d,rect:e||new B(0,0,0,0)}}
function Sd(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new B(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new B(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new B(b,c,d-b,e-c)}return new B(0,0,0,0)}function Rd(a){a=Md(a);return new wb(a.b,a.a+a.width,a.b+a.height,a.a)}
function Td(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function Ud(a){var b=[];Id?Vd(a,b):Wd(a,b);a=Wa(b,Td);return Td(a.join("\n")).replace(/\xa0/g," ")}
function Xd(a,b,c){if(I(a,"BR"))b.push("");else{var d=I(a,"TD"),e=X(a,"display"),f=!d&&!(0<=Ua(Yd,e)),g=ba(a.previousElementSibling)?a.previousElementSibling:Zb(a.previousSibling),g=g?X(g,"display"):"",h=X(a,"float")||X(a,"cssFloat")||X(a,"styleFloat");!f||"run-in"==g&&"none"==h||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var k=Qd(a),p=null,n=null;k&&(p=X(a,"white-space"),n=X(a,"text-transform"));y(a.childNodes,function(a){c(a,b,k,p,n)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||va(a," ")||
(b[b.length-1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function Wd(a,b){Xd(a,b,function(a,b,e,f,g){3==a.nodeType&&e?Zd(a,b,f,g):I(a)&&Wd(a,b)})}var Yd="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function Zd(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";va(c," ")&&!a.lastIndexOf(" ",0)&&(a=a.substr(1));b.push(c+a)}
function Pd(a){if(Ub){if("relative"==X(a,"position"))return 1;a=X(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return $d(a)}function $d(a){var b=1,c=X(a,"opacity");c&&(b=Number(c));(a=Jd(a))&&(b*=$d(a));return b}
function ae(a,b,c,d,e){var f;if(3==a.nodeType&&c)Zd(a,b,d,e);else if(I(a))if(I(a,"CONTENT")||I(a,"SLOT")){for(f=a;f.parentNode;)f=f.parentNode;f instanceof ShadowRoot?(a=I(a,"CONTENT")?a.getDistributedNodes():a.assignedNodes(),y(a,function(a){ae(a,b,c,d,e)})):Vd(a,b)}else if(I(a,"SHADOW")){for(f=a;f.parentNode;)f=f.parentNode;if(f instanceof ShadowRoot&&(a=f))for(a=a.olderShadowRoot;a;)y(a.childNodes,function(a){ae(a,b,c,d,e)}),a=a.olderShadowRoot}else Vd(a,b)}
function Vd(a,b){a.shadowRoot&&y(a.shadowRoot.childNodes,function(a){ae(a,b,!0,null,null)});Xd(a,b,function(a,b,e,f,g){var c=null;1==a.nodeType?c=a:3==a.nodeType&&(c=a);c&&(c.assignedSlot||c.getDestinationInsertionPoints&&0<c.getDestinationInsertionPoints().length)||ae(a,b,e,f,g)})};var be={B:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},s:function(a,b){var c=D(b),d=l(a)?c.a.getElementById(a):a;return d?qc(d,"id")==a&&b!=d&&$b(b,d)?d:$a(hc(c,"*"),function(c){return qc(c,"id")==a&&b!=c&&$b(b,c)}):null},u:function(a,b){if(!a)return[];if(be.B(b,a))try{return b.querySelectorAll("#"+be.U(a))}catch(c){return[]}b=hc(D(b),"*",null,b);return Va(b,function(b){return qc(b,"id")==a})},U:function(a){return a.replace(/([\s'"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var ce={},de={};ce.P=function(a,b,c){try{var d=vc.u("a",b)}catch(e){d=hc(D(b),"A",null,b)}return $a(d,function(b){b=Ud(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};ce.L=function(a,b,c){try{var d=vc.u("a",b)}catch(e){d=hc(D(b),"A",null,b)}return Va(d,function(b){b=Ud(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};ce.s=function(a,b){return ce.P(a,b,!1)};ce.u=function(a,b){return ce.L(a,b,!1)};de.s=function(a,b){return ce.P(a,b,!0)};
de.u=function(a,b){return ce.L(a,b,!0)};var ee={index:function(a,b){var c=Number(a);if(isNaN(c)||0>c)throw new Ga("Illegal Index: "+a);if(b.length<=c)throw new Ga("Index out of range: "+a);return[b[c]]},name:function(a,b){return Va(b,function(b){return tc(b,"name")==a})},value:function(a,b){return Va(b,function(b){return tc(b,"value")===a})}};var fe={className:uc,"class name":uc,css:vc,"css selector":vc,id:be,linkText:ce,"link text":ce,name:{s:function(a,b){b=hc(D(b),"*",null,b);return $a(b,function(b){return qc(b,"name")==a})},u:function(a,b){b=hc(D(b),"*",null,b);return Va(b,function(b){return qc(b,"name")==a})}},partialLinkText:de,"partial link text":de,tagName:ib,"tag name":ib,xpath:V};
function ge(a,b){a:{for(c in a)if(a.hasOwnProperty(c))break a;var c=null}if(c){var d=fe[c];if(d&&fa(d.s))return d.s(a[c],b||na.document)}throw Error("Unsupported locator strategy: "+c);};var Z={W:function(a,b){return a.lastIndexOf("//",0)?a.lastIndexOf("document.",0)?Z.J(a,b):Z.I(a,b):Z.R(a,b)},S:function(a,b){return he(b||E(na),function(b){return b.alt==a})},T:function(a,b){return he(b||E(na),function(b){return b.className==a})},I:function(a){var b=null;try{b=eval(a)}catch(c){return null}return b?b:null},V:function(a,b){return ge({id:a},b)},J:function(a,b){return Z.id(a,b)||Z.name(a,b)},j:function(a,b){b=b||E(na);D(b);b=Wb(document,"*",null,b);a=a.split(" ");for(a[0]="name="+a[0];a.length;){var c=
a.shift(),d=b;b="value";var e=c.match(/^([A-Za-z]+)=(.+)/);e&&(b=e[1].toLowerCase(),c=e[2]);e=ee[b];if(!e)throw new Ga("Unrecognised element-filter type: '"+b+"'");b=e(c,d)}return 0<b.length?b[0]:null},aa:function(a,b){try{a:{a=decodeURIComponent(a);b=b||document;var c=b||document,d=c.$wdc_;d||(d=c.$wdc_={},d.N=la());d.N||(d.N=la());var e=d;if(!(null!==e&&a in e))throw new q(10,"Element does not exist in cache");var f=e[a];if(null!==f&&"setInterval"in f){if(f.closed)throw delete e[a],new q(23,"Window has been closed.");
var g=f}else{for(d=f;d;){if(d==b.documentElement){g=f;break a}d=d.parentNode}delete e[a];throw new q(10,"Element is no longer attached to the DOM");}}return g}catch(h){return null}},R:function(a,b){var c=va(a,"/"),d={xpath:a};try{var e=ge(d,b);if(e||!c)return e}catch(f){if(!c)throw f;}d={xpath:a.substring(0,a.length-1)};return ge(d,b)}};Z.alt=Z.S;Z["class"]=Z.T;Z.dom=Z.I;Z.id=Z.V;Z.identifier=Z.J;Z.implicit=Z.W;
Z.link=function(a,b){b=(b||E(na)).getElementsByTagName("a");for(var c=0;c<b.length;c++){var d=b[c],e=d,f="";A&&"1.8"<=pb||nb||z?f=Tc(e,!1):e.textContent?f=e.textContent:e.innerText&&(f=e.innerText);e=f=f.replace(/\r\n|\r/g,"\n");e=e.replace(/\ +/g," ");f=new RegExp(String.fromCharCode(160),"g");if(nb)for(f=String.fromCharCode(160);-1!=e.indexOf(f);)e=e.replace(f," ");else e=e.replace(f," ");var f=e,e=wa(f),g=a,f="glob",h=/^([a-zA-Z-]+):(.*)/.exec(g);if(h){var k=h[1],h=h[2];Ta[k.toLowerCase()]&&(f=
k.toLowerCase(),g=h)}k=Ta[f];if(!k)throw new Ga("Cannot find pattern matching strategy: "+f);"glob"==f?(g.indexOf("glob:")||(g=g.substring(5)),k=Ta.glob):"exact"!=f||g.indexOf("exact:")||(g=g.substring(6));g=ka(k,g);g.Ta=f;if(g(e))return d}return null};Z.name=Z.j;Z.stored=Z.aa;Z.xpath=Z.R;function ie(a,b,c,d){var e=Z[a];if(!e)throw new Ga("Unrecognised locator type: '"+a+"'");if(c=e.call(null,b,c))return c;if(!d)return null;for(e=0;e<d.frames.length;e++){try{var f=d.frames[e].document}catch(g){}if(f&&(c=ie(a,b,f,d.frames[e])))return c}return null}function he(a,b){for(var c=a.childNodes.length,d=0;d<c;d++){var e=a.childNodes[d];if(1==e.nodeType&&(b(e)||(e=he(e,b))))return e}return null};function je(a){var b="";a&&(b=a.toUpperCase());return(b=Oc[b])?b:{create:function(b){b=E(b);Ub&&b.createEventObject?b=b.createEventObject():(b=b.createEvent("HTMLEvents"),b.initEvent(a,!0,!0));return b},g:a}};da("_",function(a,b){var c;if(l(a)){(c=a.match(/^([A-Za-z]+)=.+/))?(c=c[1].toLowerCase(),c={type:c,string:a.substring(c.length+1)}):(c={string:"",type:""},c.string=a,c.type=a.lastIndexOf("//",0)?a.lastIndexOf("document.",0)?"identifier":"dom":"xpath");var d=na||na;c=ie(c.type,c.string,d.document,d);if(!c)throw new Ga("Element "+a+" not found");}else c=a;a=je(b);if(!a)throw Error("Unable to find type for: "+b);b=c;c=a.create(b,void 0);"isTrusted"in c||(c.isTrusted=!1);Ub&&b.fireEvent?b.fireEvent("on"+
a.g,c):b.dispatchEvent(c)});; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
