function(){return function(){var aa=this;function l(a){return void 0!==a}function m(a){return"string"==typeof a}function ba(a){return"number"==typeof a}function ca(a,b){a=a.split(".");var c=aa;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ea(a){return"function"==da(a)}function fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ga(a,b,c){return a.call.apply(a.bind,arguments)}
function ha(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ia(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia=ga:ia=ha;return ia.apply(null,arguments)}
function ja(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var ka=Date.now||function(){return+new Date};function q(a,b){function c(){}c.prototype=b.prototype;a.Ua=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Sa=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var la=window;function r(a,b){this.code=a;this.a=t[a]||ma;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}q(r,Error);var ma="unknown error",t={15:"element not selectable",11:"element not visible"};t[31]=ma;t[30]=ma;t[24]="invalid cookie domain";t[29]="invalid element coordinates";t[12]="invalid element state";
t[32]="invalid selector";t[51]="invalid selector";t[52]="invalid selector";t[17]="javascript error";t[405]="unsupported operation";t[34]="move target out of bounds";t[27]="no such alert";t[7]="no such element";t[8]="no such frame";t[23]="no such window";t[28]="script timeout";t[33]="session not created";t[10]="stale element reference";t[21]="timeout";t[25]="unable to set cookie";t[26]="unexpected alert open";t[13]=ma;t[9]="unknown command";r.prototype.toString=function(){return this.name+": "+this.message};var oa={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};function pa(a){if(Error.captureStackTrace)Error.captureStackTrace(this,pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}q(pa,Error);pa.prototype.name="CustomError";var qa;function ra(a,b){this.width=a;this.height=b}ra.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};ra.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};ra.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};ra.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
ra.prototype.scale=function(a,b){b=ba(b)?b:a;this.width*=a;this.height*=b;return this};function sa(a,b){var c=ta;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};function ua(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var va=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function wa(a,b){var c=0;a=va(String(a)).split(".");b=va(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;!c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=xa(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||xa(0==f[2].length,0==g[2].length)||xa(f[2],g[2]);f=f[3];g=g[3]}while(!c)}return c}function xa(a,b){return a<b?-1:a>b?1:0}
function ya(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function za(a,b,c){this.a=a;this.b=b||1;this.f=c||1};function Aa(a){this.b=a;this.a=0}function Ba(a){a=a.match(Ca);for(var b=0;b<a.length;b++)Da.test(a[b])&&a.splice(b,1);return new Aa(a)}var Ca=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,Da=/^\s/;function u(a,b){return a.b[a.a+(b||0)]}function v(a){return a.b[a.a++]}function Ea(a){return a.b.length<=a.a};function Fa(a){pa.call(this,a)}q(Fa,pa);var Ga;a:{var Ha=aa.navigator;if(Ha){var Ia=Ha.userAgent;if(Ia){Ga=Ia;break a}}Ga=""}function w(a){return-1!=Ga.indexOf(a)};function x(a,b){this.c=a;this.f=l(b)?b:null;this.g=null;switch(a){case "comment":this.g=8;break;case "text":this.g=3;break;case "processing-instruction":this.g=7;break;case "node":break;default:throw Error("Unexpected argument");}}function Ja(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}x.prototype.a=function(a){return null===this.g||this.g==a.nodeType};x.prototype.b=function(){return this.c};
x.prototype.toString=function(){var a="Kind Test: "+this.c;null===this.f||(a+=y(this.f));return a};function Ka(a,b){this.j=a.toLowerCase();a="*"==this.j?"*":"http://www.w3.org/1999/xhtml";this.f=b?b.toLowerCase():a}Ka.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=l(a.localName)?a.localName:a.nodeName;return"*"!=this.j&&this.j!=b.toLowerCase()?!1:"*"==this.f?!0:this.f==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Ka.prototype.b=function(){return this.j};
Ka.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.f?"":this.f+":")+this.j};function La(a){switch(a.nodeType){case 1:return ja(Ma,a);case 9:return La(a.documentElement);case 11:case 10:case 6:case 12:return Na;default:return a.parentNode?La(a.parentNode):Na}}function Na(){return null}function Ma(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Ma(a.parentNode,b):null};function Oa(a,b){return(new RegExp(a)).test(b)}function Qa(a,b){return(new RegExp(a,"i")).test(b)}function Ra(a){a=a.replace(/([.^$+(){}\[\]\\|])/g,"\\$1");a=a.replace(/\?/g,"(.|[\r\n])");return a=a.replace(/\*/g,"(.|[\r\n])*")}var Sa={exact:function(a,b){return-1!=b.indexOf(a)},glob:function(a,b){return(new RegExp("^"+Ra(a)+"$")).test(b)},globcontains:function(a,b){return(new RegExp(Ra(a))).test(b)},regex:Oa,regexi:Qa,regexpi:Qa,regexp:Oa};function Ta(a,b){if(m(a))return m(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function z(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function Ua(a,b){for(var c=a.length,d=[],e=0,f=m(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d}
function Va(a,b){for(var c=a.length,d=Array(c),e=m(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d}function Wa(a,b,c){var d=c;z(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}function Xa(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function Ya(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}
function Za(a,b){a:{for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:m(a)?a.charAt(b):a[b]}function $a(a){return Array.prototype.concat.apply([],arguments)}function ab(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function bb(){return w("iPhone")&&!w("iPod")&&!w("iPad")};var cb="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),db=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,eb=/^#(?:[0-9a-f]{3}){1,2}$/i,fb=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,gb=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;var hb={s:function(a,b){if(""===a)throw new r(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},u:function(a,b){if(""===a)throw new r(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};function ib(){return(w("Chrome")||w("CriOS"))&&!w("Edge")};function jb(a,b){this.x=l(a)?a:0;this.y=l(b)?b:0}jb.prototype.toString=function(){return"("+this.x+", "+this.y+")"};jb.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};jb.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};jb.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};jb.prototype.scale=function(a,b){b=ba(b)?b:a;this.x*=a;this.y*=b;return this};var kb=w("Opera"),A=w("Trident")||w("MSIE"),lb=w("Edge"),B=w("Gecko")&&!(-1!=Ga.toLowerCase().indexOf("webkit")&&!w("Edge"))&&!(w("Trident")||w("MSIE"))&&!w("Edge"),mb=-1!=Ga.toLowerCase().indexOf("webkit")&&!w("Edge");function nb(){var a=aa.document;return a?a.documentMode:void 0}var ob;
a:{var pb="",qb=function(){var a=Ga;if(B)return/rv\:([^\);]+)(\)|;)/.exec(a);if(lb)return/Edge\/([\d\.]+)/.exec(a);if(A)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(mb)return/WebKit\/(\S+)/.exec(a);if(kb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();qb&&(pb=qb?qb[1]:"");if(A){var rb=nb();if(null!=rb&&rb>parseFloat(pb)){ob=String(rb);break a}}ob=pb}var ta={};function sb(a){return sa(a,function(){return 0<=wa(ob,a)})}var tb;var ub=aa.document;
tb=ub&&A?nb()||("CSS1Compat"==ub.compatMode?parseInt(ob,10):5):void 0;function vb(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}vb.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};vb.prototype.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
vb.prototype.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};vb.prototype.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};vb.prototype.scale=function(a,b){b=ba(b)?b:a;this.left*=a;this.right*=a;this.top*=b;this.bottom*=b;return this};var wb=w("Firefox"),xb=bb()||w("iPod"),yb=w("iPad"),zb=w("Android")&&!(ib()||w("Firefox")||w("Opera")||w("Silk")),Ab=ib(),Bb=w("Safari")&&!(ib()||w("Coast")||w("Opera")||w("Edge")||w("Silk")||w("Android"))&&!(bb()||w("iPad")||w("iPod"));var Cb=A&&!(9<=Number(tb)),Db=A&&!(8<=Number(tb));function D(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}D.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};D.prototype.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
D.prototype.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};D.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};D.prototype.scale=function(a,b){b=ba(b)?b:a;this.left*=a;this.width*=a;this.top*=b;this.height*=b;return this};function Eb(a){return(a=a.exec(Ga))?a[1]:""}var Fb=function(){if(wb)return Eb(/Firefox\/([0-9.]+)/);if(A||lb||kb)return ob;if(Ab)return bb()||w("iPad")||w("iPod")?Eb(/CriOS\/([0-9.]+)/):Eb(/Chrome\/([0-9.]+)/);if(Bb&&!(bb()||w("iPad")||w("iPod")))return Eb(/Version\/([0-9.]+)/);if(xb||yb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Ga);if(a)return a[1]+"."+a[2]}else if(zb)return(a=Eb(/Android\s+([0-9.]+)/))?a:Eb(/Version\/([0-9.]+)/);return""}();function Gb(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Hb(a,b){var c=Db&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Gb(b,a,b.nodeName,c)};var Ib={},Jb,Kb;function Lb(a){return Mb?Jb(a):A?0<=wa(tb,a):sb(a)}function Nb(a){return Mb?Kb(a):zb?0<=wa(Ob,a):0<=wa(Fb,a)}
var Mb=function(){if(!B)return!1;var a=aa.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;Jb=function(a){return 0<=c.compare(d,""+a)};Kb=function(a){return 0<=c.compare(e,""+a)};return!0}(),Pb=yb||xb,Qb;
if(zb){var Rb=/Android\s+([0-9\.]+)/.exec(Ga);Qb=Rb?Rb[1]:"0"}else Qb="0";var Ob=Qb,Sb=A&&!(8<=Number(tb)),Tb=A&&!(9<=Number(tb));zb&&Nb(2.3);zb&&Nb(4);Bb&&Nb(6);function E(a){return a?new Ub(F(a)):qa||(qa=new Ub)}
function Vb(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){d=a.getElementsByClassName(c);if(e){a={};for(var f=b=0,g;g=d[f];f++)e==g.nodeName&&(a[b++]=g);a.length=b;return a}return d}d=a.getElementsByTagName(e||"*");if(c){a={};for(f=b=0;g=d[f];f++){var e=g.className,h;if(h="function"==typeof e.split)h=0<=Ta(e.split(/\s+/),c);h&&(a[b++]=g)}a.length=b;return a}return d}
function Wb(a){var b=Xb(a);a=a.parentWindow||a.defaultView;return A&&sb("10")&&a.pageYOffset!=b.scrollTop?new jb(b.scrollLeft,b.scrollTop):new jb(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}function Xb(a){return a.scrollingElement?a.scrollingElement:mb||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement}function Yb(a){return a?a.parentWindow||a.defaultView:window}function Zb(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}
function $b(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function ac(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(A&&!(9<=Number(tb))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?bc(a,b):!c&&$b(e,b)?-1*cc(a,b):!d&&$b(f,a)?cc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=F(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(aa.Range.START_TO_END,a)}function cc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return bc(b,a)}function bc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function F(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var dc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},ec={IMG:" ",BR:"\n"};
function fc(a,b,c){if(!(a.nodeName in dc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in ec)b.push(ec[a.nodeName]);else for(a=a.firstChild;a;)fc(a,b,c),a=a.nextSibling}function gc(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function Ub(a){this.a=a||aa.document||document}Ub.prototype.getElementsByTagName=function(a,b){return(b||this.a).getElementsByTagName(String(a))};
function hc(a,b,c,d){return Vb(a.a,b,c,d)};function G(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(Cb&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),Cb&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function ic(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}Db&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function jc(a,b,c,d,e){return(Cb?kc:lc).call(null,a,b,m(c)?c:null,m(d)?d:null,e||new H)}
function kc(a,b,c,d,e){if(a instanceof Ka||8==a.g||c&&null===a.g){var f=b.all;if(!f)return e;var g=mc(a);if("*"!=g&&(f=b.getElementsByTagName(g),!f))return e;if(c){var h=[];for(a=0;b=f[a++];)ic(b,c,d)&&h.push(b);f=h}for(a=0;b=f[a++];)"*"==g&&"!"==b.tagName||I(e,b);return e}nc(a,b,c,d,e);return e}
function lc(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!A?(b=b.getElementsByName(d),z(b,function(b){a.a(b)&&I(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),z(b,function(b){b.className==d&&a.a(b)&&I(e,b)})):a instanceof x?nc(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.b()),z(b,function(a){ic(a,c,d)&&I(e,a)}));return e}
function oc(a,b,c,d,e){var f;if((a instanceof Ka||8==a.g||c&&null===a.g)&&(f=b.childNodes)){var g=mc(a);if("*"!=g&&(f=Ua(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=Ua(f,function(a){return ic(a,c,d)}));z(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||I(e,a)});return e}return pc(a,b,c,d,e)}function pc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)ic(b,c,d)&&a.a(b)&&I(e,b);return e}
function nc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)ic(b,c,d)&&a.a(b)&&I(e,b),nc(a,b,c,d,e)}function mc(a){if(a instanceof x){if(8==a.g)return"!";if(null===a.g)return"*"}return a.b()};function qc(a,b){b=b.toLowerCase();return"style"==b?rc(a.style.cssText):Sb&&"value"==b&&J(a,"INPUT")?a.value:Tb&&!0===a[b]?String(a.getAttribute(b)):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var sc=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function rc(a){var b=[];z(a.split(sc),function(a){var c=a.indexOf(":");0<c&&(a=[a.slice(0,c),a.slice(c+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function tc(a,b){Sb&&"value"==b&&J(a,"OPTION")&&null===qc(a,"value")?(b=[],fc(a,b,!1),a=b.join("")):a=a[b];return a}function J(a,b){b&&"string"!==typeof b&&(b=b.toString());return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};mb||B&&Lb(3.5)||A&&Lb(8);var uc={B:function(a){return!(!a.querySelectorAll||!a.querySelector)},s:function(a,b){if(!a)throw new r(32,"No class name specified");a=va(a);if(-1!==a.indexOf(" "))throw new r(32,"Compound class names not permitted");if(uc.B(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new r(32,"An invalid or illegal class name was specified");}a=hc(E(b),"*",a,b);return a.length?a[0]:null},u:function(a,b){if(!a)throw new r(32,"No class name specified");a=va(a);if(-1!==a.indexOf(" "))throw new r(32,
"Compound class names not permitted");if(uc.B(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new r(32,"An invalid or illegal class name was specified");}return hc(E(b),"*",a,b)}};var vc={s:function(a,b){if(!ea(b.querySelector)&&A&&Lb(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new r(32,"No selector specified");a=va(a);try{var c=b.querySelector(a)}catch(d){throw new r(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},u:function(a,b){if(!ea(b.querySelectorAll)&&A&&Lb(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new r(32,"No selector specified");a=va(a);try{return b.querySelectorAll(a)}catch(c){throw new r(32,
"An invalid or illegal selector was specified");}}};function wc(a,b){var c=F(a);return c.defaultView&&c.defaultView.getComputedStyle&&(a=c.defaultView.getComputedStyle(a,null))?a[b]||a.getPropertyValue(b)||"":""}function xc(a){a=a?F(a):document;return!A||9<=Number(tb)||"CSS1Compat"==E(a).a.compatMode?a.documentElement:a.body}
function yc(a){try{var b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}A&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}function zc(a){var b=a.offsetWidth,c=a.offsetHeight,d=mb&&!b&&!c;return l(b)&&!d||!a.getBoundingClientRect?new ra(b,c):(a=yc(a),new ra(a.right-a.left,a.bottom-a.top))};function H(){this.b=this.a=null;this.m=0}function Ac(a){this.node=a;this.a=this.b=null}function Bc(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;){e=c.node;var g=b.node;e==g||e instanceof Gb&&g instanceof Gb&&e.a==g.a?(e=c,c=c.a,b=b.a):0<ac(c.node,b.node)?(e=b,b=b.a):(e=c,c=c.a);(e.b=d)?d.a=e:a.a=e;d=e;f++}for(e=c||b;e;)e.b=d,d=d.a=e,f++,e=e.a;a.b=d;a.m=f;return a}function Cc(a,b){b=new Ac(b);b.a=a.a;a.b?a.a.b=b:a.a=a.b=b;a.a=b;a.m++}
function I(a,b){b=new Ac(b);b.b=a.b;a.a?a.b.a=b:a.a=a.b=b;a.b=b;a.m++}function Dc(a){return(a=a.a)?a.node:null}H.prototype.f=function(){var a=Dc(this);return a?G(a):""};function Ec(a,b){return new Fc(a,!!b)}function Fc(a,b){this.f=a;this.b=(this.w=b)?a.b:a.a;this.a=null}function K(a){var b=a.b;if(b){var c=a.a=b;a.b=a.w?b.b:b.a;return c.node}return null};var Gc=!(A&&!Lb(10)),Hc=zb?!Nb(4):!Pb,Ic=A&&la.navigator.msPointerEnabled;function L(a,b,c){this.g=a;this.a=b;this.b=c}L.prototype.create=function(a){a=F(a);Tb&&a.createEventObject?a=a.createEventObject():(a=a.createEvent("HTMLEvents"),a.initEvent(this.g,this.a,this.b));return a};L.prototype.toString=function(){return this.g};function M(a,b,c){L.call(this,a,b,c)}q(M,L);
M.prototype.create=function(a,b){if(!B&&this==Jc)throw new r(9,"Browser does not support a mouse pixel scroll event.");var c=F(a);if(Tb){var d=c.createEventObject();d.altKey=b.altKey;d.ctrlKey=b.ctrlKey;d.metaKey=b.metaKey;d.shiftKey=b.shiftKey;d.button=b.button;d.clientX=b.clientX;d.clientY=b.clientY;c=function(a,b){Object.defineProperty(d,a,{get:function(){return b}})};if(this==Kc||this==Lc)if(Object.defineProperty){var e=this==Kc;c("fromElement",e?a:b.relatedTarget);c("toElement",e?b.relatedTarget:
a)}else d.relatedTarget=b.relatedTarget;this==Mc&&(Object.defineProperty?c("wheelDelta",b.wheelDelta):d.detail=b.wheelDelta)}else{e=Yb(c);d=c.createEvent("MouseEvents");var f=1;this==Mc&&(B||(d.wheelDelta=b.wheelDelta),B&&(f=b.wheelDelta/-40));B&&this==Jc&&(f=b.wheelDelta);d.initMouseEvent(this.g,this.a,this.b,e,f,b.clientX,b.clientY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);if(A&&!d.pageX&&!d.pageY&&Object.defineProperty){a=Xb(E(a).a);var c=xc(c),g=b.clientX+
a.scrollLeft-c.clientLeft,h=b.clientY+a.scrollTop-c.clientTop;Object.defineProperty(d,"pageX",{get:function(){return g}});Object.defineProperty(d,"pageY",{get:function(){return h}})}}return d};function Nc(a,b,c){L.call(this,a,b,c)}q(Nc,L);
Nc.prototype.create=function(a,b){var c=F(a);if(B){a=Yb(c);var d=b.charCode?0:b.keyCode,c=c.createEvent("KeyboardEvent");c.initKeyEvent(this.g,this.a,this.b,a,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,d,b.charCode);this.g==Oc&&b.preventDefault&&c.preventDefault()}else if(Tb?c=c.createEventObject():(c=c.createEvent("Events"),c.initEvent(this.g,this.a,this.b)),c.altKey=b.altKey,c.ctrlKey=b.ctrlKey,c.metaKey=b.metaKey,c.shiftKey=b.shiftKey,c.keyCode=b.charCode||b.keyCode,mb||lb)c.charCode=this==Oc?c.keyCode:
0;return c};function Pc(a,b,c){L.call(this,a,b,c)}q(Pc,L);
Pc.prototype.create=function(a,b){function c(b){b=Va(b,function(b){return g.createTouch(h,a,b.identifier,b.pageX,b.pageY,b.screenX,b.screenY)});return g.createTouchList.apply(g,b)}function d(b){var c=Va(b,function(b){return{identifier:b.identifier,screenX:b.screenX,screenY:b.screenY,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,target:a}});c.item=function(a){return c[a]};return c}function e(b){return Va(b,function(b){return new Touch({identifier:b.identifier,screenX:b.screenX,screenY:b.screenY,
clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,target:a})})}function f(a,b){switch(a){case 1:return d(b);case 2:return c(b);case 3:return e(b)}return null}if(!Gc)throw new r(9,"Browser does not support firing touch events.");var g=F(a),h=Yb(g);if(Hc)var k=1;else if(TouchEvent.prototype.initTouchEvent)k=2;else if(TouchEvent&&0<TouchEvent.length)k=3;else throw new r(9,"Not able to create touch events in this browser");var p=f(k,b.changedTouches),n=b.touches==b.changedTouches?p:f(k,
b.touches),C=b.targetTouches==b.changedTouches?p:f(k,b.targetTouches);if(1==k)k=g.createEvent("MouseEvents"),k.initMouseEvent(this.g,this.a,this.b,h,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,b.relatedTarget),k.touches=n,k.targetTouches=C,k.changedTouches=p,k.scale=b.scale,k.rotation=b.rotation;else if(2==k)k=g.createEvent("TouchEvent"),0==k.initTouchEvent.length?k.initTouchEvent(n,C,p,this.g,h,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey):k.initTouchEvent(this.g,
this.a,this.b,h,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,n,C,p,b.scale,b.rotation),k.relatedTarget=b.relatedTarget;else if(3==k)k=new TouchEvent(this.g,{touches:n,targetTouches:C,changedTouches:p,bubbles:this.a,cancelable:this.b,ctrlKey:b.ctrlKey,shiftKey:b.shiftKey,altKey:b.altKey,metaKey:b.metaKey});else throw new r(9,"Illegal TouchEventStrategy_ value (this is a bug)");return k};function Qc(a,b,c){L.call(this,a,b,c)}q(Qc,L);
Qc.prototype.create=function(a,b){if(!Ic)throw new r(9,"Browser does not support MSGesture events.");var c=F(a);a=Yb(c);c=c.createEvent("MSGestureEvent");c.initGestureEvent(this.g,this.a,this.b,a,1,0,0,b.clientX,b.clientY,0,0,b.translationX,b.translationY,b.scale,b.expansion,b.rotation,b.velocityX,b.velocityY,b.velocityExpansion,b.velocityAngular,(new Date).getTime(),b.relatedTarget);return c};function N(a,b,c){L.call(this,a,b,c)}q(N,L);
N.prototype.create=function(a,b){if(!Ic)throw new r(9,"Browser does not support MSPointer events.");var c=F(a);a=Yb(c);c=c.createEvent("MSPointerEvent");c.initPointerEvent(this.g,this.a,this.b,a,0,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget,0,0,b.width,b.height,b.pressure,b.rotation,b.tiltX,b.tiltY,b.pointerId,b.pointerType,0,b.isPrimary);return c};
var Kc=new M("mouseout",!0,!0),Lc=new M("mouseover",!0,!0),Mc=new M(B?"DOMMouseScroll":"mousewheel",!0,!0),Jc=new M("MozMousePixelScroll",!0,!0),Oc=new Nc("keypress",!0,!0),Rc={ca:new L("blur",!1,!1),da:new L("change",!0,!1),ha:new L("focus",!1,!1),ia:new L("focusin",!0,!1),ja:new L("focusout",!0,!1),la:new L("input",!0,!1),Ka:new L("orientationchange",!1,!1),La:new L("propertychange",!1,!1),Ma:new L("select",!0,!1),Na:new L("submit",!0,!0),Oa:new L("textInput",!0,!0),ea:new M("click",!0,!0),fa:new M("contextmenu",
!0,!0),ga:new M("dblclick",!0,!0),pa:new M("mousedown",!0,!0),qa:new M("mousemove",!0,!1),ra:Kc,sa:Lc,ua:new M("mouseup",!0,!0),va:Mc,ta:Jc,ma:new Nc("keydown",!0,!0),na:Oc,oa:new Nc("keyup",!0,!0),Pa:new Pc("touchend",!0,!0),Qa:new Pc("touchmove",!0,!0),Ra:new Pc("touchstart",!0,!0),wa:new Qc("MSGestureChange",!0,!0),xa:new Qc("MSGestureEnd",!0,!0),ya:new Qc("MSGestureHold",!0,!0),za:new Qc("MSGestureStart",!0,!0),Aa:new Qc("MSGestureTap",!0,!0),Ca:new Qc("MSInertiaStart",!0,!0),Ba:new N("MSGotPointerCapture",
!0,!1),Da:new N("MSLostPointerCapture",!0,!1),Ea:new N("MSPointerCancel",!0,!0),Fa:new N("MSPointerDown",!0,!0),Ga:new N("MSPointerMove",!0,!0),Ia:new N("MSPointerOver",!0,!0),Ha:new N("MSPointerOut",!0,!0),Ja:new N("MSPointerUp",!0,!0)};function O(a){this.l=a;this.b=this.h=!1;this.f=null}function y(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Sc(a,b){a.h=b}function Tc(a,b){a.b=b}function P(a,b){a=a.a(b);return a instanceof H?+a.f():+a}function Q(a,b){a=a.a(b);return a instanceof H?a.f():""+a}function Uc(a,b){a=a.a(b);return a instanceof H?!!a.m:!!a};var Vc="function"===typeof ShadowRoot;
function Wc(a,b){if(a.style&&("hidden"==a.style.visibility||"none"==a.style.display))return"";if(3==a.nodeType){var c=a.data;b||(c=c.replace(/\n|\r|\t/g," "));return c.replace(/&nbsp/," ")}if(Vc&&1==a.nodeType&&null!==a.shadowRoot)return Wc(a.shadowRoot,b);if((1==a.nodeType||11==a.nodeType)&&"SCRIPT"!=a.nodeName&&"STYLE"!=a.nodeName){var d=b||"PRE"==a.tagName;c="";for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes.item(e);if(f)if(!Vc||"CONTENT"!=f.nodeName&&"SLOT"!=f.nodeName)c+=Wc(f,d);else for(var f=
"CONTENT"==f.nodeName?f.getDistributedNodes():f.assignedNodes(),g=0;g<f.length;g++){var h=f[g];h&&(c+=Wc(h,b))}}if("P"==a.tagName||"BR"==a.tagName||"HR"==a.tagName||"DIV"==a.tagName)c+="\n";c=c.replace(/&nbsp/," ");Ib.ka&&Nb(9)&&(c=c.replace(/&#100;/," "));return c}return""};function Xc(a,b,c){O.call(this,a.l);this.c=a;this.i=b;this.v=c;this.h=b.h||c.h;this.b=b.b||c.b;this.c==Yc&&(c.b||c.h||4==c.l||0==c.l||!b.f?b.b||b.h||4==b.l||0==b.l||!c.f||(this.f={name:c.f.name,A:b}):this.f={name:b.f.name,A:c})}q(Xc,O);
function Zc(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof H&&c instanceof H){b=Ec(b);for(d=K(b);d;d=K(b))for(e=Ec(c),f=K(e);f;f=K(e))if(a(G(d),G(f)))return!0;return!1}if(b instanceof H||c instanceof H){b instanceof H?(e=b,d=c):(e=c,d=b);f=Ec(e);for(var g=typeof d,h=K(f);h;h=K(f)){switch(g){case "number":h=+G(h);break;case "boolean":h=!!G(h);break;case "string":h=G(h);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(h,d)||e==c&&a(d,h))return!0}return!1}return e?
"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Xc.prototype.a=function(a){return this.c.o(this.i,this.v,a)};Xc.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+y(this.i);return a+=y(this.v)};function $c(a,b,c,d){this.$=a;this.O=b;this.l=c;this.o=d}$c.prototype.toString=function(){return this.$};var ad={};
function R(a,b,c,d){if(ad.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new $c(a,b,c,d);return ad[a.toString()]=a}R("div",6,1,function(a,b,c){return P(a,c)/P(b,c)});R("mod",6,1,function(a,b,c){return P(a,c)%P(b,c)});R("*",6,1,function(a,b,c){return P(a,c)*P(b,c)});R("+",5,1,function(a,b,c){return P(a,c)+P(b,c)});R("-",5,1,function(a,b,c){return P(a,c)-P(b,c)});R("<",4,2,function(a,b,c){return Zc(function(a,b){return a<b},a,b,c)});
R(">",4,2,function(a,b,c){return Zc(function(a,b){return a>b},a,b,c)});R("<=",4,2,function(a,b,c){return Zc(function(a,b){return a<=b},a,b,c)});R(">=",4,2,function(a,b,c){return Zc(function(a,b){return a>=b},a,b,c)});var Yc=R("=",3,2,function(a,b,c){return Zc(function(a,b){return a==b},a,b,c,!0)});R("!=",3,2,function(a,b,c){return Zc(function(a,b){return a!=b},a,b,c,!0)});R("and",2,2,function(a,b,c){return Uc(a,c)&&Uc(b,c)});R("or",1,2,function(a,b,c){return Uc(a,c)||Uc(b,c)});function bd(a,b){if(b.a.length&&4!=a.l)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");O.call(this,a.l);this.c=a;this.i=b;this.h=a.h;this.b=a.b}q(bd,O);bd.prototype.a=function(a){a=this.c.a(a);return cd(this.i,a)};bd.prototype.toString=function(){var a="Filter:"+y(this.c);return a+=y(this.i)};function dd(a,b){if(b.length<a.M)throw Error("Function "+a.j+" expects at least"+a.M+" arguments, "+b.length+" given");if(null!==a.F&&b.length>a.F)throw Error("Function "+a.j+" expects at most "+a.F+" arguments, "+b.length+" given");a.Z&&z(b,function(b,d){if(4!=b.l)throw Error("Argument "+d+" to function "+a.j+" is not of type Nodeset: "+b);});O.call(this,a.l);this.C=a;this.c=b;Sc(this,a.h||Xa(b,function(a){return a.h}));Tc(this,a.Y&&!b.length||a.X&&!!b.length||Xa(b,function(a){return a.b}))}
q(dd,O);dd.prototype.a=function(a){return this.C.o.apply(null,$a(a,this.c))};dd.prototype.toString=function(){var a="Function: "+this.C;if(this.c.length)var b=Wa(this.c,function(a,b){return a+y(b)},"Arguments:"),a=a+y(b);return a};function ed(a,b,c,d,e,f,g,h,k){this.j=a;this.l=b;this.h=c;this.Y=d;this.X=e;this.o=f;this.M=g;this.F=l(h)?h:g;this.Z=!!k}ed.prototype.toString=function(){return this.j};var fd={};
function S(a,b,c,d,e,f,g,h){if(fd.hasOwnProperty(a))throw Error("Function already created: "+a+".");fd[a]=new ed(a,b,c,d,!1,e,f,g,h)}S("boolean",2,!1,!1,function(a,b){return Uc(b,a)},1);S("ceiling",1,!1,!1,function(a,b){return Math.ceil(P(b,a))},1);S("concat",3,!1,!1,function(a,b){return Wa(ab(arguments,1),function(b,d){return b+Q(d,a)},"")},2,null);S("contains",2,!1,!1,function(a,b,c){b=Q(b,a);a=Q(c,a);return-1!=b.indexOf(a)},2);S("count",1,!1,!1,function(a,b){return b.a(a).m},1,1,!0);
S("false",2,!1,!1,function(){return!1},0);S("floor",1,!1,!1,function(a,b){return Math.floor(P(b,a))},1);S("id",4,!1,!1,function(a,b){function c(a){if(Cb){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return Za(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument;a=Q(b,a).split(/\s+/);var f=[];z(a,function(a){a=c(a);!a||0<=Ta(f,a)||f.push(a)});f.sort(ac);var g=new H;z(f,function(a){I(g,a)});return g},1);
S("lang",2,!1,!1,function(){return!1},1);S("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);S("local-name",3,!1,!0,function(a,b){return(a=b?Dc(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);S("name",3,!1,!0,function(a,b){return(a=b?Dc(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);S("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
S("normalize-space",3,!1,!0,function(a,b){return(b?Q(b,a):G(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);S("not",2,!1,!1,function(a,b){return!Uc(b,a)},1);S("number",1,!1,!0,function(a,b){return b?P(b,a):+G(a.a)},0,1);S("position",1,!0,!1,function(a){return a.b},0);S("round",1,!1,!1,function(a,b){return Math.round(P(b,a))},1);S("starts-with",2,!1,!1,function(a,b,c){b=Q(b,a);a=Q(c,a);return!b.lastIndexOf(a,0)},2);S("string",3,!1,!0,function(a,b){return b?Q(b,a):G(a.a)},0,1);
S("string-length",1,!1,!0,function(a,b){return(b?Q(b,a):G(a.a)).length},0,1);S("substring",3,!1,!1,function(a,b,c,d){c=P(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?P(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=Q(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);S("substring-after",3,!1,!1,function(a,b,c){b=Q(b,a);a=Q(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
S("substring-before",3,!1,!1,function(a,b,c){b=Q(b,a);a=Q(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);S("sum",1,!1,!1,function(a,b){a=Ec(b.a(a));b=0;for(var c=K(a);c;c=K(a))b+=+G(c);return b},1,1,!0);S("translate",3,!1,!1,function(a,b,c,d){b=Q(b,a);c=Q(c,a);var e=Q(d,a);d={};for(var f=0;f<c.length;f++)a=c.charAt(f),a in d||(d[a]=e.charAt(f));c="";for(f=0;f<b.length;f++)a=b.charAt(f),c+=a in d?d[a]:a;return c},3);S("true",2,!1,!1,function(){return!0},0);function gd(a){O.call(this,3);this.c=a.substring(1,a.length-1)}q(gd,O);gd.prototype.a=function(){return this.c};gd.prototype.toString=function(){return"Literal: "+this.c};function hd(a){O.call(this,1);this.c=a}q(hd,O);hd.prototype.a=function(){return this.c};hd.prototype.toString=function(){return"Number: "+this.c};function id(a,b){O.call(this,a.l);this.i=a;this.c=b;this.h=a.h;this.b=a.b;1==this.c.length&&(a=this.c[0],a.D||a.c!=jd||(a=a.v,"*"!=a.b()&&(this.f={name:a.b(),A:null})))}q(id,O);function kd(){O.call(this,4)}q(kd,O);kd.prototype.a=function(a){var b=new H;a=a.a;9==a.nodeType?I(b,a):I(b,a.ownerDocument);return b};kd.prototype.toString=function(){return"Root Helper Expression"};function ld(){O.call(this,4)}q(ld,O);ld.prototype.a=function(a){var b=new H;I(b,a.a);return b};ld.prototype.toString=function(){return"Context Helper Expression"};
function md(a){return"/"==a||"//"==a}id.prototype.a=function(a){var b=this.i.a(a);if(!(b instanceof H))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.m;c++){var e=a[c],f=Ec(b,e.c.w);if(e.h||e.c!=nd)if(e.h||e.c!=od){var g=K(f);for(b=e.a(new za(g));g=K(f);)g=e.a(new za(g)),b=Bc(b,g)}else g=K(f),b=e.a(new za(g));else{for(g=K(f);(b=K(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new za(g))}}return b};
id.prototype.toString=function(){var a="Path Expression:"+y(this.i);if(this.c.length){var b=Wa(this.c,function(a,b){return a+y(b)},"Steps:");a+=y(b)}return a};function pd(a,b){this.a=a;this.w=!!b}
function cd(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=Ec(b),f=b.m,g,h=0;g=K(e);h++){var k=a.w?f-h:h+1;g=d.a(new za(g,k,f));if("number"==typeof g)k=k==g;else if("string"==typeof g||"boolean"==typeof g)k=!!g;else if(g instanceof H)k=0<g.m;else throw Error("Predicate.evaluate returned an unexpected type.");if(!k){k=e;g=k.f;var p=k.a;if(!p)throw Error("Next must be called at least once before remove.");var n=p.b,p=p.a;n?n.a=p:g.a=p;p?p.b=n:g.b=n;g.m--;k.a=null}}return b}
pd.prototype.toString=function(){return Wa(this.a,function(a,b){return a+y(b)},"Predicates:")};function qd(a){O.call(this,1);this.c=a;this.h=a.h;this.b=a.b}q(qd,O);qd.prototype.a=function(a){return-P(this.c,a)};qd.prototype.toString=function(){return"Unary Expression: -"+y(this.c)};function rd(a){O.call(this,4);this.c=a;Sc(this,Xa(this.c,function(a){return a.h}));Tc(this,Xa(this.c,function(a){return a.b}))}q(rd,O);rd.prototype.a=function(a){var b=new H;z(this.c,function(c){c=c.a(a);if(!(c instanceof H))throw Error("Path expression must evaluate to NodeSet.");b=Bc(b,c)});return b};rd.prototype.toString=function(){return Wa(this.c,function(a,b){return a+y(b)},"Union Expression:")};function sd(a,b,c,d){O.call(this,4);this.c=a;this.v=b;this.i=c||new pd([]);this.D=!!d;b=this.i;b=0<b.a.length?b.a[0].f:null;a.ba&&b&&(a=b.name,a=Cb?a.toLowerCase():a,this.f={name:a,A:b.A});a:{a=this.i;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.h||1==c.l||0==c.l){a=!0;break a}a=!1}this.h=a}q(sd,O);
sd.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.A?Q(c.A,a):null,f=1);if(this.D)if(this.h||this.c!=td)if(b=Ec((new sd(ud,new x("node"))).a(a)),c=K(b))for(a=this.o(c,d,e,f);c=K(b);)a=Bc(a,this.o(c,d,e,f));else a=new H;else a=jc(this.v,b,d,e),a=cd(this.i,a,f);else a=this.o(a.a,d,e,f);return a};sd.prototype.o=function(a,b,c,d){a=this.c.C(this.v,a,b,c);return a=cd(this.i,a,d)};
sd.prototype.toString=function(){var a="Step:"+y("Operator: "+(this.D?"//":"/"));this.c.j&&(a+=y("Axis: "+this.c));a+=y(this.v);if(this.i.a.length){var b=Wa(this.i.a,function(a,b){return a+y(b)},"Predicates:");a+=y(b)}return a};function vd(a,b,c,d){this.j=a;this.C=b;this.w=c;this.ba=d}vd.prototype.toString=function(){return this.j};var wd={};function T(a,b,c,d){if(wd.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new vd(a,b,c,!!d);return wd[a]=b}
T("ancestor",function(a,b){for(var c=new H;b=b.parentNode;)a.a(b)&&Cc(c,b);return c},!0);T("ancestor-or-self",function(a,b){var c=new H;do a.a(b)&&Cc(c,b);while(b=b.parentNode);return c},!0);
var jd=T("attribute",function(a,b){var c=new H,d=a.b();if("style"==d&&Cb&&b.style)return I(c,new Gb(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof x&&null===a.g||"*"==d)for(d=0;a=e[d];d++)Cb?a.nodeValue&&I(c,Hb(b,a)):I(c,a);else(a=e.getNamedItem(d))&&(Cb?a.nodeValue&&I(c,Hb(b,a)):I(c,a));return c},!1),td=T("child",function(a,b,c,d,e){return(Cb?oc:pc).call(null,a,b,m(c)?c:null,m(d)?d:null,e||new H)},!1,!0);T("descendant",jc,!1,!0);
var ud=T("descendant-or-self",function(a,b,c,d){var e=new H;ic(b,c,d)&&a.a(b)&&I(e,b);return jc(a,b,c,d,e)},!1,!0),nd=T("following",function(a,b,c,d){var e=new H;do for(var f=b;f=f.nextSibling;)ic(f,c,d)&&a.a(f)&&I(e,f),e=jc(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);T("following-sibling",function(a,b){for(var c=new H;b=b.nextSibling;)a.a(b)&&I(c,b);return c},!1);T("namespace",function(){return new H},!1);
var xd=T("parent",function(a,b){var c=new H;if(9==b.nodeType)return c;if(2==b.nodeType)return I(c,b.ownerElement),c;b=b.parentNode;a.a(b)&&I(c,b);return c},!1),od=T("preceding",function(a,b,c,d){var e=new H,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,h=f.length;g<h;g++){var k=[];for(b=f[g];b=b.previousSibling;)k.unshift(b);for(var p=0,n=k.length;p<n;p++)b=k[p],ic(b,c,d)&&a.a(b)&&I(e,b),e=jc(a,b,c,d,e)}return e},!0,!0);
T("preceding-sibling",function(a,b){for(var c=new H;b=b.previousSibling;)a.a(b)&&Cc(c,b);return c},!0);var yd=T("self",function(a,b){var c=new H;a.a(b)&&I(c,b);return c},!1);function zd(a,b){this.a=a;this.b=b}function Ad(a){for(var b,c=[];;){U(a,"Missing right hand side of binary expression.");b=Bd(a);var d=v(a.a);if(!d)break;var e=(d=ad[d]||null)&&d.O;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].O;)b=new Xc(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Xc(c.pop(),c.pop(),b);return b}function U(a,b){if(Ea(a.a))throw Error(b);}function Cd(a,b){a=v(a.a);if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function Dd(a){a=v(a.a);if(")"!=a)throw Error("Bad token: "+a);}function Ed(a){a=v(a.a);if(2>a.length)throw Error("Unclosed literal string");return new gd(a)}
function Fd(a){var b=[];if(md(u(a.a))){var c=v(a.a);var d=u(a.a);if("/"==c&&(Ea(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new kd;d=new kd;U(a,"Missing next location step.");c=Gd(a,c);b.push(c)}else{a:{c=u(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":v(a.a);c=Ad(a);U(a,'unclosed "("');Cd(a,")");break;case '"':case "'":c=Ed(a);break;default:if(isNaN(+c))if(!Ja(c)&&/(?![0-9])[\w]/.test(d)&&"("==u(a.a,1)){c=v(a.a);
c=fd[c]||null;v(a.a);for(d=[];")"!=u(a.a);){U(a,"Missing function argument list.");d.push(Ad(a));if(","!=u(a.a))break;v(a.a)}U(a,"Unclosed function argument list.");Dd(a);c=new dd(c,d)}else{c=null;break a}else c=new hd(+v(a.a))}"["==u(a.a)&&(d=new pd(Hd(a)),c=new bd(c,d))}if(c)if(md(u(a.a)))d=c;else return c;else c=Gd(a,"/"),d=new ld,b.push(c)}for(;md(u(a.a));)c=v(a.a),U(a,"Missing next location step."),c=Gd(a,c),b.push(c);return new id(d,b)}
function Gd(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==u(a.a)){var c=new sd(yd,new x("node"));v(a.a);return c}if(".."==u(a.a))return c=new sd(xd,new x("node")),v(a.a),c;if("@"==u(a.a)){var d=jd;v(a.a);U(a,"Missing attribute name")}else if("::"==u(a.a,1)){if(!/(?![0-9])[\w]/.test(u(a.a).charAt(0)))throw Error("Bad token: "+v(a.a));var e=v(a.a);d=wd[e]||null;if(!d)throw Error("No axis with name: "+e);v(a.a);U(a,"Missing node name")}else d=td;e=u(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==
u(a.a,1)){if(!Ja(e))throw Error("Invalid node type: "+e);e=v(a.a);if(!Ja(e))throw Error("Invalid type name: "+e);Cd(a,"(");U(a,"Bad nodetype");var f=u(a.a).charAt(0),g=null;if('"'==f||"'"==f)g=Ed(a);U(a,"Bad nodetype");Dd(a);e=new x(e,g)}else if(e=v(a.a),f=e.indexOf(":"),-1==f)e=new Ka(e);else{var g=e.substring(0,f);if("*"==g)var h="*";else if(h=a.b(g),!h)throw Error("Namespace prefix not declared: "+g);e=e.substr(f+1);e=new Ka(e,h)}else throw Error("Bad token: "+v(a.a));a=new pd(Hd(a),d.w);return c||
new sd(d,e,a,"//"==b)}function Hd(a){for(var b=[];"["==u(a.a);){v(a.a);U(a,"Missing predicate expression.");var c=Ad(a);b.push(c);U(a,"Unclosed predicate expression.");Cd(a,"]")}return b}function Bd(a){if("-"==u(a.a))return v(a.a),new qd(Bd(a));var b=Fd(a);if("|"!=u(a.a))a=b;else{for(b=[b];"|"==v(a.a);)U(a,"Missing next union location path."),b.push(Fd(a));a.a.a--;a=new rd(b)}return a};function Id(a,b){if(!a.length)throw Error("Empty XPath expression.");a=Ba(a);if(Ea(a))throw Error("Invalid XPath expression.");b?ea(b)||(b=ia(b.lookupNamespaceURI,b)):b=function(){return null};var c=Ad(new zd(a,b));if(!Ea(a))throw Error("Bad token: "+v(a));this.evaluate=function(a,b){a=c.a(new za(a));return new V(a,b)}}
function V(a,b){if(!b)if(a instanceof H)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof H))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof H?a.f():""+a;break;case 1:this.numberValue=a instanceof H?+a.f():+a;break;case 3:this.booleanValue=a instanceof H?0<a.m:!!a;break;case 4:case 5:case 6:case 7:var c=
Ec(a);var d=[];for(var e=K(c);e;e=K(c))d.push(e instanceof Gb?e.a:e);this.snapshotLength=a.m;this.invalidIteratorState=!1;break;case 8:case 9:a=Dc(a);this.singleNodeValue=a instanceof Gb?a.a:a;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=d.length||
0>a?null:d[a]}}V.ANY_TYPE=0;V.NUMBER_TYPE=1;V.STRING_TYPE=2;V.BOOLEAN_TYPE=3;V.UNORDERED_NODE_ITERATOR_TYPE=4;V.ORDERED_NODE_ITERATOR_TYPE=5;V.UNORDERED_NODE_SNAPSHOT_TYPE=6;V.ORDERED_NODE_SNAPSHOT_TYPE=7;V.ANY_UNORDERED_NODE_TYPE=8;V.FIRST_ORDERED_NODE_TYPE=9;function Jd(a){this.lookupNamespaceURI=La(a)}
function Kd(a,b){a=a||aa;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=V,c.evaluate=function(a,b,c,g){return(new Id(a,c)).evaluate(b,g)},c.createExpression=function(a,b){return new Id(a,b)},c.createNSResolver=function(a){return new Jd(a)}}ca("wgxpath.install",Kd);var X={};X.G=function(){var a={Va:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
X.o=function(a,b,c){var d=F(a);if(!d.documentElement)return null;(A||zb)&&Kd(Yb(d));try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):X.G;if(A&&!sb(7))return d.evaluate.call(d,b,a,e,c,null);if(!A||9<=Number(tb)){for(var f={},g=d.getElementsByTagName("*"),h=0;h<g.length;++h){var k=g[h],p=k.namespaceURI;if(p&&!f[p]){var n=k.lookupPrefix(p);if(!n)var C=p.match(".*/(\\w+)/?$"),n=C?C[1]:"xhtml";f[p]=n}}var W={},na;for(na in f)W[f[na]]=na;e=function(a){return W[a]||null}}try{return d.evaluate(b,
a,e,c,null)}catch(Pa){if("TypeError"===Pa.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):X.G,d.evaluate(b,a,e,c,null);throw Pa;}}catch(Pa){if(!B||"NS_ERROR_ILLEGAL_VALUE"!=Pa.name)throw new r(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+Pa);}};X.H=function(a,b){if(!a||1!=a.nodeType)throw new r(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
X.s=function(a,b){var c=function(){var c=X.o(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=F(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||X.H(c,a);return c};
X.u=function(a,b){var c=function(){var c=X.o(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=F(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();z(c,function(b){X.H(b,a)});return c};var Ld="function"===typeof ShadowRoot;function Md(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return J(a)?a:null}
function Y(a,b){b=ya(b);if("float"==b||"cssFloat"==b||"styleFloat"==b)b=Tb?"styleFloat":"cssFloat";a=wc(a,b)||Nd(a,b);if(null===a)a=null;else if(0<=Ta(cb,b)){b:{var c=a.match(fb);if(c){b=Number(c[1]);var d=Number(c[2]),e=Number(c[3]),c=Number(c[4]);if(0<=b&&255>=b&&0<=d&&255>=d&&0<=e&&255>=e&&0<=c&&1>=c){b=[b,d,e,c];break b}}b=null}if(!b)b:{if(e=a.match(gb))if(b=Number(e[1]),d=Number(e[2]),e=Number(e[3]),0<=b&&255>=b&&0<=d&&255>=d&&0<=e&&255>=e){b=[b,d,e,1];break b}b=null}if(!b)b:{b=a.toLowerCase();
d=oa[b.toLowerCase()];if(!d&&(d="#"==b.charAt(0)?b:"#"+b,4==d.length&&(d=d.replace(db,"#$1$1$2$2$3$3")),!eb.test(d))){b=null;break b}b=[parseInt(d.substr(1,2),16),parseInt(d.substr(3,2),16),parseInt(d.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}function Nd(a,b){var c=a.currentStyle||a.style,d=c[b];!l(d)&&ea(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?l(d)?d:null:(a=Md(a))?Nd(a,b):null}
function Od(a,b,c){function d(a){var b=Pd(a);return 0<b.height&&0<b.width?!0:J(a,"PATH")&&(0<b.height||0<b.width)?(a=Y(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=Y(a,"overflow")&&Xa(a.childNodes,function(a){return 3==a.nodeType||J(a)&&d(a)})}function e(a){return Qd(a)==Rd&&Ya(a.childNodes,function(a){return!J(a)||e(a)||!d(a)})}if(!J(a))throw Error("Argument to isShown must be of type Element");if(J(a,"BODY"))return!0;if(J(a,"OPTION")||J(a,"OPTGROUP"))return a=gc(a,function(a){return J(a,"SELECT")}),
!!a&&Od(a,!0,c);var f=Sd(a);if(f)return!!f.K&&0<f.rect.width&&0<f.rect.height&&Od(f.K,b,c);if(J(a,"INPUT")&&"hidden"==a.type.toLowerCase()||J(a,"NOSCRIPT"))return!1;f=Y(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||Td(a))&&d(a)?!e(a):!1}
function Ud(a){function b(a){if(J(a)&&"none"==Y(a,"display"))return!1;var c;(c=a.parentNode)&&c.shadowRoot&&void 0!==a.assignedSlot?c=a.assignedSlot?a.assignedSlot.parentNode:null:a.getDestinationInsertionPoints&&(a=a.getDestinationInsertionPoints(),0<a.length&&(c=a[a.length-1]));if(Ld&&c instanceof ShadowRoot){if(c.host.shadowRoot!==c)return!1;c=c.host}return!c||9!=c.nodeType&&11!=c.nodeType?c&&b(c):!0}return Od(a,!1,b)}var Rd="hidden";
function Qd(a){function b(a){function b(a){return a==g?!0:!Y(a,"display").lastIndexOf("inline",0)||"absolute"==c&&"static"==Y(a,"position")?!1:!0}var c=Y(a,"position");if("fixed"==c)return p=!0,a==g?null:g;for(a=Md(a);a&&!b(a);)a=Md(a);return a}function c(a){var b=a;if("visible"==k)if(a==g&&h)b=h;else if(a==h)return{x:"visible",y:"visible"};b={x:Y(b,"overflow-x"),y:Y(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){return a==g?Wb((new Ub(f)).a):
new jb(a.scrollLeft,a.scrollTop)}var e=Vd(a);var f=F(a),g=f.documentElement,h=f.body,k=Y(g,"overflow"),p;for(a=b(a);a;a=b(a)){var n=c(a);if("visible"!=n.x||"visible"!=n.y){var C=Pd(a);if(!C.width||!C.height)return Rd;var W=e.right<C.left,na=e.bottom<C.top;if(W&&"hidden"==n.x||na&&"hidden"==n.y)return Rd;if(W&&"visible"!=n.x||na&&"visible"!=n.y){W=d(a);na=e.bottom<C.top-W.y;if(e.right<C.left-W.x&&"visible"!=n.x||na&&"visible"!=n.x)return Rd;e=Qd(a);return e==Rd?Rd:"scroll"}W=e.left>=C.left+C.width;
C=e.top>=C.top+C.height;if(W&&"hidden"==n.x||C&&"hidden"==n.y)return Rd;if(W&&"visible"!=n.x||C&&"visible"!=n.y){if(p&&(n=d(a),e.left>=g.scrollWidth-n.x||e.right>=g.scrollHeight-n.y))return Rd;e=Qd(a);return e==Rd?Rd:"scroll"}}}return"none"}
function Pd(a){var b=Sd(a);if(b)return b.rect;if(J(a,"HTML"))return a=F(a),a=(Yb(a)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new ra(a.clientWidth,a.clientHeight),new D(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new D(0,0,0,0)}b=new D(c.left,c.top,c.right-c.left,c.bottom-c.top);A&&a.ownerDocument.body&&(a=F(a),b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Sd(a){var b=J(a,"MAP");if(!b&&!J(a,"AREA"))return null;var c=b?a:J(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=X.s('/descendant::*[@usemap = "#'+c.name+'"]',F(c)))&&(e=Pd(d),b||"default"==a.shape.toLowerCase()||(a=Wd(a),b=Math.min(Math.max(a.left,0),e.width),c=Math.min(Math.max(a.top,0),e.height),e=new D(b+e.left,c+e.top,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{K:d,rect:e||new D(0,0,0,0)}}
function Wd(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new D(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new D(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new D(b,c,d-b,e-c)}return new D(0,0,0,0)}function Vd(a){a=Pd(a);return new vb(a.top,a.left+a.width,a.top+a.height,a.left)}
function Xd(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function Yd(a){var b=[];Ld?Zd(a,b):$d(a,b);a=Va(b,Xd);return Xd(a.join("\n")).replace(/\xa0/g," ")}
function ae(a,b,c){if(J(a,"BR"))b.push("");else{var d=J(a,"TD"),e=Y(a,"display"),f=!d&&!(0<=Ta(be,e)),g=l(a.previousElementSibling)?a.previousElementSibling:Zb(a.previousSibling),g=g?Y(g,"display"):"",h=Y(a,"float")||Y(a,"cssFloat")||Y(a,"styleFloat");!f||"run-in"==g&&"none"==h||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var k=Ud(a),p=null,n=null;k&&(p=Y(a,"white-space"),n=Y(a,"text-transform"));z(a.childNodes,function(a){c(a,b,k,p,n)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||ua(a," ")||
(b[b.length-1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function $d(a,b){ae(a,b,function(a,b,e,f,g){3==a.nodeType&&e?ce(a,b,f,g):J(a)&&$d(a,b)})}var be="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function ce(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";ua(c," ")&&!a.lastIndexOf(" ",0)&&(a=a.substr(1));b.push(c+a)}
function Td(a){if(Tb){if("relative"==Y(a,"position"))return 1;a=Y(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return de(a)}function de(a){var b=1,c=Y(a,"opacity");c&&(b=Number(c));(a=Md(a))&&(b*=de(a));return b}
function ee(a,b,c,d,e){var f;if(3==a.nodeType&&c)ce(a,b,d,e);else if(J(a))if(J(a,"CONTENT")||J(a,"SLOT")){for(f=a;f.parentNode;)f=f.parentNode;f instanceof ShadowRoot?(a=J(a,"CONTENT")?a.getDistributedNodes():a.assignedNodes(),z(a,function(a){ee(a,b,c,d,e)})):Zd(a,b)}else if(J(a,"SHADOW")){for(f=a;f.parentNode;)f=f.parentNode;if(f instanceof ShadowRoot&&(a=f))for(a=a.olderShadowRoot;a;)z(a.childNodes,function(a){ee(a,b,c,d,e)}),a=a.olderShadowRoot}else Zd(a,b)}
function Zd(a,b){a.shadowRoot&&z(a.shadowRoot.childNodes,function(a){ee(a,b,!0,null,null)});ae(a,b,function(a,b,e,f,g){var c=null;1==a.nodeType?c=a:3==a.nodeType&&(c=a);c&&(c.assignedSlot||c.getDestinationInsertionPoints&&0<c.getDestinationInsertionPoints().length)||ee(a,b,e,f,g)})};var fe={B:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},s:function(a,b){var c=E(b),d=m(a)?c.a.getElementById(a):a;return d?qc(d,"id")==a&&b!=d&&$b(b,d)?d:Za(hc(c,"*"),function(c){return qc(c,"id")==a&&b!=c&&$b(b,c)}):null},u:function(a,b){if(!a)return[];if(fe.B(b,a))try{return b.querySelectorAll("#"+fe.U(a))}catch(c){return[]}b=hc(E(b),"*",null,b);return Ua(b,function(b){return qc(b,"id")==a})},U:function(a){return a.replace(/([\s'"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var ge={},he={};ge.P=function(a,b,c){try{var d=vc.u("a",b)}catch(e){d=hc(E(b),"A",null,b)}return Za(d,function(b){b=Yd(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};ge.L=function(a,b,c){try{var d=vc.u("a",b)}catch(e){d=hc(E(b),"A",null,b)}return Ua(d,function(b){b=Yd(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};ge.s=function(a,b){return ge.P(a,b,!1)};ge.u=function(a,b){return ge.L(a,b,!1)};he.s=function(a,b){return ge.P(a,b,!0)};
he.u=function(a,b){return ge.L(a,b,!0)};var ie={index:function(a,b){var c=Number(a);if(isNaN(c)||0>c)throw new Fa("Illegal Index: "+a);if(b.length<=c)throw new Fa("Index out of range: "+a);return[b[c]]},name:function(a,b){return Ua(b,function(b){return tc(b,"name")==a})},value:function(a,b){return Ua(b,function(b){return tc(b,"value")===a})}};var je={className:uc,"class name":uc,css:vc,"css selector":vc,id:fe,linkText:ge,"link text":ge,name:{s:function(a,b){b=hc(E(b),"*",null,b);return Za(b,function(b){return qc(b,"name")==a})},u:function(a,b){b=hc(E(b),"*",null,b);return Ua(b,function(b){return qc(b,"name")==a})}},partialLinkText:he,"partial link text":he,tagName:hb,"tag name":hb,xpath:X};
function ke(a,b){a:{for(c in a)if(a.hasOwnProperty(c))break a;var c=null}if(c){var d=je[c];if(d&&ea(d.s))return d.s(a[c],b||la.document)}throw Error("Unsupported locator strategy: "+c);};var Z={W:function(a,b){return a.lastIndexOf("//",0)?a.lastIndexOf("document.",0)?Z.J(a,b):Z.I(a,b):Z.R(a,b)},S:function(a,b){return le(b||F(la),function(b){return b.alt==a})},T:function(a,b){return le(b||F(la),function(b){return b.className==a})},I:function(a){var b=null;try{b=eval(a)}catch(c){return null}return b?b:null},V:function(a,b){return ke({id:a},b)},J:function(a,b){return Z.id(a,b)||Z.name(a,b)},j:function(a,b){b=b||F(la);E(b);b=Vb(document,"*",null,b);a=a.split(" ");for(a[0]="name="+a[0];a.length;){var c=
a.shift(),d=b;b="value";var e=c.match(/^([A-Za-z]+)=(.+)/);e&&(b=e[1].toLowerCase(),c=e[2]);e=ie[b];if(!e)throw new Fa("Unrecognised element-filter type: '"+b+"'");b=e(c,d)}return 0<b.length?b[0]:null},aa:function(a,b){try{a:{a=decodeURIComponent(a);b=b||document;var c=b||document,d=c.$wdc_;d||(d=c.$wdc_={},d.N=ka());d.N||(d.N=ka());var e=d;if(!(null!==e&&a in e))throw new r(10,"Element does not exist in cache");var f=e[a];if(null!==f&&"setInterval"in f){if(f.closed)throw delete e[a],new r(23,"Window has been closed.");
var g=f}else{for(d=f;d;){if(d==b.documentElement){g=f;break a}d=d.parentNode}delete e[a];throw new r(10,"Element is no longer attached to the DOM");}}return g}catch(h){return null}},R:function(a,b){var c=ua(a,"/"),d={xpath:a};try{var e=ke(d,b);if(e||!c)return e}catch(f){if(!c)throw f;}d={xpath:a.substring(0,a.length-1)};return ke(d,b)}};Z.alt=Z.S;Z["class"]=Z.T;Z.dom=Z.I;Z.id=Z.V;Z.identifier=Z.J;Z.implicit=Z.W;
Z.link=function(a,b){b=(b||F(la)).getElementsByTagName("a");for(var c=0;c<b.length;c++){var d=b[c],e=d,f="";B&&"1.8"<=ob||mb||A?f=Wc(e,!1):e.textContent?f=e.textContent:e.innerText&&(f=e.innerText);e=f=f.replace(/\r\n|\r/g,"\n");e=e.replace(/\ +/g," ");f=new RegExp(String.fromCharCode(160),"g");if(mb)for(f=String.fromCharCode(160);-1!=e.indexOf(f);)e=e.replace(f," ");else e=e.replace(f," ");var f=e,e=va(f),g=a,f="glob",h=/^([a-zA-Z-]+):(.*)/.exec(g);if(h){var k=h[1],h=h[2];Sa[k.toLowerCase()]&&(f=
k.toLowerCase(),g=h)}k=Sa[f];if(!k)throw new Fa("Cannot find pattern matching strategy: "+f);"glob"==f?(g.indexOf("glob:")||(g=g.substring(5)),k=Sa.glob):"exact"!=f||g.indexOf("exact:")||(g=g.substring(6));g=ja(k,g);g.Ta=f;if(g(e))return d}return null};Z.name=Z.j;Z.stored=Z.aa;Z.xpath=Z.R;function me(a,b,c,d){var e=Z[a];if(!e)throw new Fa("Unrecognised locator type: '"+a+"'");if(c=e.call(null,b,c))return c;if(!d)return null;for(e=0;e<d.frames.length;e++){try{var f=d.frames[e].document}catch(g){}if(f&&(c=me(a,b,f,d.frames[e])))return c}return null}function le(a,b){for(var c=a.childNodes.length,d=0;d<c;d++){var e=a.childNodes[d];if(1==e.nodeType&&(b(e)||(e=le(e,b))))return e}return null};function ne(a){var b="";a&&(b=a.toUpperCase());return(b=Rc[b])?b:{create:function(b){b=F(b);Tb&&b.createEventObject?b=b.createEventObject():(b=b.createEvent("HTMLEvents"),b.initEvent(a,!0,!0));return b},g:a}};ca("_",function(a,b,c){var d;if(m(a)){(d=a.match(/^([A-Za-z]+)=.+/))?(d=d[1].toLowerCase(),d={type:d,string:a.substring(d.length+1)}):(d={string:"",type:""},d.string=a,d.type=a.lastIndexOf("//",0)?a.lastIndexOf("document.",0)?"identifier":"dom":"xpath");var e=la||la;d=me(d.type,d.string,e.document,e);if(!d)throw new Fa("Element "+a+" not found");a=d}c=c||"0,0";m(c)?(d=c.split(/,/),c=parseInt(d[0],0),d=parseInt(d[1],0)):d=c=0;if(A||Ab||wb&&0<=wa(Fb,27)){var f=a;var g=F(f),e=new jb(0,0),h=xc(g);f!=
h&&(h=yc(f),g=Wb(E(g).a),e.x=h.left+g.x,e.y=h.top+g.y);if("none"!=(wc(f,"display")||(f.currentStyle?f.currentStyle.display:null)||f.style&&f.style.display))f=zc(f);else{var g=f.style,h=g.display,k=g.visibility,p=g.position;g.visibility="hidden";g.position="absolute";g.display="inline";f=zc(f);g.display=h;g.position=p;g.visibility=k}e=new D(e.x,e.y,f.width,f.height);c+=e.left;d+=e.top}b=ne(b);c=b.create(a,{clientX:c,clientY:d,button:0,altKey:!1,ctrlKey:!1,shiftKey:!1,metaKey:!1,relatedTarget:null});
"isTrusted"in c||(c.isTrusted=!1);Tb&&a.fireEvent?a.fireEvent("on"+b.g,c):a.dispatchEvent(c)});; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
