function(){return function(){var h,aa=this;function l(a){return void 0!==a}function m(a){return"string"==typeof a}function ba(a){return"number"==typeof a}function ca(a,b){a=a.split(".");var c=aa;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ea(a){return"function"==da(a)}function fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ga(a,b,c){return a.call.apply(a.bind,arguments)}
function ha(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ia(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia=ga:ia=ha;return ia.apply(null,arguments)}
function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var la=Date.now||function(){return+new Date};function q(a,b){function c(){}c.prototype=b.prototype;a.ia=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ga=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var ma=window;function r(a,b){this.code=a;this.a=t[a]||na;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}q(r,Error);var na="unknown error",t={15:"element not selectable",11:"element not visible"};t[31]=na;t[30]=na;t[24]="invalid cookie domain";t[29]="invalid element coordinates";t[12]="invalid element state";
t[32]="invalid selector";t[51]="invalid selector";t[52]="invalid selector";t[17]="javascript error";t[405]="unsupported operation";t[34]="move target out of bounds";t[27]="no such alert";t[7]="no such element";t[8]="no such frame";t[23]="no such window";t[28]="script timeout";t[33]="session not created";t[10]="stale element reference";t[21]="timeout";t[25]="unable to set cookie";t[26]="unexpected alert open";t[13]=na;t[9]="unknown command";r.prototype.toString=function(){return this.name+": "+this.message};var oa={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};function pa(a){if(Error.captureStackTrace)Error.captureStackTrace(this,pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}q(pa,Error);pa.prototype.name="CustomError";var qa;function ra(a,b){this.width=a;this.height=b}h=ra.prototype;h.toString=function(){return"("+this.width+" x "+this.height+")"};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};h.scale=function(a,b){b=ba(b)?b:a;this.width*=a;this.height*=b;return this};function sa(a,b){var c=ta;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};function ua(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var va=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function wa(a,b){var c=0;a=va(String(a)).split(".");b=va(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;!c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=xa(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||xa(0==f[2].length,0==g[2].length)||xa(f[2],g[2]);f=f[3];g=g[3]}while(!c)}return c}function xa(a,b){return a<b?-1:a>b?1:0}
function ya(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function za(a,b,c){this.a=a;this.b=b||1;this.f=c||1};function Aa(a){this.b=a;this.a=0}function Ba(a){a=a.match(Ca);for(var b=0;b<a.length;b++)Da.test(a[b])&&a.splice(b,1);return new Aa(a)}var Ca=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,Da=/^\s/;function u(a,b){return a.b[a.a+(b||0)]}function v(a){return a.b[a.a++]}function Ea(a){return a.b.length<=a.a};function Fa(a){pa.call(this,a)}q(Fa,pa);var w;a:{var Ga=aa.navigator;if(Ga){var Ha=Ga.userAgent;if(Ha){w=Ha;break a}}w=""}function y(a){return-1!=w.indexOf(a)};function z(a,b){this.j=a;this.c=l(b)?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function Ia(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}z.prototype.a=function(a){return null===this.b||this.b==a.nodeType};z.prototype.f=function(){return this.j};
z.prototype.toString=function(){var a="Kind Test: "+this.j;null===this.c||(a+=A(this.c));return a};function Ja(a,b){this.l=a.toLowerCase();a="*"==this.l?"*":"http://www.w3.org/1999/xhtml";this.c=b?b.toLowerCase():a}Ja.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=l(a.localName)?a.localName:a.nodeName;return"*"!=this.l&&this.l!=b.toLowerCase()?!1:"*"==this.c?!0:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Ja.prototype.f=function(){return this.l};
Ja.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.l};function Ka(a){switch(a.nodeType){case 1:return ka(Ma,a);case 9:return Ka(a.documentElement);case 11:case 10:case 6:case 12:return Na;default:return a.parentNode?Ka(a.parentNode):Na}}function Na(){return null}function Ma(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Ma(a.parentNode,b):null};function Oa(a,b){return(new RegExp(a)).test(b)}function Pa(a,b){return(new RegExp(a,"i")).test(b)}function Qa(a){a=a.replace(/([.^$+(){}\[\]\\|])/g,"\\$1");a=a.replace(/\?/g,"(.|[\r\n])");return a=a.replace(/\*/g,"(.|[\r\n])*")}var Ra={exact:function(a,b){return-1!=b.indexOf(a)},glob:function(a,b){return(new RegExp("^"+Qa(a)+"$")).test(b)},globcontains:function(a,b){return(new RegExp(Qa(a))).test(b)},regex:Oa,regexi:Pa,regexpi:Pa,regexp:Oa};function Sa(a,b){if(m(a))return m(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function B(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function Ta(a,b){for(var c=a.length,d=[],e=0,f=m(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d}function Ua(a,b,c){var d=c;B(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}
function Va(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function Wa(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}function Xa(a,b){a:{for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:m(a)?a.charAt(b):a[b]}function Ya(a){return Array.prototype.concat.apply([],arguments)}
function Za(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function $a(){return y("iPhone")&&!y("iPod")&&!y("iPad")};var ab="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),bb=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,cb=/^#(?:[0-9a-f]{3}){1,2}$/i,db=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,eb=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;var fb={v:function(a,b){if(""===a)throw new r(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},w:function(a,b){if(""===a)throw new r(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};function gb(){return(y("Chrome")||y("CriOS"))&&!y("Edge")};function hb(a,b){this.x=l(a)?a:0;this.y=l(b)?b:0}h=hb.prototype;h.toString=function(){return"("+this.x+", "+this.y+")"};h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};h.scale=function(a,b){b=ba(b)?b:a;this.x*=a;this.y*=b;return this};var ib=y("Opera"),C=y("Trident")||y("MSIE"),jb=y("Edge"),kb=y("Gecko")&&!(-1!=w.toLowerCase().indexOf("webkit")&&!y("Edge"))&&!(y("Trident")||y("MSIE"))&&!y("Edge"),lb=-1!=w.toLowerCase().indexOf("webkit")&&!y("Edge"),mb=y("Macintosh"),nb=y("Windows");function ob(){var a=aa.document;return a?a.documentMode:void 0}var pb;
a:{var qb="",rb=function(){var a=w;if(kb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(jb)return/Edge\/([\d\.]+)/.exec(a);if(C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(lb)return/WebKit\/(\S+)/.exec(a);if(ib)return/(?:Version)[ \/]?(\S+)/.exec(a)}();rb&&(qb=rb?rb[1]:"");if(C){var sb=ob();if(null!=sb&&sb>parseFloat(qb)){pb=String(sb);break a}}pb=qb}var ta={};function tb(a){return sa(a,function(){return 0<=wa(pb,a)})}var ub;var vb=aa.document;
ub=vb&&C?ob()||("CSS1Compat"==vb.compatMode?parseInt(pb,10):5):void 0;function wb(a,b,c,d){this.c=a;this.a=b;this.b=c;this.f=d}h=wb.prototype;h.toString=function(){return"("+this.c+"t, "+this.a+"r, "+this.b+"b, "+this.f+"l)"};h.contains=function(a){return this&&a?a instanceof wb?a.f>=this.f&&a.a<=this.a&&a.c>=this.c&&a.b<=this.b:a.x>=this.f&&a.x<=this.a&&a.y>=this.c&&a.y<=this.b:!1};h.ceil=function(){this.c=Math.ceil(this.c);this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.f=Math.ceil(this.f);return this};
h.floor=function(){this.c=Math.floor(this.c);this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.f=Math.floor(this.f);return this};h.round=function(){this.c=Math.round(this.c);this.a=Math.round(this.a);this.b=Math.round(this.b);this.f=Math.round(this.f);return this};h.scale=function(a,b){b=ba(b)?b:a;this.f*=a;this.a*=a;this.c*=b;this.b*=b;return this};function xb(a,b){this.B={};this.o=[];this.a=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof xb){d=yb(a);zb(a);var e=[];for(c=0;c<a.o.length;c++)e.push(a.B[a.o[c]])}else{var c=[],f=0;for(d in a)c[f++]=d;d=c;c=[];f=0;for(e in a)c[f++]=a[e];e=c}for(c=0;c<d.length;c++)this.set(d[c],e[c])}}function yb(a){zb(a);return a.o.concat()}
function zb(a){var b,c;if(a.a!=a.o.length){for(b=c=0;c<a.o.length;){var d=a.o[c];Object.prototype.hasOwnProperty.call(a.B,d)&&(a.o[b++]=d);c++}a.o.length=b}if(a.a!=a.o.length){var e={};for(b=c=0;c<a.o.length;)d=a.o[c],Object.prototype.hasOwnProperty.call(e,d)||(a.o[b++]=d,e[d]=1),c++;a.o.length=b}}xb.prototype.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.B,a)?this.B[a]:b};
xb.prototype.set=function(a,b){Object.prototype.hasOwnProperty.call(this.B,a)||(this.a++,this.o.push(a));this.B[a]=b};var Ab=y("Firefox"),Bb=$a()||y("iPod"),Cb=y("iPad"),Db=y("Android")&&!(gb()||y("Firefox")||y("Opera")||y("Silk")),Eb=gb(),Fb=y("Safari")&&!(gb()||y("Coast")||y("Opera")||y("Edge")||y("Silk")||y("Android"))&&!($a()||y("iPad")||y("iPod"));var Gb=C&&!(9<=Number(ub)),Hb=C&&!(8<=Number(ub));function D(a,b,c,d){this.a=a;this.b=b;this.width=c;this.height=d}h=D.prototype;h.toString=function(){return"("+this.a+", "+this.b+" - "+this.width+"w x "+this.height+"h)"};h.contains=function(a){return a instanceof hb?a.x>=this.a&&a.x<=this.a+this.width&&a.y>=this.b&&a.y<=this.b+this.height:this.a<=a.a&&this.a+this.width>=a.a+a.width&&this.b<=a.b&&this.b+this.height>=a.b+a.height};
h.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.scale=function(a,b){b=ba(b)?b:a;this.a*=a;this.width*=a;this.b*=b;this.height*=b;return this};function Ib(a){return(a=a.exec(w))?a[1]:""}var Jb=function(){if(Ab)return Ib(/Firefox\/([0-9.]+)/);if(C||jb||ib)return pb;if(Eb)return $a()||y("iPad")||y("iPod")?Ib(/CriOS\/([0-9.]+)/):Ib(/Chrome\/([0-9.]+)/);if(Fb&&!($a()||y("iPad")||y("iPod")))return Ib(/Version\/([0-9.]+)/);if(Bb||Cb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(w);if(a)return a[1]+"."+a[2]}else if(Db)return(a=Ib(/Android\s+([0-9.]+)/))?a:Ib(/Version\/([0-9.]+)/);return""}();function Kb(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Lb(a,b){var c=Hb&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Kb(b,a,b.nodeName,c)};var Mb={},Nb,Ob;function Pb(a){return Qb?Nb(a):C?0<=wa(ub,a):tb(a)}function Rb(a){return Qb?Ob(a):Db?0<=wa(Sb,a):0<=wa(Jb,a)}
var Qb=function(){if(!kb)return!1;var a=aa.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;Nb=function(a){return 0<=c.compare(d,""+a)};Ob=function(a){return 0<=c.compare(e,""+a)};return!0}(),Tb;if(Db){var Ub=/Android\s+([0-9\.]+)/.exec(w);Tb=Ub?Ub[1]:"0"}else Tb="0";
var Sb=Tb,Vb=C&&!(8<=Number(ub)),Wb=C&&!(9<=Number(ub));Db&&Rb(2.3);Db&&Rb(4);Fb&&Rb(6);function Xb(a){return a?new Yb(E(a)):qa||(qa=new Yb)}
function Zb(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){d=a.getElementsByClassName(c);if(e){a={};for(var f=b=0,g;g=d[f];f++)e==g.nodeName&&(a[b++]=g);a.length=b;return a}return d}d=a.getElementsByTagName(e||"*");if(c){a={};for(f=b=0;g=d[f];f++){var e=g.className,k;if(k="function"==typeof e.split)k=0<=Sa(e.split(/\s+/),c);k&&(a[b++]=g)}a.length=b;return a}return d}
function $b(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function ac(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function bc(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(C&&!(9<=Number(ub))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?cc(a,b):!c&&ac(e,b)?-1*dc(a,b):!d&&ac(f,a)?dc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=E(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(aa.Range.START_TO_END,a)}function dc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return cc(b,a)}function cc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function E(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var ec={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},fc={IMG:" ",BR:"\n"};
function gc(a,b,c){if(!(a.nodeName in ec))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in fc)b.push(fc[a.nodeName]);else for(a=a.firstChild;a;)gc(a,b,c),a=a.nextSibling}function hc(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function Yb(a){this.a=a||aa.document||document}Yb.prototype.getElementsByTagName=function(a,b){return(b||this.a).getElementsByTagName(String(a))};
function ic(a,b,c,d){return Zb(a.a,b,c,d)}Yb.prototype.contains=ac;function F(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(Gb&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),Gb&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function jc(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}Hb&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function kc(a,b,c,d,e){return(Gb?lc:mc).call(null,a,b,m(c)?c:null,m(d)?d:null,e||new G)}
function lc(a,b,c,d,e){if(a instanceof Ja||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;var g=nc(a);if("*"!=g&&(f=b.getElementsByTagName(g),!f))return e;if(c){var k=[];for(a=0;b=f[a++];)jc(b,c,d)&&k.push(b);f=k}for(a=0;b=f[a++];)"*"==g&&"!"==b.tagName||H(e,b);return e}oc(a,b,c,d,e);return e}
function mc(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!C?(b=b.getElementsByName(d),B(b,function(b){a.a(b)&&H(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),B(b,function(b){b.className==d&&a.a(b)&&H(e,b)})):a instanceof z?oc(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),B(b,function(a){jc(a,c,d)&&H(e,a)}));return e}
function pc(a,b,c,d,e){var f;if((a instanceof Ja||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var g=nc(a);if("*"!=g&&(f=Ta(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=Ta(f,function(a){return jc(a,c,d)}));B(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||H(e,a)});return e}return qc(a,b,c,d,e)}function qc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)jc(b,c,d)&&a.a(b)&&H(e,b);return e}
function oc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)jc(b,c,d)&&a.a(b)&&H(e,b),oc(a,b,c,d,e)}function nc(a){if(a instanceof z){if(8==a.b)return"!";if(null===a.b)return"*"}return a.f()};function rc(a,b){b=b.toLowerCase();return"style"==b?sc(a.style.cssText):Vb&&"value"==b&&I(a,"INPUT")?a.value:Wb&&!0===a[b]?String(a.getAttribute(b)):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var tc=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function sc(a){var b=[];B(a.split(tc),function(a){var c=a.indexOf(":");0<c&&(a=[a.slice(0,c),a.slice(c+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function uc(a,b){Vb&&"value"==b&&I(a,"OPTION")&&null===rc(a,"value")?(b=[],gc(a,b,!1),a=b.join("")):a=a[b];return a}function I(a,b){b&&"string"!==typeof b&&(b=b.toString());return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};lb||kb&&Pb(3.5)||C&&Pb(8);var vc={F:function(a){return!(!a.querySelectorAll||!a.querySelector)},v:function(a,b){if(!a)throw new r(32,"No class name specified");a=va(a);if(-1!==a.indexOf(" "))throw new r(32,"Compound class names not permitted");if(vc.F(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new r(32,"An invalid or illegal class name was specified");}a=ic(Xb(b),"*",a,b);return a.length?a[0]:null},w:function(a,b){if(!a)throw new r(32,"No class name specified");a=va(a);if(-1!==a.indexOf(" "))throw new r(32,
"Compound class names not permitted");if(vc.F(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new r(32,"An invalid or illegal class name was specified");}return ic(Xb(b),"*",a,b)}};var wc={v:function(a,b){if(!ea(b.querySelector)&&C&&Pb(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new r(32,"No selector specified");a=va(a);try{var c=b.querySelector(a)}catch(d){throw new r(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},w:function(a,b){if(!ea(b.querySelectorAll)&&C&&Pb(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new r(32,"No selector specified");a=va(a);try{return b.querySelectorAll(a)}catch(c){throw new r(32,
"An invalid or illegal selector was specified");}}};function G(){this.b=this.a=null;this.s=0}function xc(a){this.node=a;this.a=this.b=null}function yc(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;){e=c.node;var g=b.node;e==g||e instanceof Kb&&g instanceof Kb&&e.a==g.a?(e=c,c=c.a,b=b.a):0<bc(c.node,b.node)?(e=b,b=b.a):(e=c,c=c.a);(e.b=d)?d.a=e:a.a=e;d=e;f++}for(e=c||b;e;)e.b=d,d=d.a=e,f++,e=e.a;a.b=d;a.s=f;return a}function zc(a,b){b=new xc(b);b.a=a.a;a.b?a.a.b=b:a.a=a.b=b;a.a=b;a.s++}
function H(a,b){b=new xc(b);b.b=a.b;a.a?a.b.a=b:a.a=a.b=b;a.b=b;a.s++}function Ac(a){return(a=a.a)?a.node:null}G.prototype.f=function(){var a=Ac(this);return a?F(a):""};function Bc(a,b){return new Cc(a,!!b)}function Cc(a,b){this.f=a;this.b=(this.C=b)?a.b:a.a;this.a=null}function J(a){var b=a.b;if(b){var c=a.a=b;a.b=a.C?b.b:b.a;return c.node}return null};C&&Pb(10);Db&&Rb(4);function L(a){this.m=a;this.b=this.i=!1;this.f=null}function A(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Dc(a,b){a.i=b}function Ec(a,b){a.b=b}function M(a,b){a=a.a(b);return a instanceof G?+a.f():+a}function N(a,b){a=a.a(b);return a instanceof G?a.f():""+a}function Fc(a,b){a=a.a(b);return a instanceof G?!!a.s:!!a};var Gc="function"===typeof ShadowRoot;
function Hc(a,b){if(a.style&&("hidden"==a.style.visibility||"none"==a.style.display))return"";if(3==a.nodeType){var c=a.data;b||(c=c.replace(/\n|\r|\t/g," "));return c.replace(/&nbsp/," ")}if(Gc&&1==a.nodeType&&null!==a.shadowRoot)return Hc(a.shadowRoot,b);if((1==a.nodeType||11==a.nodeType)&&"SCRIPT"!=a.nodeName&&"STYLE"!=a.nodeName){var d=b||"PRE"==a.tagName;c="";for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes.item(e);if(f)if(!Gc||"CONTENT"!=f.nodeName&&"SLOT"!=f.nodeName)c+=Hc(f,d);else for(var f=
"CONTENT"==f.nodeName?f.getDistributedNodes():f.assignedNodes(),g=0;g<f.length;g++){var k=f[g];k&&(c+=Hc(k,b))}}if("P"==a.tagName||"BR"==a.tagName||"HR"==a.tagName||"DIV"==a.tagName)c+="\n";c=c.replace(/&nbsp/," ");Mb.fa&&Rb(9)&&(c=c.replace(/&#100;/," "));return c}return""};function Ic(a,b,c){L.call(this,a.m);this.c=a;this.j=b;this.A=c;this.i=b.i||c.i;this.b=b.b||c.b;this.c==Jc&&(c.b||c.i||4==c.m||0==c.m||!b.f?b.b||b.i||4==b.m||0==b.m||!c.f||(this.f={name:c.f.name,D:b}):this.f={name:b.f.name,D:c})}q(Ic,L);
function Kc(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof G&&c instanceof G){b=Bc(b);for(d=J(b);d;d=J(b))for(e=Bc(c),f=J(e);f;f=J(e))if(a(F(d),F(f)))return!0;return!1}if(b instanceof G||c instanceof G){b instanceof G?(e=b,d=c):(e=c,d=b);f=Bc(e);for(var g=typeof d,k=J(f);k;k=J(f)){switch(g){case "number":k=+F(k);break;case "boolean":k=!!F(k);break;case "string":k=F(k);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(k,d)||e==c&&a(d,k))return!0}return!1}return e?
"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Ic.prototype.a=function(a){return this.c.u(this.j,this.A,a)};Ic.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+A(this.j);return a+=A(this.A)};function Lc(a,b,c,d){this.ca=a;this.S=b;this.m=c;this.u=d}Lc.prototype.toString=function(){return this.ca};var Mc={};
function O(a,b,c,d){if(Mc.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new Lc(a,b,c,d);return Mc[a.toString()]=a}O("div",6,1,function(a,b,c){return M(a,c)/M(b,c)});O("mod",6,1,function(a,b,c){return M(a,c)%M(b,c)});O("*",6,1,function(a,b,c){return M(a,c)*M(b,c)});O("+",5,1,function(a,b,c){return M(a,c)+M(b,c)});O("-",5,1,function(a,b,c){return M(a,c)-M(b,c)});O("<",4,2,function(a,b,c){return Kc(function(a,b){return a<b},a,b,c)});
O(">",4,2,function(a,b,c){return Kc(function(a,b){return a>b},a,b,c)});O("<=",4,2,function(a,b,c){return Kc(function(a,b){return a<=b},a,b,c)});O(">=",4,2,function(a,b,c){return Kc(function(a,b){return a>=b},a,b,c)});var Jc=O("=",3,2,function(a,b,c){return Kc(function(a,b){return a==b},a,b,c,!0)});O("!=",3,2,function(a,b,c){return Kc(function(a,b){return a!=b},a,b,c,!0)});O("and",2,2,function(a,b,c){return Fc(a,c)&&Fc(b,c)});O("or",1,2,function(a,b,c){return Fc(a,c)||Fc(b,c)});function Nc(a,b){if(b.a.length&&4!=a.m)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");L.call(this,a.m);this.c=a;this.j=b;this.i=a.i;this.b=a.b}q(Nc,L);Nc.prototype.a=function(a){a=this.c.a(a);return Oc(this.j,a)};Nc.prototype.toString=function(){var a="Filter:"+A(this.c);return a+=A(this.j)};function Pc(a,b){if(b.length<a.P)throw Error("Function "+a.l+" expects at least"+a.P+" arguments, "+b.length+" given");if(null!==a.I&&b.length>a.I)throw Error("Function "+a.l+" expects at most "+a.I+" arguments, "+b.length+" given");a.ba&&B(b,function(b,d){if(4!=b.m)throw Error("Argument "+d+" to function "+a.l+" is not of type Nodeset: "+b);});L.call(this,a.m);this.G=a;this.c=b;Dc(this,a.i||Va(b,function(a){return a.i}));Ec(this,a.aa&&!b.length||a.$&&!!b.length||Va(b,function(a){return a.b}))}
q(Pc,L);Pc.prototype.a=function(a){return this.G.u.apply(null,Ya(a,this.c))};Pc.prototype.toString=function(){var a="Function: "+this.G;if(this.c.length)var b=Ua(this.c,function(a,b){return a+A(b)},"Arguments:"),a=a+A(b);return a};function Qc(a,b,c,d,e,f,g,k,n){this.l=a;this.m=b;this.i=c;this.aa=d;this.$=e;this.u=f;this.P=g;this.I=l(k)?k:g;this.ba=!!n}Qc.prototype.toString=function(){return this.l};var Rc={};
function P(a,b,c,d,e,f,g,k){if(Rc.hasOwnProperty(a))throw Error("Function already created: "+a+".");Rc[a]=new Qc(a,b,c,d,!1,e,f,g,k)}P("boolean",2,!1,!1,function(a,b){return Fc(b,a)},1);P("ceiling",1,!1,!1,function(a,b){return Math.ceil(M(b,a))},1);P("concat",3,!1,!1,function(a,b){return Ua(Za(arguments,1),function(b,d){return b+N(d,a)},"")},2,null);P("contains",2,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);return-1!=b.indexOf(a)},2);P("count",1,!1,!1,function(a,b){return b.a(a).s},1,1,!0);
P("false",2,!1,!1,function(){return!1},0);P("floor",1,!1,!1,function(a,b){return Math.floor(M(b,a))},1);P("id",4,!1,!1,function(a,b){function c(a){if(Gb){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return Xa(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument;a=N(b,a).split(/\s+/);var f=[];B(a,function(a){a=c(a);!a||0<=Sa(f,a)||f.push(a)});f.sort(bc);var g=new G;B(f,function(a){H(g,a)});return g},1);
P("lang",2,!1,!1,function(){return!1},1);P("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);P("local-name",3,!1,!0,function(a,b){return(a=b?Ac(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);P("name",3,!1,!0,function(a,b){return(a=b?Ac(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);P("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
P("normalize-space",3,!1,!0,function(a,b){return(b?N(b,a):F(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);P("not",2,!1,!1,function(a,b){return!Fc(b,a)},1);P("number",1,!1,!0,function(a,b){return b?M(b,a):+F(a.a)},0,1);P("position",1,!0,!1,function(a){return a.b},0);P("round",1,!1,!1,function(a,b){return Math.round(M(b,a))},1);P("starts-with",2,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);return!b.lastIndexOf(a,0)},2);P("string",3,!1,!0,function(a,b){return b?N(b,a):F(a.a)},0,1);
P("string-length",1,!1,!0,function(a,b){return(b?N(b,a):F(a.a)).length},0,1);P("substring",3,!1,!1,function(a,b,c,d){c=M(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?M(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=N(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);P("substring-after",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
P("substring-before",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);P("sum",1,!1,!1,function(a,b){a=Bc(b.a(a));b=0;for(var c=J(a);c;c=J(a))b+=+F(c);return b},1,1,!0);P("translate",3,!1,!1,function(a,b,c,d){b=N(b,a);c=N(c,a);var e=N(d,a);d={};for(var f=0;f<c.length;f++)a=c.charAt(f),a in d||(d[a]=e.charAt(f));c="";for(f=0;f<b.length;f++)a=b.charAt(f),c+=a in d?d[a]:a;return c},3);P("true",2,!1,!1,function(){return!0},0);function Sc(a){L.call(this,3);this.c=a.substring(1,a.length-1)}q(Sc,L);Sc.prototype.a=function(){return this.c};Sc.prototype.toString=function(){return"Literal: "+this.c};function Tc(a){L.call(this,1);this.c=a}q(Tc,L);Tc.prototype.a=function(){return this.c};Tc.prototype.toString=function(){return"Number: "+this.c};function Uc(a,b){L.call(this,a.m);this.j=a;this.c=b;this.i=a.i;this.b=a.b;1==this.c.length&&(a=this.c[0],a.H||a.c!=Vc||(a=a.A,"*"!=a.f()&&(this.f={name:a.f(),D:null})))}q(Uc,L);function Wc(){L.call(this,4)}q(Wc,L);Wc.prototype.a=function(a){var b=new G;a=a.a;9==a.nodeType?H(b,a):H(b,a.ownerDocument);return b};Wc.prototype.toString=function(){return"Root Helper Expression"};function Xc(){L.call(this,4)}q(Xc,L);Xc.prototype.a=function(a){var b=new G;H(b,a.a);return b};Xc.prototype.toString=function(){return"Context Helper Expression"};
function Yc(a){return"/"==a||"//"==a}Uc.prototype.a=function(a){var b=this.j.a(a);if(!(b instanceof G))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.s;c++){var e=a[c],f=Bc(b,e.c.C);if(e.i||e.c!=Zc)if(e.i||e.c!=$c){var g=J(f);for(b=e.a(new za(g));g=J(f);)g=e.a(new za(g)),b=yc(b,g)}else g=J(f),b=e.a(new za(g));else{for(g=J(f);(b=J(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new za(g))}}return b};
Uc.prototype.toString=function(){var a="Path Expression:"+A(this.j);if(this.c.length){var b=Ua(this.c,function(a,b){return a+A(b)},"Steps:");a+=A(b)}return a};function ad(a,b){this.a=a;this.C=!!b}
function Oc(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=Bc(b),f=b.s,g,k=0;g=J(e);k++){var n=a.C?f-k:k+1;g=d.a(new za(g,n,f));if("number"==typeof g)n=n==g;else if("string"==typeof g||"boolean"==typeof g)n=!!g;else if(g instanceof G)n=0<g.s;else throw Error("Predicate.evaluate returned an unexpected type.");if(!n){n=e;g=n.f;var x=n.a;if(!x)throw Error("Next must be called at least once before remove.");var p=x.b,x=x.a;p?p.a=x:g.a=x;x?x.b=p:g.b=p;g.s--;n.a=null}}return b}
ad.prototype.toString=function(){return Ua(this.a,function(a,b){return a+A(b)},"Predicates:")};function bd(a){L.call(this,1);this.c=a;this.i=a.i;this.b=a.b}q(bd,L);bd.prototype.a=function(a){return-M(this.c,a)};bd.prototype.toString=function(){return"Unary Expression: -"+A(this.c)};function cd(a){L.call(this,4);this.c=a;Dc(this,Va(this.c,function(a){return a.i}));Ec(this,Va(this.c,function(a){return a.b}))}q(cd,L);cd.prototype.a=function(a){var b=new G;B(this.c,function(c){c=c.a(a);if(!(c instanceof G))throw Error("Path expression must evaluate to NodeSet.");b=yc(b,c)});return b};cd.prototype.toString=function(){return Ua(this.c,function(a,b){return a+A(b)},"Union Expression:")};function dd(a,b,c,d){L.call(this,4);this.c=a;this.A=b;this.j=c||new ad([]);this.H=!!d;b=this.j;b=0<b.a.length?b.a[0].f:null;a.ea&&b&&(a=b.name,a=Gb?a.toLowerCase():a,this.f={name:a,D:b.D});a:{a=this.j;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.i||1==c.m||0==c.m){a=!0;break a}a=!1}this.i=a}q(dd,L);
dd.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.D?N(c.D,a):null,f=1);if(this.H)if(this.i||this.c!=ed)if(b=Bc((new dd(fd,new z("node"))).a(a)),c=J(b))for(a=this.u(c,d,e,f);c=J(b);)a=yc(a,this.u(c,d,e,f));else a=new G;else a=kc(this.A,b,d,e),a=Oc(this.j,a,f);else a=this.u(a.a,d,e,f);return a};dd.prototype.u=function(a,b,c,d){a=this.c.G(this.A,a,b,c);return a=Oc(this.j,a,d)};
dd.prototype.toString=function(){var a="Step:"+A("Operator: "+(this.H?"//":"/"));this.c.l&&(a+=A("Axis: "+this.c));a+=A(this.A);if(this.j.a.length){var b=Ua(this.j.a,function(a,b){return a+A(b)},"Predicates:");a+=A(b)}return a};function gd(a,b,c,d){this.l=a;this.G=b;this.C=c;this.ea=d}gd.prototype.toString=function(){return this.l};var hd={};function Q(a,b,c,d){if(hd.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new gd(a,b,c,!!d);return hd[a]=b}
Q("ancestor",function(a,b){for(var c=new G;b=b.parentNode;)a.a(b)&&zc(c,b);return c},!0);Q("ancestor-or-self",function(a,b){var c=new G;do a.a(b)&&zc(c,b);while(b=b.parentNode);return c},!0);
var Vc=Q("attribute",function(a,b){var c=new G,d=a.f();if("style"==d&&Gb&&b.style)return H(c,new Kb(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof z&&null===a.b||"*"==d)for(d=0;a=e[d];d++)Gb?a.nodeValue&&H(c,Lb(b,a)):H(c,a);else(a=e.getNamedItem(d))&&(Gb?a.nodeValue&&H(c,Lb(b,a)):H(c,a));return c},!1),ed=Q("child",function(a,b,c,d,e){return(Gb?pc:qc).call(null,a,b,m(c)?c:null,m(d)?d:null,e||new G)},!1,!0);Q("descendant",kc,!1,!0);
var fd=Q("descendant-or-self",function(a,b,c,d){var e=new G;jc(b,c,d)&&a.a(b)&&H(e,b);return kc(a,b,c,d,e)},!1,!0),Zc=Q("following",function(a,b,c,d){var e=new G;do for(var f=b;f=f.nextSibling;)jc(f,c,d)&&a.a(f)&&H(e,f),e=kc(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);Q("following-sibling",function(a,b){for(var c=new G;b=b.nextSibling;)a.a(b)&&H(c,b);return c},!1);Q("namespace",function(){return new G},!1);
var id=Q("parent",function(a,b){var c=new G;if(9==b.nodeType)return c;if(2==b.nodeType)return H(c,b.ownerElement),c;b=b.parentNode;a.a(b)&&H(c,b);return c},!1),$c=Q("preceding",function(a,b,c,d){var e=new G,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,k=f.length;g<k;g++){var n=[];for(b=f[g];b=b.previousSibling;)n.unshift(b);for(var x=0,p=n.length;x<p;x++)b=n[x],jc(b,c,d)&&a.a(b)&&H(e,b),e=kc(a,b,c,d,e)}return e},!0,!0);
Q("preceding-sibling",function(a,b){for(var c=new G;b=b.previousSibling;)a.a(b)&&zc(c,b);return c},!0);var jd=Q("self",function(a,b){var c=new G;a.a(b)&&H(c,b);return c},!1);function kd(a,b){this.a=a;this.b=b}function ld(a){for(var b,c=[];;){R(a,"Missing right hand side of binary expression.");b=md(a);var d=v(a.a);if(!d)break;var e=(d=Mc[d]||null)&&d.S;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].S;)b=new Ic(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Ic(c.pop(),c.pop(),b);return b}function R(a,b){if(Ea(a.a))throw Error(b);}function nd(a,b){a=v(a.a);if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function od(a){a=v(a.a);if(")"!=a)throw Error("Bad token: "+a);}function pd(a){a=v(a.a);if(2>a.length)throw Error("Unclosed literal string");return new Sc(a)}
function qd(a){var b=[];if(Yc(u(a.a))){var c=v(a.a);var d=u(a.a);if("/"==c&&(Ea(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new Wc;d=new Wc;R(a,"Missing next location step.");c=rd(a,c);b.push(c)}else{a:{c=u(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":v(a.a);c=ld(a);R(a,'unclosed "("');nd(a,")");break;case '"':case "'":c=pd(a);break;default:if(isNaN(+c))if(!Ia(c)&&/(?![0-9])[\w]/.test(d)&&"("==u(a.a,1)){c=v(a.a);
c=Rc[c]||null;v(a.a);for(d=[];")"!=u(a.a);){R(a,"Missing function argument list.");d.push(ld(a));if(","!=u(a.a))break;v(a.a)}R(a,"Unclosed function argument list.");od(a);c=new Pc(c,d)}else{c=null;break a}else c=new Tc(+v(a.a))}"["==u(a.a)&&(d=new ad(sd(a)),c=new Nc(c,d))}if(c)if(Yc(u(a.a)))d=c;else return c;else c=rd(a,"/"),d=new Xc,b.push(c)}for(;Yc(u(a.a));)c=v(a.a),R(a,"Missing next location step."),c=rd(a,c),b.push(c);return new Uc(d,b)}
function rd(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==u(a.a)){var c=new dd(jd,new z("node"));v(a.a);return c}if(".."==u(a.a))return c=new dd(id,new z("node")),v(a.a),c;if("@"==u(a.a)){var d=Vc;v(a.a);R(a,"Missing attribute name")}else if("::"==u(a.a,1)){if(!/(?![0-9])[\w]/.test(u(a.a).charAt(0)))throw Error("Bad token: "+v(a.a));var e=v(a.a);d=hd[e]||null;if(!d)throw Error("No axis with name: "+e);v(a.a);R(a,"Missing node name")}else d=ed;e=u(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==
u(a.a,1)){if(!Ia(e))throw Error("Invalid node type: "+e);e=v(a.a);if(!Ia(e))throw Error("Invalid type name: "+e);nd(a,"(");R(a,"Bad nodetype");var f=u(a.a).charAt(0),g=null;if('"'==f||"'"==f)g=pd(a);R(a,"Bad nodetype");od(a);e=new z(e,g)}else if(e=v(a.a),f=e.indexOf(":"),-1==f)e=new Ja(e);else{var g=e.substring(0,f);if("*"==g)var k="*";else if(k=a.b(g),!k)throw Error("Namespace prefix not declared: "+g);e=e.substr(f+1);e=new Ja(e,k)}else throw Error("Bad token: "+v(a.a));a=new ad(sd(a),d.C);return c||
new dd(d,e,a,"//"==b)}function sd(a){for(var b=[];"["==u(a.a);){v(a.a);R(a,"Missing predicate expression.");var c=ld(a);b.push(c);R(a,"Unclosed predicate expression.");nd(a,"]")}return b}function md(a){if("-"==u(a.a))return v(a.a),new bd(md(a));var b=qd(a);if("|"!=u(a.a))a=b;else{for(b=[b];"|"==v(a.a);)R(a,"Missing next union location path."),b.push(qd(a));a.a.a--;a=new cd(b)}return a};function td(a,b){if(!a.length)throw Error("Empty XPath expression.");a=Ba(a);if(Ea(a))throw Error("Invalid XPath expression.");b?ea(b)||(b=ia(b.lookupNamespaceURI,b)):b=function(){return null};var c=ld(new kd(a,b));if(!Ea(a))throw Error("Bad token: "+v(a));this.evaluate=function(a,b){a=c.a(new za(a));return new S(a,b)}}
function S(a,b){if(!b)if(a instanceof G)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof G))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof G?a.f():""+a;break;case 1:this.numberValue=a instanceof G?+a.f():+a;break;case 3:this.booleanValue=a instanceof G?0<a.s:!!a;break;case 4:case 5:case 6:case 7:var c=
Bc(a);var d=[];for(var e=J(c);e;e=J(c))d.push(e instanceof Kb?e.a:e);this.snapshotLength=a.s;this.invalidIteratorState=!1;break;case 8:case 9:a=Ac(a);this.singleNodeValue=a instanceof Kb?a.a:a;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=d.length||
0>a?null:d[a]}}S.ANY_TYPE=0;S.NUMBER_TYPE=1;S.STRING_TYPE=2;S.BOOLEAN_TYPE=3;S.UNORDERED_NODE_ITERATOR_TYPE=4;S.ORDERED_NODE_ITERATOR_TYPE=5;S.UNORDERED_NODE_SNAPSHOT_TYPE=6;S.ORDERED_NODE_SNAPSHOT_TYPE=7;S.ANY_UNORDERED_NODE_TYPE=8;S.FIRST_ORDERED_NODE_TYPE=9;function ud(a){this.lookupNamespaceURI=Ka(a)}
function vd(a,b){a=a||aa;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=S,c.evaluate=function(a,b,c,g){return(new td(a,c)).evaluate(b,g)},c.createExpression=function(a,b){return new td(a,b)},c.createNSResolver=function(a){return new ud(a)}}ca("wgxpath.install",vd);var U={};U.J=function(){var a={ja:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
U.u=function(a,b,c){var d=E(a);if(!d.documentElement)return null;(C||Db)&&vd(d?d.parentWindow||d.defaultView:window);try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):U.J;if(C&&!tb(7))return d.evaluate.call(d,b,a,e,c,null);if(!C||9<=Number(ub)){for(var f={},g=d.getElementsByTagName("*"),k=0;k<g.length;++k){var n=g[k],x=n.namespaceURI;if(x&&!f[x]){var p=n.lookupPrefix(x);if(!p)var K=x.match(".*/(\\w+)/?$"),p=K?K[1]:"xhtml";f[x]=p}}var T={},ja;for(ja in f)T[f[ja]]=ja;e=function(a){return T[a]||
null}}try{return d.evaluate(b,a,e,c,null)}catch(La){if("TypeError"===La.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):U.J,d.evaluate(b,a,e,c,null);throw La;}}catch(La){if(!kb||"NS_ERROR_ILLEGAL_VALUE"!=La.name)throw new r(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+La);}};U.K=function(a,b){if(!a||1!=a.nodeType)throw new r(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
U.v=function(a,b){var c=function(){var c=U.u(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=E(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||U.K(c,a);return c};
U.w=function(a,b){var c=function(){var c=U.u(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=E(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();B(c,function(b){U.K(b,a)});return c};var wd="function"===typeof ShadowRoot;function xd(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return I(a)?a:null}
function V(a,b){b=ya(b);if("float"==b||"cssFloat"==b||"styleFloat"==b)b=Wb?"styleFloat":"cssFloat";a:{var c=b;var d=E(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||yd(a,b);if(null===a)a=null;else if(0<=Sa(ab,b)){b:{var e=a.match(db);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),e=Number(e[4]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d&&0<=e&&1>=e)){b=[b,c,d,e];break b}b=null}if(!b)b:{if(d=a.match(eb))if(b=
Number(d[1]),c=Number(d[2]),d=Number(d[3]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=oa[b.toLowerCase()];if(!c&&(c="#"==b.charAt(0)?b:"#"+b,4==c.length&&(c=c.replace(bb,"#$1$1$2$2$3$3")),!cb.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}
function yd(a,b){var c=a.currentStyle||a.style,d=c[b];!l(d)&&ea(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?l(d)?d:null:(a=xd(a))?yd(a,b):null}
function zd(a,b,c){function d(a){var b=Ad(a);return 0<b.height&&0<b.width?!0:I(a,"PATH")&&(0<b.height||0<b.width)?(a=V(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=V(a,"overflow")&&Va(a.childNodes,function(a){return 3==a.nodeType||I(a)&&d(a)})}function e(a){return Bd(a)==W&&Wa(a.childNodes,function(a){return!I(a)||e(a)||!d(a)})}if(!I(a))throw Error("Argument to isShown must be of type Element");if(I(a,"BODY"))return!0;if(I(a,"OPTION")||I(a,"OPTGROUP"))return a=hc(a,function(a){return I(a,"SELECT")}),
!!a&&zd(a,!0,c);var f=Cd(a);if(f)return!!f.N&&0<f.rect.width&&0<f.rect.height&&zd(f.N,b,c);if(I(a,"INPUT")&&"hidden"==a.type.toLowerCase()||I(a,"NOSCRIPT"))return!1;f=V(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||Dd(a))&&d(a)?!e(a):!1}
function Ed(a){function b(a){if(I(a)&&"none"==V(a,"display"))return!1;var c;(c=a.parentNode)&&c.shadowRoot&&void 0!==a.assignedSlot?c=a.assignedSlot?a.assignedSlot.parentNode:null:a.getDestinationInsertionPoints&&(a=a.getDestinationInsertionPoints(),0<a.length&&(c=a[a.length-1]));if(wd&&c instanceof ShadowRoot){if(c.host.shadowRoot!==c)return!1;c=c.host}return!c||9!=c.nodeType&&11!=c.nodeType?c&&b(c):!0}return zd(a,!1,b)}var W="hidden";
function Bd(a){function b(a){function b(a){return a==g?!0:!V(a,"display").lastIndexOf("inline",0)||"absolute"==c&&"static"==V(a,"position")?!1:!0}var c=V(a,"position");if("fixed"==c)return x=!0,a==g?null:g;for(a=xd(a);a&&!b(a);)a=xd(a);return a}function c(a){var b=a;if("visible"==n)if(a==g&&k)b=k;else if(a==k)return{x:"visible",y:"visible"};b={x:V(b,"overflow-x"),y:V(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new Yb(f)).a;
a=b.scrollingElement?b.scrollingElement:lb||"CSS1Compat"!=b.compatMode?b.body||b.documentElement:b.documentElement;b=b.parentWindow||b.defaultView;a=C&&tb("10")&&b.pageYOffset!=a.scrollTop?new hb(a.scrollLeft,a.scrollTop):new hb(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new hb(a.scrollLeft,a.scrollTop);return a}var e=Fd(a);var f=E(a),g=f.documentElement,k=f.body,n=V(g,"overflow"),x;for(a=b(a);a;a=b(a)){var p=c(a);if("visible"!=p.x||"visible"!=p.y){var K=Ad(a);if(!K.width||!K.height)return W;
var T=e.a<K.a,ja=e.b<K.b;if(T&&"hidden"==p.x||ja&&"hidden"==p.y)return W;if(T&&"visible"!=p.x||ja&&"visible"!=p.y){T=d(a);ja=e.b<K.b-T.y;if(e.a<K.a-T.x&&"visible"!=p.x||ja&&"visible"!=p.x)return W;e=Bd(a);return e==W?W:"scroll"}T=e.f>=K.a+K.width;K=e.c>=K.b+K.height;if(T&&"hidden"==p.x||K&&"hidden"==p.y)return W;if(T&&"visible"!=p.x||K&&"visible"!=p.y){if(x&&(p=d(a),e.f>=g.scrollWidth-p.x||e.a>=g.scrollHeight-p.y))return W;e=Bd(a);return e==W?W:"scroll"}}}return"none"}
function Ad(a){var b=Cd(a);if(b)return b.rect;if(I(a,"HTML"))return a=E(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new ra(a.clientWidth,a.clientHeight),new D(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new D(0,0,0,0)}b=new D(c.left,c.top,c.right-c.left,c.bottom-c.top);C&&a.ownerDocument.body&&(a=E(a),b.a-=a.documentElement.clientLeft+a.body.clientLeft,b.b-=a.documentElement.clientTop+a.body.clientTop);
return b}function Cd(a){var b=I(a,"MAP");if(!b&&!I(a,"AREA"))return null;var c=b?a:I(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=U.v('/descendant::*[@usemap = "#'+c.name+'"]',E(c)))&&(e=Ad(d),b||"default"==a.shape.toLowerCase()||(a=Gd(a),b=Math.min(Math.max(a.a,0),e.width),c=Math.min(Math.max(a.b,0),e.height),e=new D(b+e.a,c+e.b,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{N:d,rect:e||new D(0,0,0,0)}}
function Gd(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new D(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new D(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new D(b,c,d-b,e-c)}return new D(0,0,0,0)}function Fd(a){a=Ad(a);return new wb(a.b,a.a+a.width,a.b+a.height,a.a)}
function Hd(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function Id(a){var b=[];wd?Jd(a,b):Kd(a,b);var c=b;a=c.length;for(var b=Array(a),c=m(c)?c.split(""):c,d=0;d<a;d++)d in c&&(b[d]=Hd.call(void 0,c[d]));return Hd(b.join("\n")).replace(/\xa0/g," ")}
function Ld(a,b,c){if(I(a,"BR"))b.push("");else{var d=I(a,"TD"),e=V(a,"display"),f=!d&&!(0<=Sa(Md,e)),g=l(a.previousElementSibling)?a.previousElementSibling:$b(a.previousSibling),g=g?V(g,"display"):"",k=V(a,"float")||V(a,"cssFloat")||V(a,"styleFloat");!f||"run-in"==g&&"none"==k||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var n=Ed(a),x=null,p=null;n&&(x=V(a,"white-space"),p=V(a,"text-transform"));B(a.childNodes,function(a){c(a,b,n,x,p)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||ua(a," ")||
(b[b.length-1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function Kd(a,b){Ld(a,b,function(a,b,e,f,g){3==a.nodeType&&e?Nd(a,b,f,g):I(a)&&Kd(a,b)})}var Md="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function Nd(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";ua(c," ")&&!a.lastIndexOf(" ",0)&&(a=a.substr(1));b.push(c+a)}
function Dd(a){if(Wb){if("relative"==V(a,"position"))return 1;a=V(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return Od(a)}function Od(a){var b=1,c=V(a,"opacity");c&&(b=Number(c));(a=xd(a))&&(b*=Od(a));return b}
function Pd(a,b,c,d,e){var f;if(3==a.nodeType&&c)Nd(a,b,d,e);else if(I(a))if(I(a,"CONTENT")||I(a,"SLOT")){for(f=a;f.parentNode;)f=f.parentNode;f instanceof ShadowRoot?(a=I(a,"CONTENT")?a.getDistributedNodes():a.assignedNodes(),B(a,function(a){Pd(a,b,c,d,e)})):Jd(a,b)}else if(I(a,"SHADOW")){for(f=a;f.parentNode;)f=f.parentNode;if(f instanceof ShadowRoot&&(a=f))for(a=a.olderShadowRoot;a;)B(a.childNodes,function(a){Pd(a,b,c,d,e)}),a=a.olderShadowRoot}else Jd(a,b)}
function Jd(a,b){a.shadowRoot&&B(a.shadowRoot.childNodes,function(a){Pd(a,b,!0,null,null)});Ld(a,b,function(a,b,e,f,g){var c=null;1==a.nodeType?c=a:3==a.nodeType&&(c=a);c&&(c.assignedSlot||c.getDestinationInsertionPoints&&0<c.getDestinationInsertionPoints().length)||Pd(a,b,e,f,g)})};var Qd={F:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},v:function(a,b){var c=Xb(b),d=m(a)?c.a.getElementById(a):a;return d?rc(d,"id")==a&&b!=d&&ac(b,d)?d:Xa(ic(c,"*"),function(c){return rc(c,"id")==a&&b!=c&&ac(b,c)}):null},w:function(a,b){if(!a)return[];if(Qd.F(b,a))try{return b.querySelectorAll("#"+Qd.X(a))}catch(c){return[]}b=ic(Xb(b),"*",null,b);return Ta(b,function(b){return rc(b,"id")==a})},X:function(a){return a.replace(/([\s'"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var X={},Rd={};X.T=function(a,b,c){try{var d=wc.w("a",b)}catch(e){d=ic(Xb(b),"A",null,b)}return Xa(d,function(b){b=Id(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};X.O=function(a,b,c){try{var d=wc.w("a",b)}catch(e){d=ic(Xb(b),"A",null,b)}return Ta(d,function(b){b=Id(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};X.v=function(a,b){return X.T(a,b,!1)};X.w=function(a,b){return X.O(a,b,!1)};Rd.v=function(a,b){return X.T(a,b,!0)};
Rd.w=function(a,b){return X.O(a,b,!0)};var Sd={index:function(a,b){var c=Number(a);if(isNaN(c)||0>c)throw new Fa("Illegal Index: "+a);if(b.length<=c)throw new Fa("Index out of range: "+a);return[b[c]]},name:function(a,b){return Ta(b,function(b){return uc(b,"name")==a})},value:function(a,b){return Ta(b,function(b){return uc(b,"value")===a})}};var Td={className:vc,"class name":vc,css:wc,"css selector":wc,id:Qd,linkText:X,"link text":X,name:{v:function(a,b){b=ic(Xb(b),"*",null,b);return Xa(b,function(b){return rc(b,"name")==a})},w:function(a,b){b=ic(Xb(b),"*",null,b);return Ta(b,function(b){return rc(b,"name")==a})}},partialLinkText:Rd,"partial link text":Rd,tagName:fb,"tag name":fb,xpath:U};
function Ud(a,b){a:{for(c in a)if(a.hasOwnProperty(c))break a;var c=null}if(c){var d=Td[c];if(d&&ea(d.v))return d.v(a[c],b||ma.document)}throw Error("Unsupported locator strategy: "+c);};lb||Qb&&Rb(3.6);var Y={Z:function(a,b){return a.lastIndexOf("//",0)?a.lastIndexOf("document.",0)?Y.M(a,b):Y.L(a,b):Y.U(a,b)},V:function(a,b){return Vd(b||E(ma),function(b){return b.alt==a})},W:function(a,b){return Vd(b||E(ma),function(b){return b.className==a})},L:function(a){var b=null;try{b=eval(a)}catch(c){return null}return b?b:null},Y:function(a,b){return Ud({id:a},b)},M:function(a,b){return Y.id(a,b)||Y.name(a,b)},l:function(a,b){b=b||E(ma);Xb(b);b=Zb(document,"*",null,b);a=a.split(" ");for(a[0]="name="+a[0];a.length;){var c=
a.shift(),d=b;b="value";var e=c.match(/^([A-Za-z]+)=(.+)/);e&&(b=e[1].toLowerCase(),c=e[2]);e=Sd[b];if(!e)throw new Fa("Unrecognised element-filter type: '"+b+"'");b=e(c,d)}return 0<b.length?b[0]:null},da:function(a,b){try{a:{a=decodeURIComponent(a);b=b||document;var c=b||document,d=c.$wdc_;d||(d=c.$wdc_={},d.R=la());d.R||(d.R=la());var e=d;if(!(null!==e&&a in e))throw new r(10,"Element does not exist in cache");var f=e[a];if(null!==f&&"setInterval"in f){if(f.closed)throw delete e[a],new r(23,"Window has been closed.");
var g=f}else{for(d=f;d;){if(d==b.documentElement){g=f;break a}d=d.parentNode}delete e[a];throw new r(10,"Element is no longer attached to the DOM");}}return g}catch(k){return null}},U:function(a,b){var c=ua(a,"/"),d={xpath:a};try{var e=Ud(d,b);if(e||!c)return e}catch(f){if(!c)throw f;}d={xpath:a.substring(0,a.length-1)};return Ud(d,b)}};Y.alt=Y.V;Y["class"]=Y.W;Y.dom=Y.L;Y.id=Y.Y;Y.identifier=Y.M;Y.implicit=Y.Z;
Y.link=function(a,b){b=(b||E(ma)).getElementsByTagName("a");for(var c=0;c<b.length;c++){var d=b[c],e=d,f="";kb&&"1.8"<=pb||lb||C?f=Hc(e,!1):e.textContent?f=e.textContent:e.innerText&&(f=e.innerText);e=f=f.replace(/\r\n|\r/g,"\n");e=e.replace(/\ +/g," ");f=new RegExp(String.fromCharCode(160),"g");if(lb)for(f=String.fromCharCode(160);-1!=e.indexOf(f);)e=e.replace(f," ");else e=e.replace(f," ");var f=e,e=va(f),g=a,f="glob",k=/^([a-zA-Z-]+):(.*)/.exec(g);if(k){var n=k[1],k=k[2];Ra[n.toLowerCase()]&&(f=
n.toLowerCase(),g=k)}n=Ra[f];if(!n)throw new Fa("Cannot find pattern matching strategy: "+f);"glob"==f?(g.indexOf("glob:")||(g=g.substring(5)),n=Ra.glob):"exact"!=f||g.indexOf("exact:")||(g=g.substring(6));g=ka(n,g);g.ha=f;if(g(e))return d}return null};Y.name=Y.l;Y.stored=Y.da;Y.xpath=Y.U;var Wd={};function Z(a,b,c){fa(a)&&(a=kb?a.g:a.h);a=new Xd(a);!b||b in Wd&&!c||(Wd[b]={key:a,shift:!1},c&&(Wd[c]={key:a,shift:!0}));return a}function Xd(a){this.code=a}Z(8);Z(9);Z(13);var Yd=Z(16),Zd=Z(17),$d=Z(18);Z(19);Z(20);Z(27);Z(32," ");Z(33);Z(34);Z(35);Z(36);Z(37);Z(38);Z(39);Z(40);Z(44);Z(45);Z(46);Z(48,"0",")");Z(49,"1","!");Z(50,"2","@");Z(51,"3","#");Z(52,"4","$");Z(53,"5","%");Z(54,"6","^");Z(55,"7","&");Z(56,"8","*");Z(57,"9","(");Z(65,"a","A");Z(66,"b","B");Z(67,"c","C");Z(68,"d","D");
Z(69,"e","E");Z(70,"f","F");Z(71,"g","G");Z(72,"h","H");Z(73,"i","I");Z(74,"j","J");Z(75,"k","K");Z(76,"l","L");Z(77,"m","M");Z(78,"n","N");Z(79,"o","O");Z(80,"p","P");Z(81,"q","Q");Z(82,"r","R");Z(83,"s","S");Z(84,"t","T");Z(85,"u","U");Z(86,"v","V");Z(87,"w","W");Z(88,"x","X");Z(89,"y","Y");Z(90,"z","Z");var ae=Z(nb?{g:91,h:91}:mb?{g:224,h:91}:{g:0,h:91});Z(nb?{g:92,h:92}:mb?{g:224,h:93}:{g:0,h:92});Z(nb?{g:93,h:93}:mb?{g:0,h:0}:{g:93,h:null});Z({g:96,h:96},"0");Z({g:97,h:97},"1");
Z({g:98,h:98},"2");Z({g:99,h:99},"3");Z({g:100,h:100},"4");Z({g:101,h:101},"5");Z({g:102,h:102},"6");Z({g:103,h:103},"7");Z({g:104,h:104},"8");Z({g:105,h:105},"9");Z({g:106,h:106},"*");Z({g:107,h:107},"+");Z({g:109,h:109},"-");Z({g:110,h:110},".");Z({g:111,h:111},"/");Z(144);Z(112);Z(113);Z(114);Z(115);Z(116);Z(117);Z(118);Z(119);Z(120);Z(121);Z(122);Z(123);Z({g:107,h:187},"=","+");Z(108,",");Z({g:109,h:189},"-","_");Z(188,",","<");Z(190,".",">");Z(191,"/","?");Z(192,"`","~");Z(219,"[","{");
Z(220,"\\","|");Z(221,"]","}");Z({g:59,h:186},";",":");Z(222,"'",'"');var be=new xb;be.set(1,Yd);be.set(2,Zd);be.set(4,$d);be.set(8,ae);(function(a){var b=new xb;B(yb(a),function(c){b.set(a.get(c).code,c)});return b})(be);kb&&Pb(12);function ce(a,b,c,d){var e=Y[a];if(!e)throw new Fa("Unrecognised locator type: '"+a+"'");if(c=e.call(null,b,c))return c;if(!d)return null;for(e=0;e<d.frames.length;e++){try{var f=d.frames[e].document}catch(g){}if(f&&(c=ce(a,b,f,d.frames[e])))return c}return null}function Vd(a,b){for(var c=a.childNodes.length,d=0;d<c;d++){var e=a.childNodes[d];if(1==e.nodeType&&(b(e)||(e=Vd(e,b))))return e}return null};ca("_",function(a){if(m(a)&&m(a)){var b;(b=a.match(/^([A-Za-z]+)=.+/))?(b=b[1].toLowerCase(),b={type:b,string:a.substring(b.length+1)}):(b={string:"",type:""},b.string=a,b.type=a.lastIndexOf("//",0)?a.lastIndexOf("document.",0)?"identifier":"dom":"xpath");var c=ma||ma;b=ce(b.type,b.string,c.document,c);if(!b)throw new Fa("Element "+a+" not found");a=b}if(!l(a.options))throw new Fa("Specified element is not a Select (has no options)");for(b=0;b<a.options.length;b++)if(a.options[b].selected)return!0;
return!1});; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
