function(){return function(){var aa=this;function k(a){return void 0!==a}function l(a){return"string"==typeof a}function ba(a){return"number"==typeof a}function ca(a,b){a=a.split(".");var c=aa;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&k(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ea(a){return"function"==da(a)}function fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ga(a,b,c){return a.call.apply(a.bind,arguments)}
function ia(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ja(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja=ga:ja=ia;return ja.apply(null,arguments)}
function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var la=Date.now||function(){return+new Date};function p(a,b){function c(){}c.prototype=b.prototype;a.ea=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ca=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var ma=window;function q(a,b){this.code=a;this.a=r[a]||na;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}p(q,Error);var na="unknown error",r={15:"element not selectable",11:"element not visible"};r[31]=na;r[30]=na;r[24]="invalid cookie domain";r[29]="invalid element coordinates";r[12]="invalid element state";
r[32]="invalid selector";r[51]="invalid selector";r[52]="invalid selector";r[17]="javascript error";r[405]="unsupported operation";r[34]="move target out of bounds";r[27]="no such alert";r[7]="no such element";r[8]="no such frame";r[23]="no such window";r[28]="script timeout";r[33]="session not created";r[10]="stale element reference";r[21]="timeout";r[25]="unable to set cookie";r[26]="unexpected alert open";r[13]=na;r[9]="unknown command";q.prototype.toString=function(){return this.name+": "+this.message};var oa={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};function pa(a){if(Error.captureStackTrace)Error.captureStackTrace(this,pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}p(pa,Error);pa.prototype.name="CustomError";var qa;function ra(a,b){this.width=a;this.height=b}ra.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};ra.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};ra.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};ra.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
ra.prototype.scale=function(a,b){b=ba(b)?b:a;this.width*=a;this.height*=b;return this};function sa(a,b){var c=ta;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};function ua(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var va=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function wa(a,b){var c=0;a=va(String(a)).split(".");b=va(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;!c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=xa(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||xa(0==f[2].length,0==g[2].length)||xa(f[2],g[2]);f=f[3];g=g[3]}while(!c)}return c}function xa(a,b){return a<b?-1:a>b?1:0}
function ya(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function za(a,b,c){this.a=a;this.b=b||1;this.f=c||1};function Aa(a){this.b=a;this.a=0}function Ba(a){a=a.match(Ca);for(var b=0;b<a.length;b++)Da.test(a[b])&&a.splice(b,1);return new Aa(a)}var Ca=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,Da=/^\s/;function t(a,b){return a.b[a.a+(b||0)]}function u(a){return a.b[a.a++]}function Ea(a){return a.b.length<=a.a};function Fa(a){pa.call(this,a)}p(Fa,pa);var w;a:{var Ga=aa.navigator;if(Ga){var Ha=Ga.userAgent;if(Ha){w=Ha;break a}}w=""}function x(a){return-1!=w.indexOf(a)};function y(a,b){this.h=a;this.c=k(b)?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function Ia(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}y.prototype.a=function(a){return null===this.b||this.b==a.nodeType};y.prototype.f=function(){return this.h};
y.prototype.toString=function(){var a="Kind Test: "+this.h;null===this.c||(a+=z(this.c));return a};function Ja(a,b){this.i=a.toLowerCase();a="*"==this.i?"*":"http://www.w3.org/1999/xhtml";this.c=b?b.toLowerCase():a}Ja.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=k(a.localName)?a.localName:a.nodeName;return"*"!=this.i&&this.i!=b.toLowerCase()?!1:"*"==this.c?!0:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Ja.prototype.f=function(){return this.i};
Ja.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.i};function La(a){switch(a.nodeType){case 1:return ka(Ma,a);case 9:return La(a.documentElement);case 11:case 10:case 6:case 12:return Na;default:return a.parentNode?La(a.parentNode):Na}}function Na(){return null}function Ma(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Ma(a.parentNode,b):null};function Oa(a,b){return(new RegExp(a)).test(b)}function Pa(a,b){return(new RegExp(a,"i")).test(b)}function Qa(a){a=a.replace(/([.^$+(){}\[\]\\|])/g,"\\$1");a=a.replace(/\?/g,"(.|[\r\n])");return a=a.replace(/\*/g,"(.|[\r\n])*")}var Ra={exact:function(a,b){return-1!=b.indexOf(a)},glob:function(a,b){return(new RegExp("^"+Qa(a)+"$")).test(b)},globcontains:function(a,b){return(new RegExp(Qa(a))).test(b)},regex:Oa,regexi:Pa,regexpi:Pa,regexp:Oa};function Sa(a,b){if(l(a))return l(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function A(a,b){for(var c=a.length,d=l(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function Ta(a,b){for(var c=a.length,d=[],e=0,f=l(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d}function Ua(a,b,c){var d=c;A(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}
function Va(a,b){for(var c=a.length,d=l(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function Wa(a,b){for(var c=a.length,d=l(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}function Xa(a,b){a:{for(var c=a.length,d=l(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:l(a)?a.charAt(b):a[b]}function Ya(a){return Array.prototype.concat.apply([],arguments)}
function Za(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function $a(){return x("iPhone")&&!x("iPod")&&!x("iPad")};var ab="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),bb=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,cb=/^#(?:[0-9a-f]{3}){1,2}$/i,db=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,eb=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;var fb={o:function(a,b){if(""===a)throw new q(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},s:function(a,b){if(""===a)throw new q(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};function gb(){return(x("Chrome")||x("CriOS"))&&!x("Edge")};function hb(a,b){this.x=k(a)?a:0;this.y=k(b)?b:0}hb.prototype.toString=function(){return"("+this.x+", "+this.y+")"};hb.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};hb.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};hb.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};hb.prototype.scale=function(a,b){b=ba(b)?b:a;this.x*=a;this.y*=b;return this};var ib=x("Opera"),B=x("Trident")||x("MSIE"),jb=x("Edge"),kb=x("Gecko")&&!(-1!=w.toLowerCase().indexOf("webkit")&&!x("Edge"))&&!(x("Trident")||x("MSIE"))&&!x("Edge"),lb=-1!=w.toLowerCase().indexOf("webkit")&&!x("Edge");function mb(){var a=aa.document;return a?a.documentMode:void 0}var nb;
a:{var ob="",pb=function(){var a=w;if(kb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(jb)return/Edge\/([\d\.]+)/.exec(a);if(B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(lb)return/WebKit\/(\S+)/.exec(a);if(ib)return/(?:Version)[ \/]?(\S+)/.exec(a)}();pb&&(ob=pb?pb[1]:"");if(B){var qb=mb();if(null!=qb&&qb>parseFloat(ob)){nb=String(qb);break a}}nb=ob}var ta={};function rb(a){return sa(a,function(){return 0<=wa(nb,a)})}var sb;var tb=aa.document;
sb=tb&&B?mb()||("CSS1Compat"==tb.compatMode?parseInt(nb,10):5):void 0;function ub(a,b,c,d){this.c=a;this.a=b;this.b=c;this.f=d}ub.prototype.toString=function(){return"("+this.c+"t, "+this.a+"r, "+this.b+"b, "+this.f+"l)"};ub.prototype.ceil=function(){this.c=Math.ceil(this.c);this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.f=Math.ceil(this.f);return this};ub.prototype.floor=function(){this.c=Math.floor(this.c);this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.f=Math.floor(this.f);return this};
ub.prototype.round=function(){this.c=Math.round(this.c);this.a=Math.round(this.a);this.b=Math.round(this.b);this.f=Math.round(this.f);return this};ub.prototype.scale=function(a,b){b=ba(b)?b:a;this.f*=a;this.a*=a;this.c*=b;this.b*=b;return this};var vb=x("Firefox"),wb=$a()||x("iPod"),xb=x("iPad"),yb=x("Android")&&!(gb()||x("Firefox")||x("Opera")||x("Silk")),zb=gb(),Ab=x("Safari")&&!(gb()||x("Coast")||x("Opera")||x("Edge")||x("Silk")||x("Android"))&&!($a()||x("iPad")||x("iPod"));var C=B&&!(9<=Number(sb)),Bb=B&&!(8<=Number(sb));function D(a,b,c,d){this.a=a;this.b=b;this.width=c;this.height=d}D.prototype.toString=function(){return"("+this.a+", "+this.b+" - "+this.width+"w x "+this.height+"h)"};D.prototype.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};D.prototype.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
D.prototype.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};D.prototype.scale=function(a,b){b=ba(b)?b:a;this.a*=a;this.width*=a;this.b*=b;this.height*=b;return this};function Cb(a){return(a=a.exec(w))?a[1]:""}var Db=function(){if(vb)return Cb(/Firefox\/([0-9.]+)/);if(B||jb||ib)return nb;if(zb)return $a()||x("iPad")||x("iPod")?Cb(/CriOS\/([0-9.]+)/):Cb(/Chrome\/([0-9.]+)/);if(Ab&&!($a()||x("iPad")||x("iPod")))return Cb(/Version\/([0-9.]+)/);if(wb||xb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(w);if(a)return a[1]+"."+a[2]}else if(yb)return(a=Cb(/Android\s+([0-9.]+)/))?a:Cb(/Version\/([0-9.]+)/);return""}();function Eb(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Fb(a,b){var c=Bb&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Eb(b,a,b.nodeName,c)};var Gb={},Hb,Ib;function Jb(a){return Kb?Hb(a):B?0<=wa(sb,a):rb(a)}function Lb(a){return Kb?Ib(a):yb?0<=wa(Mb,a):0<=wa(Db,a)}
var Kb=function(){if(!kb)return!1;var a=aa.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;Hb=function(a){return 0<=c.compare(d,""+a)};Ib=function(a){return 0<=c.compare(e,""+a)};return!0}(),Nb;if(yb){var Ob=/Android\s+([0-9\.]+)/.exec(w);Nb=Ob?Ob[1]:"0"}else Nb="0";
var Mb=Nb,Pb=B&&!(8<=Number(sb)),Qb=B&&!(9<=Number(sb));yb&&Lb(2.3);yb&&Lb(4);Ab&&Lb(6);function E(a){return a?new Rb(F(a)):qa||(qa=new Rb)}
function Sb(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){d=a.getElementsByClassName(c);if(e){a={};for(var f=b=0,g;g=d[f];f++)e==g.nodeName&&(a[b++]=g);a.length=b;return a}return d}d=a.getElementsByTagName(e||"*");if(c){a={};for(f=b=0;g=d[f];f++){var e=g.className,h;if(h="function"==typeof e.split)h=0<=Sa(e.split(/\s+/),c);h&&(a[b++]=g)}a.length=b;return a}return d}
function Tb(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function Ub(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Vb(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(B&&!(9<=Number(sb))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Wb(a,b):!c&&Ub(e,b)?-1*Xb(a,b):!d&&Ub(f,a)?Xb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=F(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(aa.Range.START_TO_END,a)}function Xb(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return Wb(b,a)}function Wb(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function F(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var Yb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Zb={IMG:" ",BR:"\n"};
function $b(a,b,c){if(!(a.nodeName in Yb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Zb)b.push(Zb[a.nodeName]);else for(a=a.firstChild;a;)$b(a,b,c),a=a.nextSibling}function ac(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function Rb(a){this.a=a||aa.document||document}Rb.prototype.getElementsByTagName=function(a,b){return(b||this.a).getElementsByTagName(String(a))};
function bc(a,b,c,d){return Sb(a.a,b,c,d)};function H(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(C&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),C&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function cc(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}Bb&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function dc(a,b,c,d,e){return(C?ec:fc).call(null,a,b,l(c)?c:null,l(d)?d:null,e||new I)}
function ec(a,b,c,d,e){if(a instanceof Ja||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;var g=gc(a);if("*"!=g&&(f=b.getElementsByTagName(g),!f))return e;if(c){var h=[];for(a=0;b=f[a++];)cc(b,c,d)&&h.push(b);f=h}for(a=0;b=f[a++];)"*"==g&&"!"==b.tagName||J(e,b);return e}hc(a,b,c,d,e);return e}
function fc(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!B?(b=b.getElementsByName(d),A(b,function(b){a.a(b)&&J(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),A(b,function(b){b.className==d&&a.a(b)&&J(e,b)})):a instanceof y?hc(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),A(b,function(a){cc(a,c,d)&&J(e,a)}));return e}
function ic(a,b,c,d,e){var f;if((a instanceof Ja||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var g=gc(a);if("*"!=g&&(f=Ta(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=Ta(f,function(a){return cc(a,c,d)}));A(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||J(e,a)});return e}return jc(a,b,c,d,e)}function jc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)cc(b,c,d)&&a.a(b)&&J(e,b);return e}
function hc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)cc(b,c,d)&&a.a(b)&&J(e,b),hc(a,b,c,d,e)}function gc(a){if(a instanceof y){if(8==a.b)return"!";if(null===a.b)return"*"}return a.f()};function kc(a,b){b=b.toLowerCase();return"style"==b?lc(a.style.cssText):Pb&&"value"==b&&K(a,"INPUT")?a.value:Qb&&!0===a[b]?String(a.getAttribute(b)):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var mc=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function lc(a){var b=[];A(a.split(mc),function(a){var c=a.indexOf(":");0<c&&(a=[a.slice(0,c),a.slice(c+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function nc(a,b){Pb&&"value"==b&&K(a,"OPTION")&&null===kc(a,"value")?(b=[],$b(a,b,!1),a=b.join("")):a=a[b];return a}function K(a,b){b&&"string"!==typeof b&&(b=b.toString());return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};lb||kb&&Jb(3.5)||B&&Jb(8);var oc={A:function(a){return!(!a.querySelectorAll||!a.querySelector)},o:function(a,b){if(!a)throw new q(32,"No class name specified");a=va(a);if(-1!==a.indexOf(" "))throw new q(32,"Compound class names not permitted");if(oc.A(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new q(32,"An invalid or illegal class name was specified");}a=bc(E(b),"*",a,b);return a.length?a[0]:null},s:function(a,b){if(!a)throw new q(32,"No class name specified");a=va(a);if(-1!==a.indexOf(" "))throw new q(32,
"Compound class names not permitted");if(oc.A(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new q(32,"An invalid or illegal class name was specified");}return bc(E(b),"*",a,b)}};var pc={o:function(a,b){if(!ea(b.querySelector)&&B&&Jb(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new q(32,"No selector specified");a=va(a);try{var c=b.querySelector(a)}catch(d){throw new q(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},s:function(a,b){if(!ea(b.querySelectorAll)&&B&&Jb(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new q(32,"No selector specified");a=va(a);try{return b.querySelectorAll(a)}catch(c){throw new q(32,
"An invalid or illegal selector was specified");}}};function I(){this.b=this.a=null;this.l=0}function qc(a){this.node=a;this.a=this.b=null}function rc(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;){e=c.node;var g=b.node;e==g||e instanceof Eb&&g instanceof Eb&&e.a==g.a?(e=c,c=c.a,b=b.a):0<Vb(c.node,b.node)?(e=b,b=b.a):(e=c,c=c.a);(e.b=d)?d.a=e:a.a=e;d=e;f++}for(e=c||b;e;)e.b=d,d=d.a=e,f++,e=e.a;a.b=d;a.l=f;return a}function sc(a,b){b=new qc(b);b.a=a.a;a.b?a.a.b=b:a.a=a.b=b;a.a=b;a.l++}
function J(a,b){b=new qc(b);b.b=a.b;a.a?a.b.a=b:a.a=a.b=b;a.b=b;a.l++}function tc(a){return(a=a.a)?a.node:null}I.prototype.f=function(){var a=tc(this);return a?H(a):""};function uc(a,b){return new vc(a,!!b)}function vc(a,b){this.f=a;this.b=(this.v=b)?a.b:a.a;this.a=null}function L(a){var b=a.b;if(b){var c=a.a=b;a.b=a.v?b.b:b.a;return c.node}return null};B&&Jb(10);yb&&Lb(4);function wc(a,b,c){this.a=a;this.b=b;this.f=c}wc.prototype.create=function(a){a=F(a);Qb&&a.createEventObject?a=a.createEventObject():(a=a.createEvent("HTMLEvents"),a.initEvent(this.a,this.b,this.f));return a};wc.prototype.toString=function(){return this.a};var xc=new wc("change",!0,!1),yc=new wc("focus",!1,!1),zc=new wc("select",!0,!1);function Ac(a,b){var c=b.create(a,void 0);"isTrusted"in c||(c.isTrusted=!1);Qb&&a.fireEvent?a.fireEvent("on"+b.a,c):a.dispatchEvent(c)};function M(a){this.j=a;this.b=this.g=!1;this.f=null}function z(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Bc(a,b){a.g=b}function Cc(a,b){a.b=b}function N(a,b){a=a.a(b);return a instanceof I?+a.f():+a}function O(a,b){a=a.a(b);return a instanceof I?a.f():""+a}function Dc(a,b){a=a.a(b);return a instanceof I?!!a.l:!!a};var Ec="function"===typeof ShadowRoot;
function Fc(a,b){if(a.style&&("hidden"==a.style.visibility||"none"==a.style.display))return"";if(3==a.nodeType){var c=a.data;b||(c=c.replace(/\n|\r|\t/g," "));return c.replace(/&nbsp/," ")}if(Ec&&1==a.nodeType&&null!==a.shadowRoot)return Fc(a.shadowRoot,b);if((1==a.nodeType||11==a.nodeType)&&"SCRIPT"!=a.nodeName&&"STYLE"!=a.nodeName){var d=b||"PRE"==a.tagName;c="";for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes.item(e);if(f)if(!Ec||"CONTENT"!=f.nodeName&&"SLOT"!=f.nodeName)c+=Fc(f,d);else for(var f=
"CONTENT"==f.nodeName?f.getDistributedNodes():f.assignedNodes(),g=0;g<f.length;g++){var h=f[g];h&&(c+=Fc(h,b))}}if("P"==a.tagName||"BR"==a.tagName||"HR"==a.tagName||"DIV"==a.tagName)c+="\n";c=c.replace(/&nbsp/," ");Gb.ba&&Lb(9)&&(c=c.replace(/&#100;/," "));return c}return""};function Gc(a,b,c){M.call(this,a.j);this.c=a;this.h=b;this.u=c;this.g=b.g||c.g;this.b=b.b||c.b;this.c==Hc&&(c.b||c.g||4==c.j||0==c.j||!b.f?b.b||b.g||4==b.j||0==b.j||!c.f||(this.f={name:c.f.name,w:b}):this.f={name:b.f.name,w:c})}p(Gc,M);
function Ic(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof I&&c instanceof I){b=uc(b);for(d=L(b);d;d=L(b))for(e=uc(c),f=L(e);f;f=L(e))if(a(H(d),H(f)))return!0;return!1}if(b instanceof I||c instanceof I){b instanceof I?(e=b,d=c):(e=c,d=b);f=uc(e);for(var g=typeof d,h=L(f);h;h=L(f)){switch(g){case "number":h=+H(h);break;case "boolean":h=!!H(h);break;case "string":h=H(h);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(h,d)||e==c&&a(d,h))return!0}return!1}return e?
"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Gc.prototype.a=function(a){return this.c.m(this.h,this.u,a)};Gc.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+z(this.h);return a+=z(this.u)};function Jc(a,b,c,d){this.Z=a;this.N=b;this.j=c;this.m=d}Jc.prototype.toString=function(){return this.Z};var Kc={};
function P(a,b,c,d){if(Kc.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new Jc(a,b,c,d);return Kc[a.toString()]=a}P("div",6,1,function(a,b,c){return N(a,c)/N(b,c)});P("mod",6,1,function(a,b,c){return N(a,c)%N(b,c)});P("*",6,1,function(a,b,c){return N(a,c)*N(b,c)});P("+",5,1,function(a,b,c){return N(a,c)+N(b,c)});P("-",5,1,function(a,b,c){return N(a,c)-N(b,c)});P("<",4,2,function(a,b,c){return Ic(function(a,b){return a<b},a,b,c)});
P(">",4,2,function(a,b,c){return Ic(function(a,b){return a>b},a,b,c)});P("<=",4,2,function(a,b,c){return Ic(function(a,b){return a<=b},a,b,c)});P(">=",4,2,function(a,b,c){return Ic(function(a,b){return a>=b},a,b,c)});var Hc=P("=",3,2,function(a,b,c){return Ic(function(a,b){return a==b},a,b,c,!0)});P("!=",3,2,function(a,b,c){return Ic(function(a,b){return a!=b},a,b,c,!0)});P("and",2,2,function(a,b,c){return Dc(a,c)&&Dc(b,c)});P("or",1,2,function(a,b,c){return Dc(a,c)||Dc(b,c)});function Lc(a,b){if(b.a.length&&4!=a.j)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");M.call(this,a.j);this.c=a;this.h=b;this.g=a.g;this.b=a.b}p(Lc,M);Lc.prototype.a=function(a){a=this.c.a(a);return Mc(this.h,a)};Lc.prototype.toString=function(){var a="Filter:"+z(this.c);return a+=z(this.h)};function Nc(a,b){if(b.length<a.L)throw Error("Function "+a.i+" expects at least"+a.L+" arguments, "+b.length+" given");if(null!==a.D&&b.length>a.D)throw Error("Function "+a.i+" expects at most "+a.D+" arguments, "+b.length+" given");a.Y&&A(b,function(b,d){if(4!=b.j)throw Error("Argument "+d+" to function "+a.i+" is not of type Nodeset: "+b);});M.call(this,a.j);this.B=a;this.c=b;Bc(this,a.g||Va(b,function(a){return a.g}));Cc(this,a.X&&!b.length||a.W&&!!b.length||Va(b,function(a){return a.b}))}
p(Nc,M);Nc.prototype.a=function(a){return this.B.m.apply(null,Ya(a,this.c))};Nc.prototype.toString=function(){var a="Function: "+this.B;if(this.c.length)var b=Ua(this.c,function(a,b){return a+z(b)},"Arguments:"),a=a+z(b);return a};function Oc(a,b,c,d,e,f,g,h,m){this.i=a;this.j=b;this.g=c;this.X=d;this.W=e;this.m=f;this.L=g;this.D=k(h)?h:g;this.Y=!!m}Oc.prototype.toString=function(){return this.i};var Pc={};
function Q(a,b,c,d,e,f,g,h){if(Pc.hasOwnProperty(a))throw Error("Function already created: "+a+".");Pc[a]=new Oc(a,b,c,d,!1,e,f,g,h)}Q("boolean",2,!1,!1,function(a,b){return Dc(b,a)},1);Q("ceiling",1,!1,!1,function(a,b){return Math.ceil(N(b,a))},1);Q("concat",3,!1,!1,function(a,b){return Ua(Za(arguments,1),function(b,d){return b+O(d,a)},"")},2,null);Q("contains",2,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);return-1!=b.indexOf(a)},2);Q("count",1,!1,!1,function(a,b){return b.a(a).l},1,1,!0);
Q("false",2,!1,!1,function(){return!1},0);Q("floor",1,!1,!1,function(a,b){return Math.floor(N(b,a))},1);Q("id",4,!1,!1,function(a,b){function c(a){if(C){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return Xa(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument;a=O(b,a).split(/\s+/);var f=[];A(a,function(a){a=c(a);!a||0<=Sa(f,a)||f.push(a)});f.sort(Vb);var g=new I;A(f,function(a){J(g,a)});return g},1);
Q("lang",2,!1,!1,function(){return!1},1);Q("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);Q("local-name",3,!1,!0,function(a,b){return(a=b?tc(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);Q("name",3,!1,!0,function(a,b){return(a=b?tc(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);Q("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
Q("normalize-space",3,!1,!0,function(a,b){return(b?O(b,a):H(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);Q("not",2,!1,!1,function(a,b){return!Dc(b,a)},1);Q("number",1,!1,!0,function(a,b){return b?N(b,a):+H(a.a)},0,1);Q("position",1,!0,!1,function(a){return a.b},0);Q("round",1,!1,!1,function(a,b){return Math.round(N(b,a))},1);Q("starts-with",2,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);return!b.lastIndexOf(a,0)},2);Q("string",3,!1,!0,function(a,b){return b?O(b,a):H(a.a)},0,1);
Q("string-length",1,!1,!0,function(a,b){return(b?O(b,a):H(a.a)).length},0,1);Q("substring",3,!1,!1,function(a,b,c,d){c=N(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?N(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=O(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);Q("substring-after",3,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
Q("substring-before",3,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);Q("sum",1,!1,!1,function(a,b){a=uc(b.a(a));b=0;for(var c=L(a);c;c=L(a))b+=+H(c);return b},1,1,!0);Q("translate",3,!1,!1,function(a,b,c,d){b=O(b,a);c=O(c,a);var e=O(d,a);d={};for(var f=0;f<c.length;f++)a=c.charAt(f),a in d||(d[a]=e.charAt(f));c="";for(f=0;f<b.length;f++)a=b.charAt(f),c+=a in d?d[a]:a;return c},3);Q("true",2,!1,!1,function(){return!0},0);function Qc(a){M.call(this,3);this.c=a.substring(1,a.length-1)}p(Qc,M);Qc.prototype.a=function(){return this.c};Qc.prototype.toString=function(){return"Literal: "+this.c};function Rc(a){M.call(this,1);this.c=a}p(Rc,M);Rc.prototype.a=function(){return this.c};Rc.prototype.toString=function(){return"Number: "+this.c};function Sc(a,b){M.call(this,a.j);this.h=a;this.c=b;this.g=a.g;this.b=a.b;1==this.c.length&&(a=this.c[0],a.C||a.c!=Tc||(a=a.u,"*"!=a.f()&&(this.f={name:a.f(),w:null})))}p(Sc,M);function Uc(){M.call(this,4)}p(Uc,M);Uc.prototype.a=function(a){var b=new I;a=a.a;9==a.nodeType?J(b,a):J(b,a.ownerDocument);return b};Uc.prototype.toString=function(){return"Root Helper Expression"};function Vc(){M.call(this,4)}p(Vc,M);Vc.prototype.a=function(a){var b=new I;J(b,a.a);return b};Vc.prototype.toString=function(){return"Context Helper Expression"};
function Wc(a){return"/"==a||"//"==a}Sc.prototype.a=function(a){var b=this.h.a(a);if(!(b instanceof I))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.l;c++){var e=a[c],f=uc(b,e.c.v);if(e.g||e.c!=Xc)if(e.g||e.c!=Yc){var g=L(f);for(b=e.a(new za(g));g=L(f);)g=e.a(new za(g)),b=rc(b,g)}else g=L(f),b=e.a(new za(g));else{for(g=L(f);(b=L(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new za(g))}}return b};
Sc.prototype.toString=function(){var a="Path Expression:"+z(this.h);if(this.c.length){var b=Ua(this.c,function(a,b){return a+z(b)},"Steps:");a+=z(b)}return a};function Zc(a,b){this.a=a;this.v=!!b}
function Mc(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=uc(b),f=b.l,g,h=0;g=L(e);h++){var m=a.v?f-h:h+1;g=d.a(new za(g,m,f));if("number"==typeof g)m=m==g;else if("string"==typeof g||"boolean"==typeof g)m=!!g;else if(g instanceof I)m=0<g.l;else throw Error("Predicate.evaluate returned an unexpected type.");if(!m){m=e;g=m.f;var v=m.a;if(!v)throw Error("Next must be called at least once before remove.");var n=v.b,v=v.a;n?n.a=v:g.a=v;v?v.b=n:g.b=n;g.l--;m.a=null}}return b}
Zc.prototype.toString=function(){return Ua(this.a,function(a,b){return a+z(b)},"Predicates:")};function $c(a){M.call(this,1);this.c=a;this.g=a.g;this.b=a.b}p($c,M);$c.prototype.a=function(a){return-N(this.c,a)};$c.prototype.toString=function(){return"Unary Expression: -"+z(this.c)};function ad(a){M.call(this,4);this.c=a;Bc(this,Va(this.c,function(a){return a.g}));Cc(this,Va(this.c,function(a){return a.b}))}p(ad,M);ad.prototype.a=function(a){var b=new I;A(this.c,function(c){c=c.a(a);if(!(c instanceof I))throw Error("Path expression must evaluate to NodeSet.");b=rc(b,c)});return b};ad.prototype.toString=function(){return Ua(this.c,function(a,b){return a+z(b)},"Union Expression:")};function bd(a,b,c,d){M.call(this,4);this.c=a;this.u=b;this.h=c||new Zc([]);this.C=!!d;b=this.h;b=0<b.a.length?b.a[0].f:null;a.aa&&b&&(a=b.name,a=C?a.toLowerCase():a,this.f={name:a,w:b.w});a:{a=this.h;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.g||1==c.j||0==c.j){a=!0;break a}a=!1}this.g=a}p(bd,M);
bd.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.w?O(c.w,a):null,f=1);if(this.C)if(this.g||this.c!=cd)if(b=uc((new bd(dd,new y("node"))).a(a)),c=L(b))for(a=this.m(c,d,e,f);c=L(b);)a=rc(a,this.m(c,d,e,f));else a=new I;else a=dc(this.u,b,d,e),a=Mc(this.h,a,f);else a=this.m(a.a,d,e,f);return a};bd.prototype.m=function(a,b,c,d){a=this.c.B(this.u,a,b,c);return a=Mc(this.h,a,d)};
bd.prototype.toString=function(){var a="Step:"+z("Operator: "+(this.C?"//":"/"));this.c.i&&(a+=z("Axis: "+this.c));a+=z(this.u);if(this.h.a.length){var b=Ua(this.h.a,function(a,b){return a+z(b)},"Predicates:");a+=z(b)}return a};function ed(a,b,c,d){this.i=a;this.B=b;this.v=c;this.aa=d}ed.prototype.toString=function(){return this.i};var fd={};function R(a,b,c,d){if(fd.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new ed(a,b,c,!!d);return fd[a]=b}
R("ancestor",function(a,b){for(var c=new I;b=b.parentNode;)a.a(b)&&sc(c,b);return c},!0);R("ancestor-or-self",function(a,b){var c=new I;do a.a(b)&&sc(c,b);while(b=b.parentNode);return c},!0);
var Tc=R("attribute",function(a,b){var c=new I,d=a.f();if("style"==d&&C&&b.style)return J(c,new Eb(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof y&&null===a.b||"*"==d)for(d=0;a=e[d];d++)C?a.nodeValue&&J(c,Fb(b,a)):J(c,a);else(a=e.getNamedItem(d))&&(C?a.nodeValue&&J(c,Fb(b,a)):J(c,a));return c},!1),cd=R("child",function(a,b,c,d,e){return(C?ic:jc).call(null,a,b,l(c)?c:null,l(d)?d:null,e||new I)},!1,!0);R("descendant",dc,!1,!0);
var dd=R("descendant-or-self",function(a,b,c,d){var e=new I;cc(b,c,d)&&a.a(b)&&J(e,b);return dc(a,b,c,d,e)},!1,!0),Xc=R("following",function(a,b,c,d){var e=new I;do for(var f=b;f=f.nextSibling;)cc(f,c,d)&&a.a(f)&&J(e,f),e=dc(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);R("following-sibling",function(a,b){for(var c=new I;b=b.nextSibling;)a.a(b)&&J(c,b);return c},!1);R("namespace",function(){return new I},!1);
var gd=R("parent",function(a,b){var c=new I;if(9==b.nodeType)return c;if(2==b.nodeType)return J(c,b.ownerElement),c;b=b.parentNode;a.a(b)&&J(c,b);return c},!1),Yc=R("preceding",function(a,b,c,d){var e=new I,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,h=f.length;g<h;g++){var m=[];for(b=f[g];b=b.previousSibling;)m.unshift(b);for(var v=0,n=m.length;v<n;v++)b=m[v],cc(b,c,d)&&a.a(b)&&J(e,b),e=dc(a,b,c,d,e)}return e},!0,!0);
R("preceding-sibling",function(a,b){for(var c=new I;b=b.previousSibling;)a.a(b)&&sc(c,b);return c},!0);var hd=R("self",function(a,b){var c=new I;a.a(b)&&J(c,b);return c},!1);function id(a,b){this.a=a;this.b=b}function jd(a){for(var b,c=[];;){T(a,"Missing right hand side of binary expression.");b=kd(a);var d=u(a.a);if(!d)break;var e=(d=Kc[d]||null)&&d.N;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].N;)b=new Gc(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Gc(c.pop(),c.pop(),b);return b}function T(a,b){if(Ea(a.a))throw Error(b);}function ld(a,b){a=u(a.a);if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function md(a){a=u(a.a);if(")"!=a)throw Error("Bad token: "+a);}function nd(a){a=u(a.a);if(2>a.length)throw Error("Unclosed literal string");return new Qc(a)}
function od(a){var b=[];if(Wc(t(a.a))){var c=u(a.a);var d=t(a.a);if("/"==c&&(Ea(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new Uc;d=new Uc;T(a,"Missing next location step.");c=pd(a,c);b.push(c)}else{a:{c=t(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":u(a.a);c=jd(a);T(a,'unclosed "("');ld(a,")");break;case '"':case "'":c=nd(a);break;default:if(isNaN(+c))if(!Ia(c)&&/(?![0-9])[\w]/.test(d)&&"("==t(a.a,1)){c=u(a.a);
c=Pc[c]||null;u(a.a);for(d=[];")"!=t(a.a);){T(a,"Missing function argument list.");d.push(jd(a));if(","!=t(a.a))break;u(a.a)}T(a,"Unclosed function argument list.");md(a);c=new Nc(c,d)}else{c=null;break a}else c=new Rc(+u(a.a))}"["==t(a.a)&&(d=new Zc(qd(a)),c=new Lc(c,d))}if(c)if(Wc(t(a.a)))d=c;else return c;else c=pd(a,"/"),d=new Vc,b.push(c)}for(;Wc(t(a.a));)c=u(a.a),T(a,"Missing next location step."),c=pd(a,c),b.push(c);return new Sc(d,b)}
function pd(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==t(a.a)){var c=new bd(hd,new y("node"));u(a.a);return c}if(".."==t(a.a))return c=new bd(gd,new y("node")),u(a.a),c;if("@"==t(a.a)){var d=Tc;u(a.a);T(a,"Missing attribute name")}else if("::"==t(a.a,1)){if(!/(?![0-9])[\w]/.test(t(a.a).charAt(0)))throw Error("Bad token: "+u(a.a));var e=u(a.a);d=fd[e]||null;if(!d)throw Error("No axis with name: "+e);u(a.a);T(a,"Missing node name")}else d=cd;e=t(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==
t(a.a,1)){if(!Ia(e))throw Error("Invalid node type: "+e);e=u(a.a);if(!Ia(e))throw Error("Invalid type name: "+e);ld(a,"(");T(a,"Bad nodetype");var f=t(a.a).charAt(0),g=null;if('"'==f||"'"==f)g=nd(a);T(a,"Bad nodetype");md(a);e=new y(e,g)}else if(e=u(a.a),f=e.indexOf(":"),-1==f)e=new Ja(e);else{var g=e.substring(0,f);if("*"==g)var h="*";else if(h=a.b(g),!h)throw Error("Namespace prefix not declared: "+g);e=e.substr(f+1);e=new Ja(e,h)}else throw Error("Bad token: "+u(a.a));a=new Zc(qd(a),d.v);return c||
new bd(d,e,a,"//"==b)}function qd(a){for(var b=[];"["==t(a.a);){u(a.a);T(a,"Missing predicate expression.");var c=jd(a);b.push(c);T(a,"Unclosed predicate expression.");ld(a,"]")}return b}function kd(a){if("-"==t(a.a))return u(a.a),new $c(kd(a));var b=od(a);if("|"!=t(a.a))a=b;else{for(b=[b];"|"==u(a.a);)T(a,"Missing next union location path."),b.push(od(a));a.a.a--;a=new ad(b)}return a};function rd(a,b){if(!a.length)throw Error("Empty XPath expression.");a=Ba(a);if(Ea(a))throw Error("Invalid XPath expression.");b?ea(b)||(b=ja(b.lookupNamespaceURI,b)):b=function(){return null};var c=jd(new id(a,b));if(!Ea(a))throw Error("Bad token: "+u(a));this.evaluate=function(a,b){a=c.a(new za(a));return new U(a,b)}}
function U(a,b){if(!b)if(a instanceof I)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof I))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof I?a.f():""+a;break;case 1:this.numberValue=a instanceof I?+a.f():+a;break;case 3:this.booleanValue=a instanceof I?0<a.l:!!a;break;case 4:case 5:case 6:case 7:var c=
uc(a);var d=[];for(var e=L(c);e;e=L(c))d.push(e instanceof Eb?e.a:e);this.snapshotLength=a.l;this.invalidIteratorState=!1;break;case 8:case 9:a=tc(a);this.singleNodeValue=a instanceof Eb?a.a:a;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=d.length||
0>a?null:d[a]}}U.ANY_TYPE=0;U.NUMBER_TYPE=1;U.STRING_TYPE=2;U.BOOLEAN_TYPE=3;U.UNORDERED_NODE_ITERATOR_TYPE=4;U.ORDERED_NODE_ITERATOR_TYPE=5;U.UNORDERED_NODE_SNAPSHOT_TYPE=6;U.ORDERED_NODE_SNAPSHOT_TYPE=7;U.ANY_UNORDERED_NODE_TYPE=8;U.FIRST_ORDERED_NODE_TYPE=9;function sd(a){this.lookupNamespaceURI=La(a)}
function td(a,b){a=a||aa;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=U,c.evaluate=function(a,b,c,g){return(new rd(a,c)).evaluate(b,g)},c.createExpression=function(a,b){return new rd(a,b)},c.createNSResolver=function(a){return new sd(a)}}ca("wgxpath.install",td);var V={};V.F=function(){var a={fa:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
V.m=function(a,b,c){var d=F(a);if(!d.documentElement)return null;(B||yb)&&td(d?d.parentWindow||d.defaultView:window);try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):V.F;if(B&&!rb(7))return d.evaluate.call(d,b,a,e,c,null);if(!B||9<=Number(sb)){for(var f={},g=d.getElementsByTagName("*"),h=0;h<g.length;++h){var m=g[h],v=m.namespaceURI;if(v&&!f[v]){var n=m.lookupPrefix(v);if(!n)var G=v.match(".*/(\\w+)/?$"),n=G?G[1]:"xhtml";f[v]=n}}var S={},ha;for(ha in f)S[f[ha]]=ha;e=function(a){return S[a]||
null}}try{return d.evaluate(b,a,e,c,null)}catch(Ka){if("TypeError"===Ka.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):V.F,d.evaluate(b,a,e,c,null);throw Ka;}}catch(Ka){if(!kb||"NS_ERROR_ILLEGAL_VALUE"!=Ka.name)throw new q(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+Ka);}};V.G=function(a,b){if(!a||1!=a.nodeType)throw new q(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
V.o=function(a,b){var c=function(){var c=V.m(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=F(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||V.G(c,a);return c};
V.s=function(a,b){var c=function(){var c=V.m(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=F(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();A(c,function(b){V.G(b,a)});return c};var ud="function"===typeof ShadowRoot;function vd(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return K(a)?a:null}
function W(a,b){b=ya(b);if("float"==b||"cssFloat"==b||"styleFloat"==b)b=Qb?"styleFloat":"cssFloat";a:{var c=b;var d=F(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||wd(a,b);if(null===a)a=null;else if(0<=Sa(ab,b)){b:{var e=a.match(db);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),e=Number(e[4]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d&&0<=e&&1>=e)){b=[b,c,d,e];break b}b=null}if(!b)b:{if(d=a.match(eb))if(b=
Number(d[1]),c=Number(d[2]),d=Number(d[3]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=oa[b.toLowerCase()];if(!c&&(c="#"==b.charAt(0)?b:"#"+b,4==c.length&&(c=c.replace(bb,"#$1$1$2$2$3$3")),!cb.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}
function wd(a,b){var c=a.currentStyle||a.style,d=c[b];!k(d)&&ea(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?k(d)?d:null:(a=vd(a))?wd(a,b):null}
function xd(a,b,c){function d(a){var b=yd(a);return 0<b.height&&0<b.width?!0:K(a,"PATH")&&(0<b.height||0<b.width)?(a=W(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=W(a,"overflow")&&Va(a.childNodes,function(a){return 3==a.nodeType||K(a)&&d(a)})}function e(a){return zd(a)==X&&Wa(a.childNodes,function(a){return!K(a)||e(a)||!d(a)})}if(!K(a))throw Error("Argument to isShown must be of type Element");if(K(a,"BODY"))return!0;if(K(a,"OPTION")||K(a,"OPTGROUP"))return a=ac(a,function(a){return K(a,"SELECT")}),
!!a&&xd(a,!0,c);var f=Ad(a);if(f)return!!f.J&&0<f.rect.width&&0<f.rect.height&&xd(f.J,b,c);if(K(a,"INPUT")&&"hidden"==a.type.toLowerCase()||K(a,"NOSCRIPT"))return!1;f=W(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||Bd(a))&&d(a)?!e(a):!1}
function Cd(a){function b(a){if(K(a)&&"none"==W(a,"display"))return!1;var c;(c=a.parentNode)&&c.shadowRoot&&void 0!==a.assignedSlot?c=a.assignedSlot?a.assignedSlot.parentNode:null:a.getDestinationInsertionPoints&&(a=a.getDestinationInsertionPoints(),0<a.length&&(c=a[a.length-1]));if(ud&&c instanceof ShadowRoot){if(c.host.shadowRoot!==c)return!1;c=c.host}return!c||9!=c.nodeType&&11!=c.nodeType?c&&b(c):!0}return xd(a,!1,b)}var X="hidden";
function zd(a){function b(a){function b(a){return a==g?!0:!W(a,"display").lastIndexOf("inline",0)||"absolute"==c&&"static"==W(a,"position")?!1:!0}var c=W(a,"position");if("fixed"==c)return v=!0,a==g?null:g;for(a=vd(a);a&&!b(a);)a=vd(a);return a}function c(a){var b=a;if("visible"==m)if(a==g&&h)b=h;else if(a==h)return{x:"visible",y:"visible"};b={x:W(b,"overflow-x"),y:W(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new Rb(f)).a;
a=b.scrollingElement?b.scrollingElement:lb||"CSS1Compat"!=b.compatMode?b.body||b.documentElement:b.documentElement;b=b.parentWindow||b.defaultView;a=B&&rb("10")&&b.pageYOffset!=a.scrollTop?new hb(a.scrollLeft,a.scrollTop):new hb(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new hb(a.scrollLeft,a.scrollTop);return a}var e=Dd(a);var f=F(a),g=f.documentElement,h=f.body,m=W(g,"overflow"),v;for(a=b(a);a;a=b(a)){var n=c(a);if("visible"!=n.x||"visible"!=n.y){var G=yd(a);if(!G.width||!G.height)return X;
var S=e.a<G.a,ha=e.b<G.b;if(S&&"hidden"==n.x||ha&&"hidden"==n.y)return X;if(S&&"visible"!=n.x||ha&&"visible"!=n.y){S=d(a);ha=e.b<G.b-S.y;if(e.a<G.a-S.x&&"visible"!=n.x||ha&&"visible"!=n.x)return X;e=zd(a);return e==X?X:"scroll"}S=e.f>=G.a+G.width;G=e.c>=G.b+G.height;if(S&&"hidden"==n.x||G&&"hidden"==n.y)return X;if(S&&"visible"!=n.x||G&&"visible"!=n.y){if(v&&(n=d(a),e.f>=g.scrollWidth-n.x||e.a>=g.scrollHeight-n.y))return X;e=zd(a);return e==X?X:"scroll"}}}return"none"}
function yd(a){var b=Ad(a);if(b)return b.rect;if(K(a,"HTML"))return a=F(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new ra(a.clientWidth,a.clientHeight),new D(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new D(0,0,0,0)}b=new D(c.left,c.top,c.right-c.left,c.bottom-c.top);B&&a.ownerDocument.body&&(a=F(a),b.a-=a.documentElement.clientLeft+a.body.clientLeft,b.b-=a.documentElement.clientTop+a.body.clientTop);
return b}function Ad(a){var b=K(a,"MAP");if(!b&&!K(a,"AREA"))return null;var c=b?a:K(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=V.o('/descendant::*[@usemap = "#'+c.name+'"]',F(c)))&&(e=yd(d),b||"default"==a.shape.toLowerCase()||(a=Ed(a),b=Math.min(Math.max(a.a,0),e.width),c=Math.min(Math.max(a.b,0),e.height),e=new D(b+e.a,c+e.b,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{J:d,rect:e||new D(0,0,0,0)}}
function Ed(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new D(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new D(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new D(b,c,d-b,e-c)}return new D(0,0,0,0)}function Dd(a){a=yd(a);return new ub(a.b,a.a+a.width,a.b+a.height,a.a)}
function Fd(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function Gd(a){var b=[];ud?Hd(a,b):Id(a,b);var c=b;a=c.length;for(var b=Array(a),c=l(c)?c.split(""):c,d=0;d<a;d++)d in c&&(b[d]=Fd.call(void 0,c[d]));return Fd(b.join("\n")).replace(/\xa0/g," ")}
function Jd(a,b,c){if(K(a,"BR"))b.push("");else{var d=K(a,"TD"),e=W(a,"display"),f=!d&&!(0<=Sa(Kd,e)),g=k(a.previousElementSibling)?a.previousElementSibling:Tb(a.previousSibling),g=g?W(g,"display"):"",h=W(a,"float")||W(a,"cssFloat")||W(a,"styleFloat");!f||"run-in"==g&&"none"==h||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var m=Cd(a),v=null,n=null;m&&(v=W(a,"white-space"),n=W(a,"text-transform"));A(a.childNodes,function(a){c(a,b,m,v,n)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||ua(a," ")||
(b[b.length-1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function Id(a,b){Jd(a,b,function(a,b,e,f,g){3==a.nodeType&&e?Ld(a,b,f,g):K(a)&&Id(a,b)})}var Kd="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function Ld(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";ua(c," ")&&!a.lastIndexOf(" ",0)&&(a=a.substr(1));b.push(c+a)}
function Bd(a){if(Qb){if("relative"==W(a,"position"))return 1;a=W(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return Md(a)}function Md(a){var b=1,c=W(a,"opacity");c&&(b=Number(c));(a=vd(a))&&(b*=Md(a));return b}
function Nd(a,b,c,d,e){var f;if(3==a.nodeType&&c)Ld(a,b,d,e);else if(K(a))if(K(a,"CONTENT")||K(a,"SLOT")){for(f=a;f.parentNode;)f=f.parentNode;f instanceof ShadowRoot?(a=K(a,"CONTENT")?a.getDistributedNodes():a.assignedNodes(),A(a,function(a){Nd(a,b,c,d,e)})):Hd(a,b)}else if(K(a,"SHADOW")){for(f=a;f.parentNode;)f=f.parentNode;if(f instanceof ShadowRoot&&(a=f))for(a=a.olderShadowRoot;a;)A(a.childNodes,function(a){Nd(a,b,c,d,e)}),a=a.olderShadowRoot}else Hd(a,b)}
function Hd(a,b){a.shadowRoot&&A(a.shadowRoot.childNodes,function(a){Nd(a,b,!0,null,null)});Jd(a,b,function(a,b,e,f,g){var c=null;1==a.nodeType?c=a:3==a.nodeType&&(c=a);c&&(c.assignedSlot||c.getDestinationInsertionPoints&&0<c.getDestinationInsertionPoints().length)||Nd(a,b,e,f,g)})};var Od={A:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},o:function(a,b){var c=E(b),d=l(a)?c.a.getElementById(a):a;return d?kc(d,"id")==a&&b!=d&&Ub(b,d)?d:Xa(bc(c,"*"),function(c){return kc(c,"id")==a&&b!=c&&Ub(b,c)}):null},s:function(a,b){if(!a)return[];if(Od.A(b,a))try{return b.querySelectorAll("#"+Od.T(a))}catch(c){return[]}b=bc(E(b),"*",null,b);return Ta(b,function(b){return kc(b,"id")==a})},T:function(a){return a.replace(/([\s'"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var Y={},Pd={};Y.O=function(a,b,c){try{var d=pc.s("a",b)}catch(e){d=bc(E(b),"A",null,b)}return Xa(d,function(b){b=Gd(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};Y.K=function(a,b,c){try{var d=pc.s("a",b)}catch(e){d=bc(E(b),"A",null,b)}return Ta(d,function(b){b=Gd(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};Y.o=function(a,b){return Y.O(a,b,!1)};Y.s=function(a,b){return Y.K(a,b,!1)};Pd.o=function(a,b){return Y.O(a,b,!0)};
Pd.s=function(a,b){return Y.K(a,b,!0)};var Qd={index:function(a,b){var c=Number(a);if(isNaN(c)||0>c)throw new Fa("Illegal Index: "+a);if(b.length<=c)throw new Fa("Index out of range: "+a);return[b[c]]},name:function(a,b){return Ta(b,function(b){return nc(b,"name")==a})},value:function(a,b){return Ta(b,function(b){return nc(b,"value")===a})}};var Rd={className:oc,"class name":oc,css:pc,"css selector":pc,id:Od,linkText:Y,"link text":Y,name:{o:function(a,b){b=bc(E(b),"*",null,b);return Xa(b,function(b){return kc(b,"name")==a})},s:function(a,b){b=bc(E(b),"*",null,b);return Ta(b,function(b){return kc(b,"name")==a})}},partialLinkText:Pd,"partial link text":Pd,tagName:fb,"tag name":fb,xpath:V};
function Sd(a,b){a:{for(c in a)if(a.hasOwnProperty(c))break a;var c=null}if(c){var d=Rd[c];if(d&&ea(d.o))return d.o(a[c],b||ma.document)}throw Error("Unsupported locator strategy: "+c);};var Z={V:function(a,b){return a.lastIndexOf("//",0)?a.lastIndexOf("document.",0)?Z.I(a,b):Z.H(a,b):Z.P(a,b)},R:function(a,b){return Td(b||F(ma),function(b){return b.alt==a})},S:function(a,b){return Td(b||F(ma),function(b){return b.className==a})},H:function(a){var b=null;try{b=eval(a)}catch(c){return null}return b?b:null},U:function(a,b){return Sd({id:a},b)},I:function(a,b){return Z.id(a,b)||Z.name(a,b)},i:function(a,b){b=b||F(ma);E(b);b=Sb(document,"*",null,b);a=a.split(" ");for(a[0]="name="+a[0];a.length;){var c=
a.shift(),d=b;b="value";var e=c.match(/^([A-Za-z]+)=(.+)/);e&&(b=e[1].toLowerCase(),c=e[2]);e=Qd[b];if(!e)throw new Fa("Unrecognised element-filter type: '"+b+"'");b=e(c,d)}return 0<b.length?b[0]:null},$:function(a,b){try{a:{a=decodeURIComponent(a);b=b||document;var c=b||document,d=c.$wdc_;d||(d=c.$wdc_={},d.M=la());d.M||(d.M=la());var e=d;if(!(null!==e&&a in e))throw new q(10,"Element does not exist in cache");var f=e[a];if(null!==f&&"setInterval"in f){if(f.closed)throw delete e[a],new q(23,"Window has been closed.");
var g=f}else{for(d=f;d;){if(d==b.documentElement){g=f;break a}d=d.parentNode}delete e[a];throw new q(10,"Element is no longer attached to the DOM");}}return g}catch(h){return null}},P:function(a,b){var c=ua(a,"/"),d={xpath:a};try{var e=Sd(d,b);if(e||!c)return e}catch(f){if(!c)throw f;}d={xpath:a.substring(0,a.length-1)};return Sd(d,b)}};Z.alt=Z.R;Z["class"]=Z.S;Z.dom=Z.H;Z.id=Z.U;Z.identifier=Z.I;Z.implicit=Z.V;
Z.link=function(a,b){b=(b||F(ma)).getElementsByTagName("a");for(var c=0;c<b.length;c++){var d=b[c],e=d,f="";kb&&"1.8"<=nb||lb||B?f=Fc(e,!1):e.textContent?f=e.textContent:e.innerText&&(f=e.innerText);e=f=f.replace(/\r\n|\r/g,"\n");e=e.replace(/\ +/g," ");f=new RegExp(String.fromCharCode(160),"g");if(lb)for(f=String.fromCharCode(160);-1!=e.indexOf(f);)e=e.replace(f," ");else e=e.replace(f," ");var f=e,e=va(f),g=a,f="glob",h=/^([a-zA-Z-]+):(.*)/.exec(g);if(h){var m=h[1],h=h[2];Ra[m.toLowerCase()]&&(f=
m.toLowerCase(),g=h)}m=Ra[f];if(!m)throw new Fa("Cannot find pattern matching strategy: "+f);"glob"==f?(g.indexOf("glob:")||(g=g.substring(5)),m=Ra.glob):"exact"!=f||g.indexOf("exact:")||(g=g.substring(6));g=ka(m,g);g.da=f;if(g(e))return d}return null};Z.name=Z.i;Z.stored=Z.$;Z.xpath=Z.P;function Ud(a,b,c,d){var e=Z[a];if(!e)throw new Fa("Unrecognised locator type: '"+a+"'");if(c=e.call(null,b,c))return c;if(!d)return null;for(e=0;e<d.frames.length;e++){try{var f=d.frames[e].document}catch(g){}if(f&&(c=Ud(a,b,f,d.frames[e])))return c}return null}function Td(a,b){for(var c=a.childNodes.length,d=0;d<c;d++){var e=a.childNodes[d];if(1==e.nodeType&&(b(e)||(e=Td(e,b))))return e}return null};var Vd=Vd||function(){};ca("_",function(a,b){if(l(a)){var c;(c=a.match(/^([A-Za-z]+)=.+/))?(c=c[1].toLowerCase(),c={type:c,string:a.substring(c.length+1)}):(c={string:"",type:""},c.string=a,c.type=a.lastIndexOf("//",0)?a.lastIndexOf("document.",0)?"identifier":"dom":"xpath");var d=ma||ma;c=Ud(c.type,c.string,d.document,d);if(!c)throw new Fa("Element "+a+" not found");a=c}Ac(a,yc);Ac(a,zc);d=kc(a,"maxlength");c=b;null!=d&&(d=parseInt(d,0),b.length>d&&(c=b.substr(0,d)));K(a,"BODY")?a.ownerDocument&&a.ownerDocument.designMode&&
"on"==(new String(a.ownerDocument.designMode)).toLowerCase()&&(a.innerHTML=c):kb&&Kb&&Jb(8)?Vd(a).value=c:a.value=c;try{Ac(a,xc)}catch(e){}});; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
